In [ ]:
import os
import pandas as pd
import numpy as np
import geopandas as gpd

def list_gpkg_layers(gpkg_path):
    try:
        layers_df = gpd.list_layers(gpkg_path)
        return layers_df["name"].tolist()
    except Exception as e:
        print(f"Не удалось получить список слоев для {gpkg_path}: {e}")
        return []

INPUT_GPKG = "moscow_realestate_before.gpkg"

if not os.path.exists(INPUT_GPKG):
    raise FileNotFoundError(
        f"Не найден исходный файл {INPUT_GPKG}."
    )

print("Слои в GPKG:")
input_layers = list_gpkg_layers(INPUT_GPKG)
print(input_layers if input_layers else "Список слоев не получен")

INPUT_LAYER = input_layers[0] if input_layers else None

OUTPUT_GPKG = "apartments_prepared.gpkg"
OUTPUT_LAYER = "apartments_prepared"
OUTPUT_CSV = "apartments_prepared.csv"

SOURCE_CRS = "EPSG:4326"
TARGET_CRS = "EPSG:32637"

PRICE_M2_LOW_Q = 0.01
PRICE_M2_HIGH_Q = 0.99

MIN_AREA = 15
MAX_AREA = 300

MAX_ROOMS = 8
MAX_FLOORS = 100

CURRENT_YEAR = 2026

gdf = gpd.read_file(INPUT_GPKG, layer=INPUT_LAYER)

print("Исходное количество строк:", len(gdf))
print("CRS исходного слоя:", gdf.crs)
print("Колонки:")
print(gdf.columns.tolist())

if "geometry" not in gdf.columns or gdf.geometry.isna().all():
    gdf = gpd.GeoDataFrame(
        gdf,
        geometry=gpd.points_from_xy(gdf["longitude"], gdf["latitude"]),
        crs=SOURCE_CRS
    )

if gdf.crs is None:
    gdf = gdf.set_crs(SOURCE_CRS)

required_cols = [
    "id",
    "price",
    "url",
    "total_area",
    "rooms_count",
    "floor_number",
    "floors_count",
    "address",
    "latitude",
    "longitude",
    "building_year",
    "material_type"
]

missing_cols = [col for col in required_cols if col not in gdf.columns]

if missing_cols:
    raise ValueError(f"В таблице не хватает колонок: {missing_cols}")

num_cols = [
    "price",
    "total_area",
    "rooms_count",
    "floor_number",
    "floors_count",
    "building_year",
    "latitude",
    "longitude"
]

for col in num_cols:
    gdf[col] = pd.to_numeric(gdf[col], errors="coerce")

n_before_technical = len(gdf)

gdf = gdf[
    (gdf["price"].notna()) &
    (gdf["total_area"].notna()) &
    (gdf["latitude"].notna()) &
    (gdf["longitude"].notna()) &
    (gdf["price"] > 0) &
    (gdf["total_area"] > 0)
].copy()

gdf.loc[gdf["floor_number"] <= 0, "floor_number"] = np.nan
gdf.loc[gdf["floors_count"] <= 0, "floors_count"] = np.nan
gdf.loc[gdf["floor_number"] > gdf["floors_count"], "floor_number"] = np.nan

gdf.loc[gdf["rooms_count"] < 0, "rooms_count"] = np.nan

n_after_technical = len(gdf)

print("\nТехническая чистка:")
print("Было строк:", n_before_technical)
print("Осталось строк:", n_after_technical)
print("Удалено:", n_before_technical - n_after_technical)

import re

MIN_AREA_PER_ROOM = 12

def parse_share_value(x):
    if pd.isna(x):
        return np.nan

    s = str(x).strip().lower()

    if s == "" or s in ["nan", "none", "null"]:
        return np.nan

    s = s.replace(",", ".")

    if "%" in s:
        s_num = re.sub(r"[^0-9.]", "", s)
        try:
            return float(s_num) / 100
        except:
            return np.nan

    if "/" in s:
        parts = s.split("/")
        if len(parts) == 2:
            try:
                numerator = float(parts[0])
                denominator = float(parts[1])
                if denominator != 0:
                    return numerator / denominator
            except:
                return np.nan

    try:
        return float(s)
    except:
        return np.nan

n_before_shares = len(gdf)

if "share_value" in gdf.columns:
    gdf["share_value_raw"] = gdf["share_value"]

    gdf["share_value_str"] = (
        gdf["share_value"]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    gdf["share_value_filled"] = ~(
        gdf["share_value"].isna() |
        gdf["share_value_str"].isin(["", "nan", "none", "null"])
    )

    gdf["share_value_num"] = gdf["share_value"].apply(parse_share_value)

    full_apartment_mask = (
        (~gdf["share_value_filled"]) |
        (np.isclose(gdf["share_value_num"], 1.0))
    )

    gdf = gdf[full_apartment_mask].copy()

gdf["area_per_room_tmp"] = np.where(
    gdf["rooms_count"] > 0,
    gdf["total_area"] / gdf["rooms_count"],
    np.nan
)

bad_share_like_mask = (
    gdf["rooms_count"].notna() &
    (gdf["rooms_count"] >= 2) &
    (gdf["area_per_room_tmp"] < MIN_AREA_PER_ROOM)
)

print("\nПодозрительных объектов по area_per_room:", bad_share_like_mask.sum())

gdf = gdf[~bad_share_like_mask].copy()
gdf = gdf.drop(columns=["area_per_room_tmp"])

n_after_shares = len(gdf)

print("\nУдаление долей / комнат:")
print("Было строк:", n_before_shares)
print("Осталось строк:", n_after_shares)
print("Удалено:", n_before_shares - n_after_shares)
print(
    "Доля удаленных:",
    round((n_before_shares - n_after_shares) / n_before_shares * 100, 2),
    "%"
)

gdf["price_m2"] = gdf["price"] / gdf["total_area"]

gdf["ln_price"] = np.log(gdf["price"])
gdf["ln_price_m2"] = np.log(gdf["price_m2"])

gdf["ln_total_area"] = np.log(gdf["total_area"])

gdf["area_per_room"] = np.where(
    gdf["rooms_count"] > 0,
    gdf["total_area"] / gdf["rooms_count"],
    np.nan
)

gdf["rooms_group"] = np.select(
    [
        gdf["rooms_count"] == 0,
        gdf["rooms_count"] == 1,
        gdf["rooms_count"] == 2,
        gdf["rooms_count"] == 3,
        gdf["rooms_count"] >= 4
    ],
    [
        "studio",
        "1_room",
        "2_rooms",
        "3_rooms",
        "4plus_rooms"
    ],
    default=None
)

gdf["floor_ratio"] = gdf["floor_number"] / gdf["floors_count"]

gdf["is_first_floor"] = np.where(gdf["floor_number"] == 1, 1, 0)

gdf["is_last_floor"] = np.where(
    gdf["floor_number"] == gdf["floors_count"],
    1,
    0
)

gdf["is_middle_floor"] = np.where(
    (gdf["floor_number"] > 1) &
    (gdf["floor_number"] < gdf["floors_count"]),
    1,
    0
)

floor_missing = gdf["floor_number"].isna() | gdf["floors_count"].isna()

gdf.loc[
    floor_missing,
    ["floor_ratio", "is_first_floor", "is_last_floor", "is_middle_floor"]
] = np.nan

gdf["floor_type"] = np.select(
    [
        gdf["is_first_floor"] == 1,
        gdf["is_last_floor"] == 1,
        gdf["is_middle_floor"] == 1
    ],
    [
        "first",
        "last",
        "middle"
    ],
    default=None
)

gdf["building_age"] = CURRENT_YEAR - gdf["building_year"]

gdf.loc[gdf["building_year"] < 1800, "building_age"] = np.nan
gdf.loc[gdf["building_year"] > CURRENT_YEAR, "building_age"] = np.nan

gdf["building_age_sq"] = gdf["building_age"] ** 2

n_before_outliers = len(gdf)

q_low = gdf["price_m2"].quantile(PRICE_M2_LOW_Q)
q_high = gdf["price_m2"].quantile(PRICE_M2_HIGH_Q)

gdf = gdf[
    (gdf["price_m2"] >= q_low) &
    (gdf["price_m2"] <= q_high)
].copy()

gdf = gdf[
    (gdf["total_area"] >= MIN_AREA) &
    (gdf["total_area"] <= MAX_AREA)
].copy()

gdf = gdf[
    (gdf["rooms_count"].isna()) |
    ((gdf["rooms_count"] >= 0) & (gdf["rooms_count"] <= MAX_ROOMS))
].copy()

gdf = gdf[
    (gdf["floors_count"].isna()) |
    ((gdf["floors_count"] >= 1) & (gdf["floors_count"] <= MAX_FLOORS))
].copy()

gdf = gdf[
    (gdf["floor_ratio"].isna()) |
    ((gdf["floor_ratio"] > 0) & (gdf["floor_ratio"] <= 1))
].copy()

n_after_outliers = len(gdf)

print("\nЧистка выбросов:")
print("Было строк:", n_before_outliers)
print("Осталось строк:", n_after_outliers)
print("Удалено:", n_before_outliers - n_after_outliers)
print(
    "Доля удаленных:",
    round((n_before_outliers - n_after_outliers) / n_before_outliers * 100, 2),
    "%"
)

print("\nГраницы price_m2:")
print("Нижняя граница:", round(q_low, 2))
print("Верхняя граница:", round(q_high, 2))

gdf["material_type_clean"] = (
    gdf["material_type"]
    .astype(str)
    .str.lower()
    .str.strip()
)

material_dummies = pd.get_dummies(
    gdf["material_type_clean"],
    prefix="material",
    dummy_na=False
)

gdf = pd.concat([gdf, material_dummies], axis=1)

gdf = gpd.GeoDataFrame(gdf, geometry="geometry", crs=gdf.crs)

gdf = gdf.to_crs(TARGET_CRS)

print("\nФинальное количество квартир:", len(gdf))
print("Финальный CRS:", gdf.crs)

print("\nОписание price_m2:")
print(gdf["price_m2"].describe())

print("\nОписание total_area:")
print(gdf["total_area"].describe())

print("\nОписание rooms_count:")
print(gdf["rooms_count"].describe())

print("\nОписание floor_ratio:")
print(gdf["floor_ratio"].describe())

if os.path.exists(OUTPUT_GPKG):
    os.remove(OUTPUT_GPKG)

gdf.to_file(
    OUTPUT_GPKG,
    layer=OUTPUT_LAYER,
    driver="GPKG"
)

gdf.drop(columns="geometry").to_csv(
    OUTPUT_CSV,
    index=False
)

print("\nГотово.")
print(f"GPKG сохранен: {OUTPUT_GPKG}, слой: {OUTPUT_LAYER}")
print(f"CSV сохранен: {OUTPUT_CSV}")

Слои в GPKG:
['moscow_realestate_1__merged']
Исходное количество строк: 33536
CRS исходного слоя: EPSG:32637
Колонки:
['id', 'price', 'url', 'total_area', 'rooms_count', 'floor_number', 'floors_count', 'address', 'latitude', 'longitude', 'building_year', 'material_type', 'share_value', 'layer', 'path', 'geometry']

Техническая чистка:
Было строк: 33536
Осталось строк: 33536
Удалено: 0

Подозрительных объектов по area_per_room: 69

Удаление долей / комнат:
Было строк: 33536
Осталось строк: 32984
Удалено: 552
Доля удаленных: 1.65 %

Чистка выбросов:
Было строк: 32984
Осталось строк: 31614
Удалено: 1370
Доля удаленных: 4.15 %

Границы price_m2:
Нижняя граница: 75000.0
Верхняя граница: 2182029.31

Финальное количество квартир: 31614
Финальный CRS: EPSG:32637

Описание price_m2:
count    3.161400e+04
mean     5.056260e+05
std      2.926250e+05
min      7.500000e+04
25%      3.251149e+05
50%      4.182911e+05
75%      5.816044e+05
max      2.181818e+06
Name: price_m2, dtype: float64

Описание total_area:
count    31614.000000
mean        73.315329
std         46.315585
min         15.000000
25%         42.800000
50%         60.000000
75%         85.000000
max        300.000000
Name: total_area, dtype: float64

Описание rooms_count:
count    29288.000000
mean         2.472753
std          1.095817
min          1.000000
25%          2.000000
50%          2.000000
75%          3.000000
max          6.000000
Name: rooms_count, dtype: float64

Описание floor_ratio:
count    31605.000000
mean         0.534325
std          0.286165
min          0.027027
25%          0.285714
50%          0.526316
75%          0.777778
max          1.000000
Name: floor_ratio, dtype: float64

Готово.
GPKG сохранен: apartments_prepared.gpkg, слой: apartments_prepared
CSV сохранен: apartments_prepared.csv

In [ ]:
import os
import geopandas as gpd

INPUT_GPKG = "apartments_prepared.gpkg"
INPUT_LAYER = "apartments_prepared"

OUTPUT_GPKG = "apartments_model_base.gpkg"
OUTPUT_LAYER = "apartments_model_base"
OUTPUT_CSV = "apartments_model_base.csv"

if not os.path.exists(INPUT_GPKG):
    raise FileNotFoundError(
        f"Не найден промежуточный файл {INPUT_GPKG}."
    )

apartments = gpd.read_file(
    INPUT_GPKG,
    layer=INPUT_LAYER
)

print("Исходное количество квартир:", len(apartments))
print("CRS:", apartments.crs)
print("Колонки:")
print(apartments.columns.tolist())

required_cols = [
    "id",
    "price",
    "price_m2",
    "ln_price_m2",
    "total_area",
    "rooms_count",
    "floor_number",
    "floors_count",
    "building_year",
    "material_type",
    "geometry"
]

missing_cols = [
    col for col in required_cols
    if col not in apartments.columns
]

if missing_cols:
    raise ValueError(f"Не хватает колонок: {missing_cols}")

model_base_cols = [
    "id",
    "price",
    "price_m2",
    "ln_price_m2",
    "total_area",
    "rooms_count",
    "floor_number",
    "floors_count",
    "building_year",
    "material_type",
    "geometry"
]

optional_check_cols = [
    "url",
    "address",
    "latitude",
    "longitude",
    "ln_price",
    "ln_total_area",
    "area_per_room",
    "floor_ratio",
    "is_first_floor",
    "is_last_floor",
    "is_middle_floor",
    "building_age",
    "building_age_sq",
    "rooms_group",
    "floor_type"
]

existing_optional_cols = [
    col for col in optional_check_cols
    if col in apartments.columns
]

final_cols = [
    col for col in model_base_cols
    if col != "geometry"
] + existing_optional_cols + ["geometry"]

apartments_base = apartments[final_cols].copy()

print("\nИтоговое количество квартир:", len(apartments_base))
print("Итоговые колонки:")
print(apartments_base.columns.tolist())

print("\nПервые строки:")
print(
    apartments_base[
        [
            "id",
            "price",
            "price_m2",
            "ln_price_m2",
            "total_area",
            "rooms_count",
            "floor_number",
            "floors_count",
            "building_year",
            "material_type"
        ]
    ].head()
)

if os.path.exists(OUTPUT_GPKG):
    os.remove(OUTPUT_GPKG)

apartments_base.to_file(
    OUTPUT_GPKG,
    layer=OUTPUT_LAYER,
    driver="GPKG"
)

apartments_base.drop(columns="geometry").to_csv(
    OUTPUT_CSV,
    index=False
)

print("\nГотово.")
print(f"GPKG сохранен: {OUTPUT_GPKG}, слой: {OUTPUT_LAYER}")
print(f"CSV сохранен: {OUTPUT_CSV}")

Исходное количество квартир: 31614
CRS: EPSG:32637
Колонки:
['id', 'price', 'url', 'total_area', 'rooms_count', 'floor_number', 'floors_count', 'address', 'latitude', 'longitude', 'building_year', 'material_type', 'share_value', 'layer', 'path', 'share_value_raw', 'share_value_str', 'share_value_filled', 'share_value_num', 'price_m2', 'ln_price', 'ln_price_m2', 'ln_total_area', 'area_per_room', 'rooms_group', 'floor_ratio', 'is_first_floor', 'is_last_floor', 'is_middle_floor', 'floor_type', 'building_age', 'building_age_sq', 'material_type_clean', 'material_aerocreteblock', 'material_block', 'material_brick', 'material_monolith', 'material_monolithbrick', 'material_none', 'material_old', 'material_panel', 'material_stalin', 'material_wood', 'geometry']

Итоговое количество квартир: 31614
Итоговые колонки:
['id', 'price', 'price_m2', 'ln_price_m2', 'total_area', 'rooms_count', 'floor_number', 'floors_count', 'building_year', 'material_type', 'url', 'address', 'latitude', 'longitude', 'ln_price', 'ln_total_area', 'area_per_room', 'floor_ratio', 'is_first_floor', 'is_last_floor', 'is_middle_floor', 'building_age', 'building_age_sq', 'rooms_group', 'floor_type', 'geometry']

Первые строки:
          id    price       price_m2  ln_price_m2  total_area  rooms_count  \
0  322414832  3900000   87053.571429    11.374279        44.8          2.0
1  317613685  4500000  107142.857143    11.581918        42.0          2.0
2  324479701  8900000  148333.333333    11.907217        60.0          3.0
3  323361010  7600000   80851.063830    11.300364        94.0          5.0
4  314647306  6500000   81250.000000    11.305286        80.0          4.0

   floor_number  floors_count  building_year material_type
0           7.0           9.0         1976.0         panel
1           8.0           9.0            NaN         panel
2           1.0           9.0         1968.0         panel
3           1.0           5.0         1957.0         brick
4           3.0           5.0         1929.0         brick

Готово.
GPKG сохранен: apartments_model_base.gpkg, слой: apartments_model_base
CSV сохранен: apartments_model_base.csv

In [ ]:
import os
import numpy as np
import geopandas as gpd

def list_gpkg_layers(gpkg_path):
    try:
        layers_df = gpd.list_layers(gpkg_path)
        return layers_df["name"].tolist()
    except Exception as e:
        print(f"Не удалось получить список слоев для {gpkg_path}: {e}")
        return []

APARTMENTS_GPKG = "apartments_model_base.gpkg"
APARTMENTS_LAYER = "apartments_model_base"

HEX_GPKG_CANDIDATES = [
    "moscow_hex_zones_two_variants_activity_4blocks_FINAL-2.gpkg",
    "/mnt/data/moscow_hex_zones_two_variants_activity_4blocks_FINAL-2.gpkg",
]

HEX_GPKG = next(
    (path for path in HEX_GPKG_CANDIDATES if os.path.exists(path)),
    HEX_GPKG_CANDIDATES[0]
)

HEX_LAYER = "zones_two_variants_final"
HEX_ZONE_COLUMN = "zone_final_4blocks"

OUTPUT_GPKG = "apartments_with_zones.gpkg"
OUTPUT_LAYER = "apartments_with_zones"
OUTPUT_CSV = "apartments_with_zones.csv"

if not os.path.exists(APARTMENTS_GPKG):
    raise FileNotFoundError(
        f"Не найден промежуточный файл {APARTMENTS_GPKG}."
    )

if not os.path.exists(HEX_GPKG):
    raise FileNotFoundError(
        f"Не найден файл зонирования {HEX_GPKG}."
    )

def harmonize_zone_layer(hexes):
    hexes = hexes.copy()

    if "hex_id" not in hexes.columns:
        if "id" in hexes.columns:
            hexes["hex_id"] = hexes["id"]
        else:
            hexes["hex_id"] = np.arange(len(hexes))

    if HEX_ZONE_COLUMN in hexes.columns:
        hexes["zone_name"] = hexes[HEX_ZONE_COLUMN]
    elif "zone_final" in hexes.columns:
        hexes["zone_name"] = hexes["zone_final"]
        print("поле zone_final_4blocks не найдено")
    elif "zone_name" in hexes.columns:
        hexes["zone_name"] = hexes["zone_name"]
        print("поле zone_final_4blocks не найдено")
    else:
        raise ValueError(
            "В слое гексагонов нет zone_final_4blocks, zone_final или zone_name. "
            f"Колонки слоя: {hexes.columns.tolist()}"
        )

    hexes["zone_name"] = (
        hexes["zone_name"]
        .astype(str)
        .str.strip()
        .str.lower()
        .str.replace("-", "_", regex=False)
        .str.replace(" ", "_", regex=False)
    )

    zone_aliases = {
        "центр": "core",
        "core": "core",
        "ядро": "core",
        "main_core": "core",
        "semi_periphery": "semi_periphery",
        "semiperiphery": "semi_periphery",
        "полупериферия": "semi_periphery",
        "intermediate": "semi_periphery",
        "intermediate_areas": "semi_periphery",
        "periphery": "periphery",
        "периферия": "periphery",
        "non_urban": "non_urban",
        "nonurban": "non_urban",
        "nan": np.nan,
        "none": np.nan,
    }
    hexes["zone_name"] = hexes["zone_name"].replace(zone_aliases)

    zone_rank_map = {
        "periphery": 0,
        "semi_periphery": 1,
        "core": 2,
    }
    hexes["zone_rank"] = hexes["zone_name"].map(zone_rank_map)

    print("\nРаспределение гексагонов после приведения нового зонирования:")
    print(hexes["zone_name"].value_counts(dropna=False))

    unexpected = sorted(
        set(hexes["zone_name"].dropna().unique())
        - {"core", "semi_periphery", "periphery", "non_urban"}
    )
    if unexpected:
        print("\n неожиданные названия зон:", unexpected)

    return hexes

def drop_old_zone_columns(gdf):
    old_zone_cols = [
        "hex_id",
        "zone_name",
        "zone_rank",
        "zone_core",
        "zone_semi_periphery",
    ]
    cols_to_drop = [col for col in old_zone_cols if col in gdf.columns]

    if cols_to_drop:
        print(cols_to_drop)
        gdf = gdf.drop(columns=cols_to_drop)

    return gdf

print("Слои в файле квартир:")
print(list_gpkg_layers(APARTMENTS_GPKG))

print("\nСлои в файле гексагонов:")
print(list_gpkg_layers(HEX_GPKG))

apartments = gpd.read_file(
    APARTMENTS_GPKG,
    layer=APARTMENTS_LAYER
)

hexes = gpd.read_file(
    HEX_GPKG,
    layer=HEX_LAYER
)

hexes = harmonize_zone_layer(hexes)
apartments = drop_old_zone_columns(apartments)

print("\nКвартир:", len(apartments))
print("CRS квартир:", apartments.crs)

print("\nГексагонов:", len(hexes))
print("CRS гексагонов:", hexes.crs)

print("\nКолонки квартир:")
print(apartments.columns.tolist())

print("\nКолонки гексагонов:")
print(hexes.columns.tolist())

required_apartment_cols = [
    "id",
    "price",
    "price_m2",
    "ln_price_m2",
    "total_area",
    "rooms_count",
    "floor_number",
    "floors_count",
    "building_year",
    "material_type",
    "geometry"
]

required_hex_cols = [
    "hex_id",
    "zone_name",
    "zone_rank",
    "geometry"
]

missing_apartment_cols = [
    col for col in required_apartment_cols
    if col not in apartments.columns
]

missing_hex_cols = [
    col for col in required_hex_cols
    if col not in hexes.columns
]

if missing_apartment_cols:
    raise ValueError(f"В слое квартир не хватает колонок: {missing_apartment_cols}")

if missing_hex_cols:
    raise ValueError(f"В слое гексагонов не хватает колонок: {missing_hex_cols}")

hexes = hexes.to_crs(apartments.crs)

print("\nCRS после приведения:")
print("Квартиры:", apartments.crs)
print("Гексагоны:", hexes.crs)

hexes_small = hexes[
    [
        "hex_id",
        "zone_name",
        "zone_rank",
        "geometry"
    ]
].copy()

hexes_small["zone_name"] = (
    hexes_small["zone_name"]
    .astype(str)
    .str.strip()
    .str.lower()
)

print("\nРаспределение гексагонов по зонам:")
print(hexes_small["zone_name"].value_counts(dropna=False))

print("\nПроверка zone_rank:")
print(
    hexes_small[
        ["zone_name", "zone_rank"]
    ]
    .drop_duplicates()
    .sort_values("zone_rank")
)

apartments_zoned = gpd.sjoin(
    apartments,
    hexes_small,
    how="left",
    predicate="within"
)

if "index_right" in apartments_zoned.columns:
    apartments_zoned = apartments_zoned.drop(columns=["index_right"])

apartments_zoned["zone_core"] = np.where(
    apartments_zoned["zone_name"] == "core",
    1,
    0
)

apartments_zoned["zone_semi_periphery"] = np.where(
    apartments_zoned["zone_name"] == "semi_periphery",
    1,
    0
)

zone_missing = apartments_zoned["zone_name"].isna()

apartments_zoned.loc[
    zone_missing,
    ["zone_rank", "zone_core", "zone_semi_periphery"]
] = np.nan

print("\nКвартир после spatial join:", len(apartments_zoned))

print("\nРаспределение квартир по зонам:")
print(apartments_zoned["zone_name"].value_counts(dropna=False))

missing_zone_count = apartments_zoned["zone_name"].isna().sum()
missing_zone_share = apartments_zoned["zone_name"].isna().mean() * 100

print("\nКвартир без зоны:", missing_zone_count)
print("Доля квартир без зоны:", round(missing_zone_share, 2), "%")

print("\nПроверка кодировки зон:")
print(
    apartments_zoned[
        [
            "zone_name",
            "zone_rank",
            "zone_core",
            "zone_semi_periphery"
        ]
    ]
    .drop_duplicates()
    .sort_values(["zone_rank", "zone_name"])
)

n_before_filter = len(apartments_zoned)

apartments_zoned = apartments_zoned[
    apartments_zoned["zone_name"].isin(
        ["periphery", "semi_periphery", "core"]
    )
].copy()

n_after_filter = len(apartments_zoned)

print("\nФильтр по зонам:")
print("Было:", n_before_filter)
print("Осталось:", n_after_filter)
print("Удалено:", n_before_filter - n_after_filter)

main_cols = [
    "id",
    "price",
    "price_m2",
    "ln_price_m2",
    "total_area",
    "rooms_count",
    "floor_number",
    "floors_count",
    "building_year",
    "material_type",
    "hex_id",
    "zone_name",
    "zone_rank",
    "zone_core",
    "zone_semi_periphery",
    "geometry"
]

extra_cols = [
    col for col in apartments_zoned.columns
    if col not in main_cols
]

ordered_cols = [
    col for col in main_cols
    if col != "geometry"
] + extra_cols + ["geometry"]

apartments_zoned = apartments_zoned[ordered_cols].copy()

if os.path.exists(OUTPUT_GPKG):
    os.remove(OUTPUT_GPKG)

apartments_zoned.to_file(
    OUTPUT_GPKG,
    layer=OUTPUT_LAYER,
    driver="GPKG"
)

apartments_zoned.drop(columns="geometry").to_csv(
    OUTPUT_CSV,
    index=False
)

print("\nГотово.")
print(f"GPKG сохранен: {OUTPUT_GPKG}, слой: {OUTPUT_LAYER}")
print(f"CSV сохранен: {OUTPUT_CSV}")

Слои в файле квартир:
['apartments_model_base']

Слои в файле гексагонов:
['zones_two_variants_final']

Распределение гексагонов после приведения нового зонирования:
zone_name
periphery         989
semi_periphery    325
core               99
non_urban          54
Name: count, dtype: int64

Квартир: 31614
CRS квартир: EPSG:32637

Гексагонов: 1467
CRS гексагонов: EPSG:32637

Колонки квартир:
['apt_uid', 'id', 'price', 'price_m2', 'ln_price_m2', 'total_area', 'rooms_count', 'floor_number', 'floors_count', 'building_year', 'material_type', 'url', 'address', 'latitude', 'longitude', 'ln_price', 'ln_total_area', 'area_per_room', 'floor_ratio', 'is_first_floor', 'is_last_floor', 'is_middle_floor', 'building_age', 'building_age_sq', 'rooms_group', 'floor_type', 'geometry']

Колонки гексагонов:
['id', 'left', 'top', 'right', 'bottom', 'row_index', 'col_index', 'hex_id', 'manual_class', 'manual_class_norm', 'is_non_urban', 'is_model_area', 'L_social', 'L_services', 'L_transport', 'L_activity', 'z_L_activity_for_activity_variant', 'functional_index_activity_raw', 'functional_index_activity_for_model', 'gmm_label_activity', 'gmm_max_proba_activity', 'zone_gmm_activity', 'zone_final_activity', 'activity_semi_threshold_quantile', 'activity_core_threshold_quantile', 'activity_semi_threshold_value', 'activity_core_threshold_value', 'L_sum_4blocks_raw', 'z_L_social_4blocks', 'z_L_services_4blocks', 'z_L_transport_4blocks', 'z_L_activity_4blocks', 'L_sum_4blocks_z', 'L_mean_4blocks_z', 'functional_index_4blocks_raw', 'functional_index_4blocks_for_model', 'gmm_label_4blocks', 'gmm_max_proba_4blocks', 'zone_gmm_4blocks', 'zone_final_4blocks', '4blocks_semi_threshold_quantile', '4blocks_core_threshold_quantile', '4blocks_semi_threshold_value', '4blocks_core_threshold_value', 'geometry', 'zone_name', 'zone_rank']

CRS после приведения:
Квартиры: EPSG:32637
Гексагоны: EPSG:32637

Распределение гексагонов по зонам:
zone_name
periphery         989
semi_periphery    325
core               99
non_urban          54
Name: count, dtype: int64

Проверка zone_rank:
          zone_name  zone_rank
0         periphery        0.0
335  semi_periphery        1.0
598            core        2.0
176       non_urban        NaN

Квартир после spatial join: 31614

Распределение квартир по зонам:
zone_name
periphery         13256
semi_periphery    12502
core               5812
NaN                  35
non_urban             9
Name: count, dtype: int64

Квартир без зоны: 35
Доля квартир без зоны: 0.11 %

Проверка кодировки зон:
            zone_name  zone_rank  zone_core  zone_semi_periphery
0           periphery        0.0        0.0                  0.0
3      semi_periphery        1.0        0.0                  1.0
38               core        2.0        1.0                  0.0
13509       non_urban        NaN        0.0                  0.0
2340              NaN        NaN        NaN                  NaN

Фильтр по зонам:
Было: 31614
Осталось: 31570
Удалено: 44

Готово.
GPKG сохранен: apartments_with_zones.gpkg, слой: apartments_with_zones
CSV сохранен: apartments_with_zones.csv

In [ ]:
import os
import geopandas as gpd

if not os.path.exists("apartments_prepared.gpkg"):
    raise FileNotFoundError("Не найден apartments_prepared.gpkg.")

prepared = gpd.read_file(
    "apartments_prepared.gpkg",
    layer="apartments_prepared"
)

print("Квартир в apartments_prepared:", len(prepared))
print(prepared[["price_m2", "total_area", "rooms_count", "area_per_room"]].describe())

Квартир в apartments_prepared: 31614
           price_m2    total_area   rooms_count  area_per_room
count  3.161400e+04  31614.000000  29288.000000   29288.000000
mean   5.056260e+05     73.315329      2.472753      31.164758
std    2.926250e+05     46.315585      1.095817       9.573635
min    7.500000e+04     15.000000      1.000000      12.500000
25%    3.251149e+05     42.800000      2.000000      24.333333
50%    4.182911e+05     60.000000      2.000000      29.100000
75%    5.816044e+05     85.000000      3.000000      36.600000
max    2.181818e+06    300.000000      6.000000     149.000000

In [ ]:
import os
import re
import warnings
import numpy as np
import pandas as pd
import geopandas as gpd

def list_gpkg_layers(gpkg_path):
    try:
        layers_df = gpd.list_layers(gpkg_path)
        return layers_df["name"].tolist()
    except Exception as e:
        print(f"Не удалось получить список слоев для {gpkg_path}: {e}")
        return []

warnings.filterwarnings("ignore")

TARGET_CRS = "EPSG:32637"
SOURCE_CRS_IF_MISSING = "EPSG:4326"

APARTMENTS_PREPARED_GPKG = "apartments_prepared.gpkg"
APARTMENTS_PREPARED_LAYER = "apartments_prepared"

HEX_GPKG_CANDIDATES = [
    "moscow_hex_zones_two_variants_activity_4blocks_FINAL-2.gpkg",
    "/mnt/data/moscow_hex_zones_two_variants_activity_4blocks_FINAL-2.gpkg",
]

HEX_GPKG = next(
    (path for path in HEX_GPKG_CANDIDATES if os.path.exists(path)),
    HEX_GPKG_CANDIDATES[0]
)

HEX_LAYER = "zones_two_variants_final"
HEX_ZONE_COLUMN = "zone_final_4blocks"

APARTMENTS_MODEL_BASE_GPKG = "apartments_model_base.gpkg"
APARTMENTS_MODEL_BASE_LAYER = "apartments_model_base"

APARTMENTS_WITH_ZONES_GPKG = "apartments_with_zones.gpkg"
APARTMENTS_WITH_ZONES_LAYER = "apartments_with_zones"

OUTPUT_GPKG = "apartments_hedonic_features.gpkg"
OUTPUT_LAYER = "apartments_hedonic_features"
OUTPUT_CSV = "apartments_hedonic_features.csv"

PROCESSED_LAYERS_GPKG = "processed_external_layers.gpkg"
SAVE_PROCESSED_LAYERS = True

LAYER_PATHS = {

    "mcd": {
        "gpkg": "moscow_mcd.gpkg",
        "layer": None
    },
    "metro_mcc": {
        "gpkg": "moscow_metro_mck.gpkg",
        "layer": None
    },
    "stops": {
        "gpkg": "public_transport_stops.gpkg",
        "layer": None
    },

    "social": {
        "gpkg": "moscow_social_infr.gpkg",
        "layer": None
    },
    "parks": {
        "gpkg": "moscow_parks.gpkg",
        "layer": None
    },
    "rivers": {
        "gpkg": "moscow_rivers.gpkg",
        "layer": None
    },

    "highway": {
        "gpkg": "moscow_highway.gpkg",
        "layer": None
    },
    "railway": {
        "gpkg": "moscow_railway.gpkg",
        "layer": None
    },
    "industrial": {
        "gpkg": "moscow_industrial_areas_filtered.gpkg",
        "layer": None
    },
    "aerodromes": {
        "gpkg": "moscow_aerodromes.gpkg",
        "layer": None
    },
    "waste": {
        "gpkg": "moscow_waste_facilities.gpkg",
        "layer": None
    },
    "cemeteries": {
        "gpkg": "moscow_cemeteries.gpkg",
        "layer": None
    },
}

def pick_layer(gpkg_path, preferred_layer=None):
    layers = list_gpkg_layers(gpkg_path)

    if preferred_layer is not None:
        if layers and preferred_layer not in layers:
            raise ValueError(
                f"В файле {gpkg_path} нет слоя '{preferred_layer}'. "
                f"Доступные слои: {layers}"
            )
        return preferred_layer

    if len(layers) > 0:
        return layers[0]

    print(f"Список слоев для {gpkg_path} не получен, будет прочитан первый слой GPKG.")
    return None

def read_gpkg_auto(gpkg_path, layer=None, label=None):
    if not os.path.exists(gpkg_path):
        raise FileNotFoundError(f"Не найден файл: {gpkg_path}")

    layer_to_read = pick_layer(gpkg_path, layer)

    gdf = gpd.read_file(gpkg_path, layer=layer_to_read)

    print("\n" + "=" * 70)
    print(f"Загружен слой: {label if label else gpkg_path}")
    print("Файл:", gpkg_path)
    print("Слой:", layer_to_read)
    print("Количество объектов:", len(gdf))
    print("CRS:", gdf.crs)
    print("Типы геометрии:")
    print(gdf.geom_type.value_counts(dropna=False))

    return gdf

def harmonize_zone_layer(hexes):
    hexes = hexes.copy()

    if "hex_id" not in hexes.columns:
        if "id" in hexes.columns:
            hexes["hex_id"] = hexes["id"]
        else:
            hexes["hex_id"] = np.arange(len(hexes))

    if HEX_ZONE_COLUMN in hexes.columns:
        hexes["zone_name"] = hexes[HEX_ZONE_COLUMN]
    elif "zone_final" in hexes.columns:
        hexes["zone_name"] = hexes["zone_final"]
        print("поле zone_final_4blocks не найдено")
    elif "zone_name" in hexes.columns:
        hexes["zone_name"] = hexes["zone_name"]
        print("поле zone_final_4blocks не найдено")
    else:
        raise ValueError(
            "В слое гексагонов нет zone_final_4blocks, zone_final или zone_name. "
            f"Колонки слоя: {hexes.columns.tolist()}"
        )

    hexes["zone_name"] = (
        hexes["zone_name"]
        .astype(str)
        .str.strip()
        .str.lower()
        .str.replace("-", "_", regex=False)
        .str.replace(" ", "_", regex=False)
    )

    zone_aliases = {
        "центр": "core",
        "core": "core",
        "ядро": "core",
        "main_core": "core",
        "semi_periphery": "semi_periphery",
        "semiperiphery": "semi_periphery",
        "полупериферия": "semi_periphery",
        "intermediate": "semi_periphery",
        "intermediate_areas": "semi_periphery",
        "periphery": "periphery",
        "периферия": "periphery",
        "non_urban": "non_urban",
        "nonurban": "non_urban",
        "nan": np.nan,
        "none": np.nan,
    }
    hexes["zone_name"] = hexes["zone_name"].replace(zone_aliases)

    zone_rank_map = {
        "periphery": 0,
        "semi_periphery": 1,
        "core": 2,
    }
    hexes["zone_rank"] = hexes["zone_name"].map(zone_rank_map)

    print("\nРаспределение гексагонов после приведения нового зонирования:")
    print(hexes["zone_name"].value_counts(dropna=False))

    unexpected = sorted(
        set(hexes["zone_name"].dropna().unique())
        - {"core", "semi_periphery", "periphery", "non_urban"}
    )
    if unexpected:
        print("\n найдены неожиданные названия зон:", unexpected)

    return hexes

def drop_old_zone_columns(gdf):
    old_zone_cols = [
        "hex_id",
        "zone_name",
        "zone_rank",
        "zone_core",
        "zone_semi_periphery",
    ]
    cols_to_drop = [col for col in old_zone_cols if col in gdf.columns]

    if cols_to_drop:
        print(cols_to_drop)
        gdf = gdf.drop(columns=cols_to_drop)

    return gdf

def guess_and_set_crs(gdf, target_crs=TARGET_CRS):
    if gdf.crs is not None:
        return gdf

    bounds = gdf.total_bounds
    minx, miny, maxx, maxy = bounds

    if -180 <= minx <= 180 and -180 <= maxx <= 180 and -90 <= miny <= 90 and -90 <= maxy <= 90:
        gdf = gdf.set_crs(SOURCE_CRS_IF_MISSING)
        print("CRS отсутствовал. Установлен EPSG:4326.")
    else:
        gdf = gdf.set_crs(target_crs)
        print(f"CRS отсутствовал. Установлен {target_crs}.")

    return gdf

def prepare_layer(gdf, target_crs=TARGET_CRS, make_valid=True):
    gdf = gdf.copy()

    if "geometry" not in gdf.columns:
        raise ValueError("В слое нет geometry.")

    gdf = gdf[gdf.geometry.notna()].copy()
    gdf = gdf[~gdf.geometry.is_empty].copy()

    gdf = guess_and_set_crs(gdf, target_crs=target_crs)
    gdf = gdf.to_crs(target_crs)

    if make_valid:
        try:
            gdf["geometry"] = gdf.geometry.make_valid()
        except Exception:

            try:
                gdf["geometry"] = gdf.geometry.buffer(0)
            except Exception:
                pass

    gdf = gdf[gdf.geometry.notna()].copy()
    gdf = gdf[~gdf.geometry.is_empty].copy()

    try:
        gdf = gdf.explode(index_parts=False).reset_index(drop=True)
    except TypeError:
        gdf = gdf.explode().reset_index(drop=True)

    return gdf

def save_layer(gdf, gpkg_path, layer_name, remove_file=False):
    if remove_file and os.path.exists(gpkg_path):
        os.remove(gpkg_path)

    gdf.to_file(
        gpkg_path,
        layer=layer_name,
        driver="GPKG"
    )

def add_nearest_distance(apartments_gdf, feature_gdf, output_col):
    apartments_gdf = apartments_gdf.copy()

    if feature_gdf is None or len(feature_gdf) == 0:
        apartments_gdf[output_col] = np.nan
        print(f"{output_col}: слой пустой, записан NaN.")
        return apartments_gdf

    left = apartments_gdf[["apt_uid", "geometry"]].copy()
    right = feature_gdf[["geometry"]].copy()

    nearest = gpd.sjoin_nearest(
        left,
        right,
        how="left",
        distance_col=output_col
    )

    dist = (
        nearest
        .groupby("apt_uid")[output_col]
        .min()
        .reset_index()
    )

    apartments_gdf = apartments_gdf.merge(
        dist,
        on="apt_uid",
        how="left"
    )

    print(f"{output_col}: добавлено.")
    return apartments_gdf

def add_dummy_from_distance(apartments_gdf, distance_col, threshold_m, output_col):
    apartments_gdf[output_col] = np.where(
        apartments_gdf[distance_col].notna() &
        (apartments_gdf[distance_col] <= threshold_m),
        1,
        0
    ).astype(int)

    print(f"{output_col}: создано по {distance_col} <= {threshold_m} м.")
    return apartments_gdf

def add_points_count_within_radius(apartments_gdf, points_gdf, radius_m, output_col):
    apartments_gdf = apartments_gdf.copy()

    if points_gdf is None or len(points_gdf) == 0:
        apartments_gdf[output_col] = 0
        print(f"{output_col}: слой пустой, записан 0.")
        return apartments_gdf

    buffers = apartments_gdf[["apt_uid", "geometry"]].copy()
    buffers["geometry"] = buffers.geometry.buffer(radius_m)

    joined = gpd.sjoin(
        buffers,
        points_gdf[["geometry"]],
        how="left",
        predicate="contains"
    )

    counts = (
        joined
        .dropna(subset=["index_right"])
        .groupby("apt_uid")
        .size()
        .reset_index(name=output_col)
    )

    apartments_gdf = apartments_gdf.merge(
        counts,
        on="apt_uid",
        how="left"
    )

    apartments_gdf[output_col] = apartments_gdf[output_col].fillna(0).astype(int)

    print(f"{output_col}: посчитано в радиусе {radius_m} м.")
    return apartments_gdf

def add_polygon_area_within_radius(apartments_gdf, polygons_gdf, radius_m, output_col):
    apartments_gdf = apartments_gdf.copy()

    if polygons_gdf is None or len(polygons_gdf) == 0:
        apartments_gdf[output_col] = 0.0
        print(f"{output_col}: слой пустой, записан 0.")
        return apartments_gdf

    polygons_gdf = polygons_gdf[polygons_gdf.geometry.type.isin(["Polygon", "MultiPolygon"])].copy()

    if len(polygons_gdf) == 0:
        apartments_gdf[output_col] = 0.0
        print(f"{output_col}: в слое нет полигонов, записан 0.")
        return apartments_gdf

    buffers = apartments_gdf[["apt_uid", "geometry"]].copy()
    buffers["geometry"] = buffers.geometry.buffer(radius_m)

    joined = gpd.sjoin(
        buffers,
        polygons_gdf[["geometry"]],
        how="inner",
        predicate="intersects"
    )

    if len(joined) == 0:
        apartments_gdf[output_col] = 0.0
        print(f"{output_col}: пересечений нет, записан 0.")
        return apartments_gdf

    right_geom = (
        polygons_gdf[["geometry"]]
        .reset_index()
        .rename(columns={"index": "index_right", "geometry": "right_geometry"})
    )

    joined = joined.merge(
        right_geom,
        on="index_right",
        how="left"
    )

    joined["intersection_area"] = joined.apply(
        lambda row: row.geometry.intersection(row.right_geometry).area
        if row.right_geometry is not None else 0,
        axis=1
    )

    areas = (
        joined
        .groupby("apt_uid")["intersection_area"]
        .sum()
        .reset_index(name=output_col)
    )

    apartments_gdf = apartments_gdf.merge(
        areas,
        on="apt_uid",
        how="left"
    )

    apartments_gdf[output_col] = apartments_gdf[output_col].fillna(0.0)

    print(f"{output_col}: площадь посчитана в радиусе {radius_m} м.")
    return apartments_gdf

def standardize_social_layer(social_gdf):
    social_gdf = social_gdf.copy()

    possible_cols = [
        "subcategory",
        "amenity",
        "healthcare",
        "building",
        "name",
        "type"
    ]

    existing = [col for col in possible_cols if col in social_gdf.columns]

    if len(existing) == 0:
        raise ValueError(
            "В social-слое нет полей subcategory/amenity/healthcare/name/type, "
            "по которым можно определить школы, сады и медицину."
        )

    combined = pd.Series("", index=social_gdf.index, dtype="object")

    for col in existing:
        combined = combined + " " + social_gdf[col].astype(str).str.lower().fillna("")

    social_gdf["subcategory_std"] = np.nan

    school_mask = combined.str.contains(
        r"\bschool\b|школ|лицей|гимназ",
        regex=True,
        na=False
    )

    kindergarten_mask = combined.str.contains(
        r"\bkindergarten\b|детск|сад",
        regex=True,
        na=False
    )

    clinic_mask = combined.str.contains(
        r"\bclinic\b|\bhospital\b|\bdoctors\b|\bdentist\b|поликлин|больниц|медицин|clinic|hospital",
        regex=True,
        na=False
    )

    social_gdf.loc[school_mask, "subcategory_std"] = "school"
    social_gdf.loc[kindergarten_mask, "subcategory_std"] = "kindergarten"
    social_gdf.loc[clinic_mask, "subcategory_std"] = "clinic"

    social_gdf = social_gdf[social_gdf["subcategory_std"].notna()].copy()

    print("\nСоциальная инфраструктура после классификации:")
    print(social_gdf["subcategory_std"].value_counts(dropna=False))

    return social_gdf

def get_social_subset(social_gdf, category):
    return social_gdf[social_gdf["subcategory_std"] == category].copy()

apartments = read_gpkg_auto(
    APARTMENTS_PREPARED_GPKG,
    APARTMENTS_PREPARED_LAYER,
    label="очищенные квартиры"
)

apartments = prepare_layer(apartments, target_crs=TARGET_CRS)

required_apartment_cols = [
    "id",
    "price",
    "price_m2",
    "ln_price_m2",
    "total_area",
    "rooms_count",
    "floor_number",
    "floors_count",
    "building_year",
    "material_type",
    "geometry"
]

missing = [col for col in required_apartment_cols if col not in apartments.columns]

if missing:
    raise ValueError(f"В apartments_prepared не хватает колонок: {missing}")

apartments = apartments.reset_index(drop=True).copy()
apartments["apt_uid"] = np.arange(len(apartments))

base_cols = [
    "apt_uid",
    "id",
    "price",
    "price_m2",
    "ln_price_m2",
    "total_area",
    "rooms_count",
    "floor_number",
    "floors_count",
    "building_year",
    "material_type",
    "geometry"
]

optional_cols = [
    "url",
    "address",
    "latitude",
    "longitude",
    "ln_price",
    "ln_total_area",
    "area_per_room",
    "floor_ratio",
    "is_first_floor",
    "is_last_floor",
    "is_middle_floor",
    "building_age",
    "building_age_sq",
    "rooms_group",
    "floor_type"
]

existing_optional = [col for col in optional_cols if col in apartments.columns]

apartments_base = apartments[
    [col for col in base_cols if col != "geometry"] + existing_optional + ["geometry"]
].copy()

if os.path.exists(APARTMENTS_MODEL_BASE_GPKG):
    os.remove(APARTMENTS_MODEL_BASE_GPKG)

save_layer(
    apartments_base,
    APARTMENTS_MODEL_BASE_GPKG,
    APARTMENTS_MODEL_BASE_LAYER
)

apartments_base.drop(columns="geometry").to_csv(
    "apartments_model_base.csv",
    index=False
)

print("\nБазовый слой квартир сохранен.")
print("Квартир:", len(apartments_base))

hexes = read_gpkg_auto(
    HEX_GPKG,
    HEX_LAYER,
    label="гексагоны с зонами"
)

hexes = prepare_layer(hexes, target_crs=TARGET_CRS)
hexes = harmonize_zone_layer(hexes)
apartments_base = drop_old_zone_columns(apartments_base)

required_hex_cols = [
    "hex_id",
    "zone_name",
    "zone_rank",
    "geometry"
]

missing_hex = [col for col in required_hex_cols if col not in hexes.columns]

if missing_hex:
    raise ValueError(f"В слое гексагонов не хватает колонок: {missing_hex}")

hexes_small = hexes[
    [
        "hex_id",
        "zone_name",
        "zone_rank",
        "geometry"
    ]
].copy()

hexes_small["zone_name"] = (
    hexes_small["zone_name"]
    .astype(str)
    .str.strip()
    .str.lower()
)

print("\nРаспределение гексагонов по зонам:")
print(hexes_small["zone_name"].value_counts(dropna=False))

apartments_zoned = gpd.sjoin(
    apartments_base,
    hexes_small,
    how="left",
    predicate="within"
)

if "index_right" in apartments_zoned.columns:
    apartments_zoned = apartments_zoned.drop(columns=["index_right"])

apartments_zoned["zone_core"] = np.where(
    apartments_zoned["zone_name"] == "core",
    1,
    0
)

apartments_zoned["zone_semi_periphery"] = np.where(
    apartments_zoned["zone_name"] == "semi_periphery",
    1,
    0
)

zone_missing = apartments_zoned["zone_name"].isna()

apartments_zoned.loc[
    zone_missing,
    ["zone_rank", "zone_core", "zone_semi_periphery"]
] = np.nan

print("\nРаспределение квартир по зонам до фильтра:")
print(apartments_zoned["zone_name"].value_counts(dropna=False))
print("Квартир без зоны:", apartments_zoned["zone_name"].isna().sum())
print("Доля без зоны:", round(apartments_zoned["zone_name"].isna().mean() * 100, 2), "%")

n_before_zone_filter = len(apartments_zoned)

apartments_zoned = apartments_zoned[
    apartments_zoned["zone_name"].isin(["periphery", "semi_periphery", "core"])
].copy()

n_after_zone_filter = len(apartments_zoned)

print("\nФильтр по зонам:")
print("Было:", n_before_zone_filter)
print("Осталось:", n_after_zone_filter)
print("Удалено:", n_before_zone_filter - n_after_zone_filter)

if os.path.exists(APARTMENTS_WITH_ZONES_GPKG):
    os.remove(APARTMENTS_WITH_ZONES_GPKG)

save_layer(
    apartments_zoned,
    APARTMENTS_WITH_ZONES_GPKG,
    APARTMENTS_WITH_ZONES_LAYER
)

apartments_zoned.drop(columns="geometry").to_csv(
    "apartments_with_zones.csv",
    index=False
)

print("\nСлой квартир с зонами сохранен.")

external = {}

for key, params in LAYER_PATHS.items():
    g = read_gpkg_auto(
        params["gpkg"],
        params["layer"],
        label=key
    )

    g = prepare_layer(g, target_crs=TARGET_CRS)

    g = g.reset_index(drop=True).copy()
    g[f"{key}_uid"] = np.arange(len(g))

    external[key] = g

print("\nВсе внешние слои загружены и приведены к CRS:", TARGET_CRS)

if SAVE_PROCESSED_LAYERS:
    if os.path.exists(PROCESSED_LAYERS_GPKG):
        os.remove(PROCESSED_LAYERS_GPKG)

    for i, (key, g) in enumerate(external.items()):
        save_layer(
            g,
            PROCESSED_LAYERS_GPKG,
            key,
            remove_file=False
        )

    print("\nОбработанные внешние слои сохранены в:", PROCESSED_LAYERS_GPKG)

social = standardize_social_layer(external["social"])

schools = get_social_subset(social, "school")
kindergartens = get_social_subset(social, "kindergarten")
clinics = get_social_subset(social, "clinic")

features = apartments_zoned.copy()

features = add_nearest_distance(
    features,
    external["metro_mcc"],
    "dist_nearest_metro_mcc"
)

features = add_dummy_from_distance(
    features,
    "dist_nearest_metro_mcc",
    1000,
    "metro_mcc_1000m"
)

features = add_nearest_distance(
    features,
    external["mcd"],
    "dist_nearest_mcd"
)

features = add_dummy_from_distance(
    features,
    "dist_nearest_mcd",
    1500,
    "mcd_1500m"
)

features = add_nearest_distance(
    features,
    external["stops"],
    "dist_nearest_stop"
)

features = add_points_count_within_radius(
    features,
    external["stops"],
    500,
    "stops_500m"
)

features = add_nearest_distance(
    features,
    schools,
    "dist_nearest_school"
)

features = add_points_count_within_radius(
    features,
    schools,
    1000,
    "schools_1000m"
)

features = add_nearest_distance(
    features,
    kindergartens,
    "dist_nearest_kindergarten"
)

features = add_points_count_within_radius(
    features,
    kindergartens,
    1000,
    "kindergartens_1000m"
)

features = add_nearest_distance(
    features,
    clinics,
    "dist_nearest_clinic"
)

features = add_points_count_within_radius(
    features,
    clinics,
    1000,
    "clinics_1000m"
)

features = add_nearest_distance(
    features,
    external["parks"],
    "dist_nearest_green"
)

features = add_polygon_area_within_radius(
    features,
    external["parks"],
    1000,
    "green_area_1000m"
)

features = add_dummy_from_distance(
    features,
    "dist_nearest_green",
    500,
    "green_500m"
)

features = add_nearest_distance(
    features,
    external["rivers"],
    "dist_nearest_water"
)

features = add_dummy_from_distance(
    features,
    "dist_nearest_water",
    500,
    "water_500m"
)

features = add_polygon_area_within_radius(
    features,
    external["rivers"],
    1000,
    "water_area_1000m"
)

features = add_nearest_distance(
    features,
    external["highway"],
    "dist_nearest_major_road"
)

features = add_dummy_from_distance(
    features,
    "dist_nearest_major_road",
    300,
    "major_road_300m"
)

features = add_nearest_distance(
    features,
    external["railway"],
    "dist_nearest_railway"
)

features = add_dummy_from_distance(
    features,
    "dist_nearest_railway",
    300,
    "railway_300m"
)

features = add_nearest_distance(
    features,
    external["industrial"],
    "dist_nearest_industrial"
)

features = add_polygon_area_within_radius(
    features,
    external["industrial"],
    1000,
    "industrial_area_1000m"
)

features = add_dummy_from_distance(
    features,
    "dist_nearest_industrial",
    500,
    "industrial_500m"
)

features = add_nearest_distance(
    features,
    external["aerodromes"],
    "dist_nearest_aerodrome"
)

features = add_dummy_from_distance(
    features,
    "dist_nearest_aerodrome",
    3000,
    "aerodrome_3000m"
)

features = add_nearest_distance(
    features,
    external["waste"],
    "dist_nearest_waste"
)

features = add_dummy_from_distance(
    features,
    "dist_nearest_waste",
    1000,
    "waste_1000m"
)

features = add_nearest_distance(
    features,
    external["cemeteries"],
    "dist_nearest_cemetery"
)

features = add_dummy_from_distance(
    features,
    "dist_nearest_cemetery",
    500,
    "cemetery_500m"
)

features = add_polygon_area_within_radius(
    features,
    external["cemeteries"],
    1000,
    "cemetery_area_1000m"
)

transport_cols = [
    "dist_nearest_metro_mcc",
    "metro_mcc_1000m",
    "dist_nearest_mcd",
    "mcd_1500m",
    "dist_nearest_stop",
    "stops_500m"
]

positive_cols = [
    "dist_nearest_school",
    "schools_1000m",
    "dist_nearest_kindergarten",
    "kindergartens_1000m",
    "dist_nearest_clinic",
    "clinics_1000m",
    "dist_nearest_green",
    "green_area_1000m",
    "green_500m",
    "dist_nearest_water",
    "water_500m",
    "water_area_1000m"
]

negative_cols = [
    "dist_nearest_major_road",
    "major_road_300m",
    "dist_nearest_railway",
    "railway_300m",
    "dist_nearest_industrial",
    "industrial_area_1000m",
    "industrial_500m",
    "dist_nearest_aerodrome",
    "aerodrome_3000m",
    "dist_nearest_waste",
    "waste_1000m",
    "dist_nearest_cemetery",
    "cemetery_500m",
    "cemetery_area_1000m"
]

all_new_cols = transport_cols + positive_cols + negative_cols

print("\n" + "=" * 70)
print("Проверка новых признаков:")
print(features[all_new_cols].describe().T)

print("\nСредние значения новых признаков по зонам:")
print(
    features
    .groupby("zone_name")[all_new_cols]
    .mean()
    .round(2)
)

main_cols = [
    "apt_uid",
    "id",
    "price",
    "price_m2",
    "ln_price_m2",
    "total_area",
    "rooms_count",
    "floor_number",
    "floors_count",
    "floor_ratio",
    "is_first_floor",
    "is_last_floor",
    "building_year",
    "building_age",
    "building_age_sq",
    "material_type",
    "hex_id",
    "zone_name",
    "zone_rank",
    "zone_core",
    "zone_semi_periphery"
]

existing_main_cols = [
    col for col in main_cols
    if col in features.columns
]

extra_cols = [
    col for col in features.columns
    if col not in existing_main_cols + ["geometry"]
]

features = features[
    existing_main_cols + extra_cols + ["geometry"]
].copy()

if os.path.exists(OUTPUT_GPKG):
    os.remove(OUTPUT_GPKG)

save_layer(
    features,
    OUTPUT_GPKG,
    OUTPUT_LAYER
)

features.drop(columns="geometry").to_csv(
    OUTPUT_CSV,
    index=False
)

print("\n" + "=" * 70)
print("ГОТОВО.")
print(f"Финальный GPKG: {OUTPUT_GPKG}, слой: {OUTPUT_LAYER}")
print(f"Финальный CSV: {OUTPUT_CSV}")
print("Количество квартир:", len(features))
print("CRS:", features.crs)

======================================================================
Загружен слой: очищенные квартиры
Файл: apartments_prepared.gpkg
Слой: apartments_prepared
Количество объектов: 31614
CRS: EPSG:32637
Типы геометрии:
Point    31614
Name: count, dtype: int64

Базовый слой квартир сохранен.
Квартир: 31614

======================================================================
Загружен слой: гексагоны с зонами
Файл: moscow_hex_zones_two_variants_activity_4blocks_FINAL-2.gpkg
Слой: zones_two_variants_final
Количество объектов: 1467
CRS: EPSG:32637
Типы геометрии:
MultiPolygon    1467
Name: count, dtype: int64

Распределение гексагонов после приведения нового зонирования:
zone_name
periphery         1018
semi_periphery     325
core                99
non_urban           54
Name: count, dtype: int64

Распределение гексагонов по зонам:
zone_name
periphery         1018
semi_periphery     325
core                99
non_urban           54
Name: count, dtype: int64

Распределение квартир по зонам до фильтра:
zone_name
periphery         13256
semi_periphery    12502
core               5812
NaN                  35
non_urban             9
Name: count, dtype: int64
Квартир без зоны: 35
Доля без зоны: 0.11 %

Фильтр по зонам:
Было: 31614
Осталось: 31570
Удалено: 44

Слой квартир с зонами сохранен.

======================================================================
Загружен слой: mcd
Файл: moscow_mcd.gpkg
Слой: moscow_mcd
Количество объектов: 89
CRS: EPSG:32637
Типы геометрии:
Point    89
Name: count, dtype: int64

======================================================================
Загружен слой: metro_mcc
Файл: moscow_metro_mck.gpkg
Слой: moscow_metro_mck
Количество объектов: 305
CRS: EPSG:32637
Типы геометрии:
Point    305
Name: count, dtype: int64

======================================================================
Загружен слой: stops
Файл: public_transport_stops.gpkg
Слой: public_transport_stops
Количество объектов: 11515
CRS: EPSG:32637
Типы геометрии:
Point    11515
Name: count, dtype: int64

======================================================================
Загружен слой: social
Файл: moscow_social_infr.gpkg
Слой: moscow_social_infr
Количество объектов: 6695
CRS: EPSG:32637
Типы геометрии:
Point    6695
Name: count, dtype: int64

======================================================================
Загружен слой: parks
Файл: moscow_parks.gpkg
Слой: moscow_parks
Количество объектов: 1306
CRS: EPSG:32637
Типы геометрии:
MultiPolygon    1306
Name: count, dtype: int64

======================================================================
Загружен слой: rivers
Файл: moscow_rivers.gpkg
Слой: moscow_rivers
Количество объектов: 1461
CRS: EPSG:32637
Типы геометрии:
MultiPolygon    1461
Name: count, dtype: int64

======================================================================
Загружен слой: highway
Файл: moscow_highway.gpkg
Слой: moscow_highway
Количество объектов: 5070
CRS: EPSG:32637
Типы геометрии:
MultiLineString    5070
Name: count, dtype: int64

======================================================================
Загружен слой: railway
Файл: moscow_railway.gpkg
Слой: moscow_railway
Количество объектов: 6140
CRS: EPSG:32637
Типы геометрии:
MultiLineString    6140
Name: count, dtype: int64

======================================================================
Загружен слой: industrial
Файл: moscow_industrial_areas_filtered.gpkg
Слой: moscow_industrial_areas_filtered
Количество объектов: 1195
CRS: EPSG:32637
Типы геометрии:
MultiPolygon    1195
Name: count, dtype: int64

======================================================================
Загружен слой: aerodromes
Файл: moscow_aerodromes.gpkg
Слой: moscow_aerodromes
Количество объектов: 4
CRS: EPSG:32637
Типы геометрии:
MultiPolygon    4
Name: count, dtype: int64

======================================================================
Загружен слой: waste
Файл: moscow_waste_facilities.gpkg
Слой: moscow_waste_facilities
Количество объектов: 146
CRS: EPSG:32637
Типы геометрии:
Point    146
Name: count, dtype: int64

======================================================================
Загружен слой: cemeteries
Файл: moscow_cemeteries.gpkg
Слой: moscow_cemeteries
Количество объектов: 76
CRS: EPSG:32637
Типы геометрии:
MultiPolygon    76
Name: count, dtype: int64

Все внешние слои загружены и приведены к CRS: EPSG:32637

Обработанные внешние слои сохранены в: processed_external_layers.gpkg

Социальная инфраструктура после классификации:
subcategory_std
school          2772
kindergarten    2178
clinic          1745
Name: count, dtype: int64
dist_nearest_metro_mcc: добавлено.
metro_mcc_1000m: создано по dist_nearest_metro_mcc <= 1000 м.
dist_nearest_mcd: добавлено.
mcd_1500m: создано по dist_nearest_mcd <= 1500 м.
dist_nearest_stop: добавлено.
stops_500m: посчитано в радиусе 500 м.
dist_nearest_school: добавлено.
schools_1000m: посчитано в радиусе 1000 м.
dist_nearest_kindergarten: добавлено.
kindergartens_1000m: посчитано в радиусе 1000 м.
dist_nearest_clinic: добавлено.
clinics_1000m: посчитано в радиусе 1000 м.
dist_nearest_green: добавлено.
green_area_1000m: площадь посчитана в радиусе 1000 м.
green_500m: создано по dist_nearest_green <= 500 м.
dist_nearest_water: добавлено.
water_500m: создано по dist_nearest_water <= 500 м.
water_area_1000m: площадь посчитана в радиусе 1000 м.
dist_nearest_major_road: добавлено.
major_road_300m: создано по dist_nearest_major_road <= 300 м.
dist_nearest_railway: добавлено.
railway_300m: создано по dist_nearest_railway <= 300 м.
dist_nearest_industrial: добавлено.
industrial_area_1000m: площадь посчитана в радиусе 1000 м.
industrial_500m: создано по dist_nearest_industrial <= 500 м.
dist_nearest_aerodrome: добавлено.
aerodrome_3000m: создано по dist_nearest_aerodrome <= 3000 м.
dist_nearest_waste: добавлено.
waste_1000m: создано по dist_nearest_waste <= 1000 м.
dist_nearest_cemetery: добавлено.
cemetery_500m: создано по dist_nearest_cemetery <= 500 м.
cemetery_area_1000m: площадь посчитана в радиусе 1000 м.

======================================================================
Проверка новых признаков:
                             count           mean            std         min  \
dist_nearest_metro_mcc     31570.0     895.081214     794.717708   12.052105
metro_mcc_1000m            31570.0       0.706525       0.455361    0.000000
dist_nearest_mcd           31570.0    2410.758861    1856.581068   60.221631
mcd_1500m                  31570.0       0.431232       0.495256    0.000000
dist_nearest_stop          31570.0     157.211694     142.223456    7.067515
stops_500m                 31570.0      11.346658       4.936173    0.000000
dist_nearest_school        31570.0     417.445952     337.020955   10.565428
schools_1000m              31570.0      11.425119       9.119849    0.000000
dist_nearest_kindergarten  31570.0     399.714125     312.170009    0.802970
kindergartens_1000m        31570.0       8.833069       6.776411    0.000000
dist_nearest_clinic        31570.0     450.392476     409.309289    0.552017
clinics_1000m              31570.0       9.918657      12.301230    0.000000
dist_nearest_green         31570.0     393.219294     304.958773    0.000000
green_area_1000m           31570.0  500490.303209  667413.863365    0.000000
green_500m                 31570.0       0.696991       0.459566    0.000000
dist_nearest_water         31570.0     628.244586     426.170626   15.719260
water_500m                 31570.0       0.440893       0.496502    0.000000
water_area_1000m           31570.0   85699.057753  153973.539306    0.000000
dist_nearest_major_road    31570.0     614.263503     659.529159    8.295940
major_road_300m            31570.0       0.368008       0.482271    0.000000
dist_nearest_railway       31570.0    1160.088594    1122.588190   14.183166
railway_300m               31570.0       0.205860       0.404335    0.000000
dist_nearest_industrial    31570.0     537.043154     474.550681    0.000000
industrial_area_1000m      31570.0  242470.398583  278124.239488    0.000000
industrial_500m            31570.0       0.591416       0.491580    0.000000
dist_nearest_aerodrome     31570.0   19474.307408    5672.607285  498.122592
aerodrome_3000m            31570.0       0.005417       0.073399    0.000000
dist_nearest_waste         31570.0    1661.496604     881.977436    9.247316
waste_1000m                31570.0       0.264492       0.441069    0.000000
dist_nearest_cemetery      31570.0    2043.959284    1122.268918   26.926002
cemetery_500m              31570.0       0.051124       0.220255    0.000000
cemetery_area_1000m        31570.0   12053.561955   49399.182215    0.000000

                                    25%            50%            75%  \
dist_nearest_metro_mcc       480.564872     741.029279    1067.906320
metro_mcc_1000m                0.000000       1.000000       1.000000
dist_nearest_mcd             971.407434    1800.024131    3453.464187
mcd_1500m                      0.000000       0.000000       1.000000
dist_nearest_stop             88.272682     140.359691     203.538564
stops_500m                     8.000000      11.000000      14.000000
dist_nearest_school          194.729389     331.683138     555.349195
schools_1000m                  5.000000       9.000000      16.000000
dist_nearest_kindergarten    180.879768     317.675279     533.075445
kindergartens_1000m            4.000000       7.000000      12.000000
dist_nearest_clinic          191.754799     356.928156     585.337316
clinics_1000m                  2.000000       5.000000      12.000000
dist_nearest_green           165.749258     332.056829     558.748226
green_area_1000m           91363.549282  254373.025450  642020.092041
green_500m                     0.000000       1.000000       1.000000
dist_nearest_water           311.216379     552.712086     856.492113
water_500m                     0.000000       0.000000       1.000000
water_area_1000m            1130.305440   15362.778421   77477.089423
dist_nearest_major_road      200.600803     426.717363     813.716510
major_road_300m                0.000000       0.000000       1.000000
dist_nearest_railway         363.219147     837.202869    1532.019264
railway_300m                   0.000000       0.000000       0.000000
dist_nearest_industrial      185.646969     416.429287     748.592994
industrial_area_1000m      27541.016710  146100.946330  364806.047838
industrial_500m                0.000000       1.000000       1.000000
dist_nearest_aerodrome     15566.404585   19852.065495   23492.679484
aerodrome_3000m                0.000000       0.000000       0.000000
dist_nearest_waste           963.019990    1563.778250    2238.288706
waste_1000m                    0.000000       0.000000       1.000000
dist_nearest_cemetery       1203.131054    1862.831995    2719.698158
cemetery_500m                  0.000000       0.000000       0.000000
cemetery_area_1000m            0.000000       0.000000       0.000000

                                    max
dist_nearest_metro_mcc     1.591499e+04
metro_mcc_1000m            1.000000e+00
dist_nearest_mcd           1.875979e+04
mcd_1500m                  1.000000e+00
dist_nearest_stop          1.409316e+04
stops_500m                 4.000000e+01
dist_nearest_school        1.483782e+04
schools_1000m              6.100000e+01
dist_nearest_kindergarten  2.807499e+03
kindergartens_1000m        4.800000e+01
dist_nearest_clinic        1.505414e+04
clinics_1000m              8.100000e+01
dist_nearest_green         1.425639e+04
green_area_1000m           6.448308e+06
green_500m                 1.000000e+00
dist_nearest_water         1.428739e+04
water_500m                 1.000000e+00
water_area_1000m           1.481465e+06
dist_nearest_major_road    1.412047e+04
major_road_300m            1.000000e+00
dist_nearest_railway       1.446334e+04
railway_300m               1.000000e+00
dist_nearest_industrial    1.429749e+04
industrial_area_1000m      1.752745e+06
industrial_500m            1.000000e+00
dist_nearest_aerodrome     3.371907e+04
aerodrome_3000m            1.000000e+00
dist_nearest_waste         1.522511e+04
waste_1000m                1.000000e+00
dist_nearest_cemetery      1.415585e+04
cemetery_500m              1.000000e+00
cemetery_area_1000m        8.434735e+05

Средние значения новых признаков по зонам:
                dist_nearest_metro_mcc  metro_mcc_1000m  dist_nearest_mcd  \
zone_name
core                            539.22             0.94           1858.94
periphery                      1172.61             0.56           2735.23
semi_periphery                  766.25             0.75           2323.25

                mcd_1500m  dist_nearest_stop  stops_500m  dist_nearest_school  \
zone_name
core                 0.50             149.57       12.91               310.31
periphery            0.37             155.43       11.17               424.29
semi_periphery       0.47             162.66       10.81               460.00

                schools_1000m  dist_nearest_kindergarten  kindergartens_1000m  \
zone_name
core                    17.14                     308.70                12.32
periphery               10.48                     422.52                 8.12
semi_periphery           9.77                     417.85                 7.97

                ...  dist_nearest_industrial  industrial_area_1000m  \
zone_name       ...
core            ...                   665.78              139494.64
periphery       ...                   601.88              198607.68
semi_periphery  ...                   408.45              336850.44

                industrial_500m  dist_nearest_aerodrome  aerodrome_3000m  \
zone_name
core                       0.51                24299.55             0.00
periphery                  0.51                15916.19             0.01
semi_periphery             0.72                21003.83             0.00

                dist_nearest_waste  waste_1000m  dist_nearest_cemetery  \
zone_name
core                       1863.22         0.22                1491.68
periphery                  1574.72         0.28                2265.55
semi_periphery             1659.73         0.27                2065.75

                cemetery_500m  cemetery_area_1000m
zone_name
core                     0.06             23542.09
periphery                0.04              8625.92
semi_periphery           0.06             10347.08

[3 rows x 32 columns]

======================================================================
ГОТОВО.
Финальный GPKG: apartments_hedonic_features.gpkg, слой: apartments_hedonic_features
Финальный CSV: apartments_hedonic_features.csv
Количество квартир: 31570
CRS: EPSG:32637

In [ ]:
import os
import numpy as np
import pandas as pd
import geopandas as gpd

INPUT_GPKG = "apartments_hedonic_features.gpkg"
INPUT_LAYER = "apartments_hedonic_features"

OUTPUT_GPKG = "apartments_hedonic_indices.gpkg"
OUTPUT_LAYER = "apartments_hedonic_indices"
OUTPUT_CSV = "apartments_hedonic_indices.csv"

if not os.path.exists(INPUT_GPKG):
    raise FileNotFoundError(
        f"Не найден файл {INPUT_GPKG}."
    )

gdf = gpd.read_file(INPUT_GPKG, layer=INPUT_LAYER)

print("Квартир:", len(gdf))
print("CRS:", gdf.crs)
print("Колонки:")
print(gdf.columns.tolist())

def safe_log1p(series):
    s = pd.to_numeric(series, errors="coerce")
    s = s.where(s >= 0, np.nan)
    return np.log1p(s)

def zscore(series):
    s = pd.to_numeric(series, errors="coerce")
    mean = s.mean()
    std = s.std()

    if pd.isna(std) or std == 0:
        return pd.Series(0, index=s.index)

    return (s - mean) / std

def fill_median(series):
    s = pd.to_numeric(series, errors="coerce")
    return s.fillna(s.median())

def row_mean(df, cols):
    return df[cols].mean(axis=1)

if "ln_total_area" not in gdf.columns:
    gdf["ln_total_area"] = np.log(gdf["total_area"])

gdf["idx_ln_total_area"] = fill_median(gdf["ln_total_area"])

gdf["idx_rooms_count"] = fill_median(gdf["rooms_count"])

gdf["floor_comfort_score"] = np.nan

gdf.loc[gdf["is_first_floor"] == 1, "floor_comfort_score"] = 0
gdf.loc[gdf["is_last_floor"] == 1, "floor_comfort_score"] = 0.5
gdf.loc[gdf["is_middle_floor"] == 1, "floor_comfort_score"] = 1

gdf["idx_floor_comfort_score"] = fill_median(gdf["floor_comfort_score"])

if "building_age" not in gdf.columns:
    CURRENT_YEAR = 2026
    gdf["building_age"] = CURRENT_YEAR - pd.to_numeric(gdf["building_year"], errors="coerce")

gdf["idx_building_newness"] = -safe_log1p(gdf["building_age"])
gdf["idx_building_newness"] = fill_median(gdf["idx_building_newness"])

def material_to_score(x):
    if pd.isna(x):
        return np.nan

    s = str(x).lower().strip()

    if any(v in s for v in ["монолит", "monolith", "monolithic"]):
        return 1.0

    if any(v in s for v in ["кирп", "brick"]):
        return 0.8

    if any(v in s for v in ["блок", "block"]):
        return 0.6

    if any(v in s for v in ["панел", "panel"]):
        return 0.4

    if any(v in s for v in ["дерев", "wood"]):
        return 0.3

    return 0.5

gdf["material_score"] = gdf["material_type"].apply(material_to_score)
gdf["idx_material_score"] = fill_median(gdf["material_score"])

internal_raw_cols = [
    "idx_ln_total_area",
    "idx_rooms_count",
    "idx_floor_comfort_score",
    "idx_building_newness",
    "idx_material_score"
]

internal_z_cols = []

for col in internal_raw_cols:
    z_col = "z_" + col
    gdf[z_col] = zscore(gdf[col])
    internal_z_cols.append(z_col)

gdf["internal_index"] = row_mean(gdf, internal_z_cols)

gdf["idx_schools_1000m"] = safe_log1p(gdf["schools_1000m"])
gdf["idx_kindergartens_1000m"] = safe_log1p(gdf["kindergartens_1000m"])
gdf["idx_clinics_1000m"] = safe_log1p(gdf["clinics_1000m"])

gdf["idx_green_area_1000m"] = safe_log1p(gdf["green_area_1000m"])

gdf["idx_green_proximity"] = -safe_log1p(gdf["dist_nearest_green"])
gdf["idx_water_proximity"] = -safe_log1p(gdf["dist_nearest_water"])

external_positive_raw_cols = [
    "idx_schools_1000m",
    "idx_kindergartens_1000m",
    "idx_clinics_1000m",
    "idx_green_area_1000m",
    "idx_green_proximity",
    "idx_water_proximity"
]

external_positive_z_cols = []

for col in external_positive_raw_cols:
    gdf[col] = fill_median(gdf[col])
    z_col = "z_" + col
    gdf[z_col] = zscore(gdf[col])
    external_positive_z_cols.append(z_col)

gdf["external_positive_index"] = row_mean(gdf, external_positive_z_cols)

gdf["idx_major_road_300m"] = pd.to_numeric(gdf["major_road_300m"], errors="coerce").fillna(0)
gdf["idx_railway_300m"] = pd.to_numeric(gdf["railway_300m"], errors="coerce").fillna(0)
gdf["idx_industrial_area_1000m"] = safe_log1p(gdf["industrial_area_1000m"])
gdf["idx_waste_1000m"] = pd.to_numeric(gdf["waste_1000m"], errors="coerce").fillna(0)

external_negative_raw_cols = [
    "idx_major_road_300m",
    "idx_railway_300m",
    "idx_industrial_area_1000m",
    "idx_waste_1000m"
]

external_negative_z_cols = []

for col in external_negative_raw_cols:
    gdf[col] = fill_median(gdf[col])
    z_col = "z_" + col
    gdf[z_col] = zscore(gdf[col])
    external_negative_z_cols.append(z_col)

gdf["external_negative_index"] = row_mean(gdf, external_negative_z_cols)

gdf["idx_metro_mcc_proximity"] = -safe_log1p(gdf["dist_nearest_metro_mcc"])
gdf["idx_mcd_proximity"] = -safe_log1p(gdf["dist_nearest_mcd"])
gdf["idx_stop_proximity"] = -safe_log1p(gdf["dist_nearest_stop"])
gdf["idx_stops_500m"] = safe_log1p(gdf["stops_500m"])

transport_raw_cols = [
    "idx_metro_mcc_proximity",
    "idx_mcd_proximity",
    "idx_stop_proximity",
    "idx_stops_500m"
]

transport_z_cols = []

for col in transport_raw_cols:
    gdf[col] = fill_median(gdf[col])
    z_col = "z_" + col
    gdf[z_col] = zscore(gdf[col])
    transport_z_cols.append(z_col)

gdf["transport_accessibility_index"] = row_mean(gdf, transport_z_cols)

index_cols = [
    "internal_index",
    "external_positive_index",
    "external_negative_index",
    "transport_accessibility_index"
]

print("\nОписание индексов:")
print(gdf[index_cols].describe().T.round(3))

print("\nСредние значения индексов по зонам:")
print(
    gdf
    .groupby("zone_name")[index_cols]
    .mean()
    .round(3)
)

print("\nМедианные значения индексов по зонам:")
print(
    gdf
    .groupby("zone_name")[index_cols]
    .median()
    .round(3)
)

print("\nКорреляции между индексами:")
print(
    gdf[index_cols + ["ln_price_m2", "zone_rank"]]
    .corr()
    .round(3)
)

if os.path.exists(OUTPUT_GPKG):
    os.remove(OUTPUT_GPKG)

gdf.to_file(
    OUTPUT_GPKG,
    layer=OUTPUT_LAYER,
    driver="GPKG"
)

gdf.drop(columns="geometry").to_csv(
    OUTPUT_CSV,
    index=False
)

print("\nГотово.")
print(f"GPKG сохранен: {OUTPUT_GPKG}, слой: {OUTPUT_LAYER}")
print(f"CSV сохранен: {OUTPUT_CSV}")
print("Количество квартир:", len(gdf))

Квартир: 31570
CRS: EPSG:32637
Колонки:
['apt_uid', 'id', 'price', 'price_m2', 'ln_price_m2', 'total_area', 'rooms_count', 'floor_number', 'floors_count', 'floor_ratio', 'is_first_floor', 'is_last_floor', 'building_year', 'building_age', 'building_age_sq', 'material_type', 'hex_id', 'zone_name', 'zone_rank', 'zone_core', 'zone_semi_periphery', 'url', 'address', 'latitude', 'longitude', 'ln_price', 'ln_total_area', 'area_per_room', 'is_middle_floor', 'rooms_group', 'floor_type', 'dist_nearest_metro_mcc', 'metro_mcc_1000m', 'dist_nearest_mcd', 'mcd_1500m', 'dist_nearest_stop', 'stops_500m', 'dist_nearest_school', 'schools_1000m', 'dist_nearest_kindergarten', 'kindergartens_1000m', 'dist_nearest_clinic', 'clinics_1000m', 'dist_nearest_green', 'green_area_1000m', 'green_500m', 'dist_nearest_water', 'water_500m', 'water_area_1000m', 'dist_nearest_major_road', 'major_road_300m', 'dist_nearest_railway', 'railway_300m', 'dist_nearest_industrial', 'industrial_area_1000m', 'industrial_500m', 'dist_nearest_aerodrome', 'aerodrome_3000m', 'dist_nearest_waste', 'waste_1000m', 'dist_nearest_cemetery', 'cemetery_500m', 'cemetery_area_1000m', 'geometry']

Описание индексов:
                                 count  mean    std    min    25%    50%  \
internal_index                 31570.0  -0.0  0.604 -1.888 -0.422  0.010
external_positive_index        31570.0  -0.0  0.503 -3.154 -0.298  0.048
external_negative_index        31570.0   0.0  0.553 -1.034 -0.390  0.088
transport_accessibility_index  31570.0   0.0  0.600 -5.078 -0.391 -0.001

                                 75%    max
internal_index                 0.442  1.819
external_positive_index        0.334  1.730
external_negative_index        0.268  1.467
transport_accessibility_index  0.389  2.375

Средние значения индексов по зонам:
                internal_index  external_positive_index  \
zone_name
core                     0.171                    0.241
periphery               -0.156                   -0.021
semi_periphery           0.086                   -0.090

                external_negative_index  transport_accessibility_index
zone_name
core                             -0.040                          0.290
periphery                        -0.105                         -0.128
semi_periphery                    0.129                          0.001

Медианные значения индексов по зонам:
                internal_index  external_positive_index  \
zone_name
core                     0.205                    0.351
periphery               -0.174                    0.036
semi_periphery           0.121                   -0.034

                external_negative_index  transport_accessibility_index
zone_name
core                              0.077                          0.317
periphery                        -0.302                         -0.121
semi_periphery                    0.187                         -0.033

Корреляции между индексами:
                               internal_index  external_positive_index  \
internal_index                          1.000                   -0.001
external_positive_index                -0.001                    1.000
external_negative_index                 0.034                   -0.287
transport_accessibility_index          -0.015                    0.056
ln_price_m2                             0.456                    0.186
zone_rank                               0.216                    0.142

                               external_negative_index  \
internal_index                                   0.034
external_positive_index                         -0.287
external_negative_index                          1.000
transport_accessibility_index                    0.173
ln_price_m2                                     -0.035
zone_rank                                        0.089

                               transport_accessibility_index  ln_price_m2  \
internal_index                                        -0.015        0.456
external_positive_index                                0.056        0.186
external_negative_index                                0.173       -0.035
transport_accessibility_index                          1.000        0.065
ln_price_m2                                            0.065        1.000
zone_rank                                              0.241        0.515

                               zone_rank
internal_index                     0.216
external_positive_index            0.142
external_negative_index            0.089
transport_accessibility_index      0.241
ln_price_m2                        0.515
zone_rank                          1.000

Готово.
GPKG сохранен: apartments_hedonic_indices.gpkg, слой: apartments_hedonic_indices
CSV сохранен: apartments_hedonic_indices.csv
Количество квартир: 31570

In [ ]:
import os
import numpy as np
import pandas as pd
import geopandas as gpd
import statsmodels.api as sm

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

INPUT_GPKG = "apartments_hedonic_indices.gpkg"
INPUT_LAYER = "apartments_hedonic_indices"

DEPENDENT_VAR = "ln_price_m2"

FILTER_ROOMS_1_3 = True

TEST_SIZE = 0.2
RANDOM_STATE = 42

OUTPUT_RESULTS_CSV = f"model_6_spatial_nonlinear_controls_{DEPENDENT_VAR}_metrics.csv"
OUTPUT_COEF_CSV = f"model_6_spatial_nonlinear_controls_{DEPENDENT_VAR}_coefficients.csv"
OUTPUT_SUMMARY_TXT = f"model_6_spatial_nonlinear_controls_{DEPENDENT_VAR}_summary.txt"

if not os.path.exists(INPUT_GPKG):
    raise FileNotFoundError(
        f"Не найден файл {INPUT_GPKG}."
    )

gdf = gpd.read_file(INPUT_GPKG, layer=INPUT_LAYER)

print("Всего квартир:", len(gdf))
print("CRS:", gdf.crs)

gdf["price"] = pd.to_numeric(gdf["price"], errors="coerce")

if "ln_price" not in gdf.columns:
    gdf["ln_price"] = np.log(gdf["price"])

gdf["rooms_count_num"] = pd.to_numeric(gdf["rooms_count"], errors="coerce")

print("\nРаспределение rooms_count до фильтра:")
print(gdf["rooms_count_num"].value_counts(dropna=False).sort_index())

if FILTER_ROOMS_1_3:
    gdf = gdf[gdf["rooms_count_num"].isin([1, 2, 3])].copy()

print("\nКвартир после фильтра:", len(gdf))
print("\nРаспределение по зонам:")
print(gdf["zone_name"].value_counts(dropna=False))

def safe_log1p(s):
    s = pd.to_numeric(s, errors="coerce")
    s = s.where(s >= 0, np.nan)
    return np.log1p(s)

def zscore(s):
    s = pd.to_numeric(s, errors="coerce")
    mean = s.mean()
    std = s.std()

    if pd.isna(std) or std == 0:
        return pd.Series(0, index=s.index)

    return (s - mean) / std

def material_to_score(x):
    if pd.isna(x):
        return np.nan

    s = str(x).lower().strip()

    if any(v in s for v in ["монолит", "monolith", "monolithic"]):
        return 1.0
    if any(v in s for v in ["кирп", "brick"]):
        return 0.8
    if any(v in s for v in ["блок", "block"]):
        return 0.6
    if any(v in s for v in ["панел", "panel"]):
        return 0.4
    if any(v in s for v in ["дерев", "wood"]):
        return 0.3

    return 0.5

df = gdf.copy()

df["total_area"] = pd.to_numeric(df["total_area"], errors="coerce")

if "ln_total_area" not in df.columns:
    df["ln_total_area"] = np.log(df["total_area"])

if "floor_comfort_score" not in df.columns:
    df["floor_comfort_score"] = np.nan
    df.loc[df["is_first_floor"] == 1, "floor_comfort_score"] = 0
    df.loc[df["is_last_floor"] == 1, "floor_comfort_score"] = 0.5
    df.loc[df["is_middle_floor"] == 1, "floor_comfort_score"] = 1

if "material_score" not in df.columns:
    df["material_score"] = df["material_type"].apply(material_to_score)

df["building_newness"] = -safe_log1p(df["building_age"])

df["metro_mcc_proximity"] = -safe_log1p(df["dist_nearest_metro_mcc"])
df["mcd_proximity"] = -safe_log1p(df["dist_nearest_mcd"])
df["stop_proximity"] = -safe_log1p(df["dist_nearest_stop"])
df["log_stops_500m"] = safe_log1p(df["stops_500m"])

df["log_schools_1000m"] = safe_log1p(df["schools_1000m"])
df["log_kindergartens_1000m"] = safe_log1p(df["kindergartens_1000m"])
df["log_clinics_1000m"] = safe_log1p(df["clinics_1000m"])
df["log_green_area_1000m"] = safe_log1p(df["green_area_1000m"])

df["green_proximity"] = -safe_log1p(df["dist_nearest_green"])
df["water_proximity"] = -safe_log1p(df["dist_nearest_water"])

df["log_industrial_area_1000m"] = safe_log1p(df["industrial_area_1000m"])

df["x"] = df.geometry.x
df["y"] = df.geometry.y

core_points = df[df["zone_name"] == "core"].copy()

core_x = core_points.geometry.x.mean()
core_y = core_points.geometry.y.mean()

df["dist_to_core_center"] = np.sqrt(
    (df["x"] - core_x) ** 2 +
    (df["y"] - core_y) ** 2
)

df["log_dist_to_core_center"] = np.log1p(df["dist_to_core_center"])

df["x_centered"] = df["x"] - df["x"].mean()
df["y_centered"] = df["y"] - df["y"].mean()

df["x2"] = df["x_centered"] ** 2
df["y2"] = df["y_centered"] ** 2
df["xy"] = df["x_centered"] * df["y_centered"]

component_raw_cols = [

    "ln_total_area",
    "rooms_count",
    "floor_comfort_score",
    "building_newness",
    "material_score",

    "metro_mcc_proximity",
    "mcd_proximity",
    "stop_proximity",
    "log_stops_500m",

    "log_schools_1000m",
    "log_kindergartens_1000m",
    "log_clinics_1000m",
    "log_green_area_1000m",
    "green_proximity",
    "water_proximity",

    "major_road_300m",
    "railway_300m",
    "log_industrial_area_1000m",
    "waste_1000m"
]

for col in component_raw_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")
    df[col] = df[col].fillna(df[col].median())
    df["z_" + col] = zscore(df[col])

spatial_raw_cols = [
    "x_centered",
    "y_centered",
    "x2",
    "y2",
    "xy",
    "log_dist_to_core_center"
]

for col in spatial_raw_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")
    df[col] = df[col].fillna(df[col].median())
    df["z_" + col] = zscore(df[col])

zone_vars = [
    "zone_core",
    "zone_semi_periphery"
]

component_vars = [

    "z_ln_total_area",
    "z_rooms_count",
    "z_floor_comfort_score",
    "z_building_newness",
    "z_material_score",

    "z_metro_mcc_proximity",
    "z_mcd_proximity",
    "z_stop_proximity",
    "z_log_stops_500m",

    "z_log_schools_1000m",
    "z_log_kindergartens_1000m",
    "z_log_clinics_1000m",
    "z_log_green_area_1000m",
    "z_green_proximity",
    "z_water_proximity",

    "z_major_road_300m",
    "z_railway_300m",
    "z_log_industrial_area_1000m",
    "z_waste_1000m"
]

interaction_vars = []

for component in component_vars:
    for zone in zone_vars:
        new_col = f"{component}_x_{zone}"
        df[new_col] = df[component] * df[zone]
        interaction_vars.append(new_col)

spatial_vars = [
    "z_x_centered",
    "z_y_centered",
    "z_x2",
    "z_y2",
    "z_xy",
    "z_log_dist_to_core_center"
]

MODEL_VARS = zone_vars + component_vars + interaction_vars + spatial_vars

print("\nКоличество признаков model_6:", len(MODEL_VARS))

model_df = df[[DEPENDENT_VAR, "zone_name"] + MODEL_VARS].copy()

for col in [DEPENDENT_VAR] + MODEL_VARS:
    model_df[col] = pd.to_numeric(model_df[col], errors="coerce")

for col in MODEL_VARS:
    model_df[col] = model_df[col].fillna(model_df[col].median())

n_before = len(model_df)
model_df = model_df.dropna(subset=[DEPENDENT_VAR, "zone_name"]).copy()
n_after = len(model_df)

print("\nНаблюдений до удаления NaN:", n_before)
print("Наблюдений в модели:", n_after)
print("Удалено:", n_before - n_after)

train_df, test_df = train_test_split(
    model_df,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    stratify=model_df["zone_name"]
)

print("\nTrain:", len(train_df))
print("Test:", len(test_df))

y_train = train_df[DEPENDENT_VAR]
X_train = sm.add_constant(train_df[MODEL_VARS], has_constant="add")

y_test = test_df[DEPENDENT_VAR]
X_test = sm.add_constant(test_df[MODEL_VARS], has_constant="add")

model = sm.OLS(y_train, X_train).fit(cov_type="HC3")

print(model.summary())

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

metrics = {
    "model": "model_6_spatial_nonlinear_controls",
    "dependent_var": DEPENDENT_VAR,
    "rooms_filter": "1_3_only" if FILTER_ROOMS_1_3 else "all",
    "n_total": len(model_df),
    "n_train": len(train_df),
    "n_test": len(test_df),
    "n_features": len(MODEL_VARS),
    "r2_train": model.rsquared,
    "adj_r2_train": model.rsquared_adj,
    "r2_test": r2_score(y_test, y_test_pred),
    "rmse_train_log": np.sqrt(mean_squared_error(y_train, y_train_pred)),
    "rmse_test_log": np.sqrt(mean_squared_error(y_test, y_test_pred)),
    "mae_train_log": mean_absolute_error(y_train, y_train_pred),
    "mae_test_log": mean_absolute_error(y_test, y_test_pred),
    "aic_train": model.aic,
    "bic_train": model.bic
}

metrics_df = pd.DataFrame([metrics])

metrics_df_rounded = metrics_df.copy()

for col in [
    "r2_train",
    "adj_r2_train",
    "r2_test",
    "rmse_train_log",
    "rmse_test_log",
    "mae_train_log",
    "mae_test_log",
    "aic_train",
    "bic_train"
]:
    metrics_df_rounded[col] = metrics_df_rounded[col].round(4)

print("\nМетрики model_6:")
display(metrics_df_rounded)

metrics_df_rounded.to_csv(OUTPUT_RESULTS_CSV, index=False)

coef_table = pd.DataFrame({
    "variable": model.params.index,
    "coef_log": model.params.values,
    "std_err": model.bse.values,
    "t_value": model.tvalues.values,
    "p_value": model.pvalues.values,
    "ci_low": model.conf_int()[0].values,
    "ci_high": model.conf_int()[1].values
})

coef_table["effect_percent"] = (np.exp(coef_table["coef_log"]) - 1) * 100
coef_table["ci_low_percent"] = (np.exp(coef_table["ci_low"]) - 1) * 100
coef_table["ci_high_percent"] = (np.exp(coef_table["ci_high"]) - 1) * 100

coef_table_rounded = coef_table.round({
    "coef_log": 4,
    "std_err": 4,
    "t_value": 3,
    "p_value": 4,
    "ci_low": 4,
    "ci_high": 4,
    "effect_percent": 2,
    "ci_low_percent": 2,
    "ci_high_percent": 2
})

print("\nКоэффициенты model_6:")
display(coef_table_rounded)

coef_table_rounded.to_csv(OUTPUT_COEF_CSV, index=False)

with open(OUTPUT_SUMMARY_TXT, "w", encoding="utf-8") as f:
    f.write(str(model.summary()))
    f.write("\n\nМетрики:\n")
    for key, value in metrics.items():
        f.write(f"{key}: {value}\n")

print("\nГотово.")
print("Метрики сохранены:", OUTPUT_RESULTS_CSV)
print("Коэффициенты сохранены:", OUTPUT_COEF_CSV)
print("Summary сохранен:", OUTPUT_SUMMARY_TXT)

Всего квартир: 31570
CRS: EPSG:32637

Распределение rooms_count до фильтра:
rooms_count_num
1.0    5858
2.0    9885
3.0    8904
4.0    3315
5.0     991
6.0     295
NaN    2322
Name: count, dtype: int64

Квартир после фильтра: 24647

Распределение по зонам:
zone_name
periphery         11205
semi_periphery     9747
core               3695
Name: count, dtype: int64

Количество признаков model_6: 65

Наблюдений до удаления NaN: 24647
Наблюдений в модели: 24647
Удалено: 0

Train: 19717
Test: 4930
                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_price_m2   R-squared:                       0.621
Model:                            OLS   Adj. R-squared:                  0.620
Method:                 Least Squares   F-statistic:                     478.6
Date:                Sun, 07 Jun 2026   Prob (F-statistic):               0.00
Time:                        14:02:41   Log-Likelihood:                -1991.0
No. Observations:               19717   AIC:                             4114.
Df Residuals:                   19651   BIC:                             4635.
Df Model:                          65
Covariance Type:                  HC3
=====================================================================================================================
                                                        coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------------
const                                                12.9390      0.006   2025.354      0.000      12.926      12.951
zone_core                                             0.0434      0.020      2.120      0.034       0.003       0.083
zone_semi_periphery                                  -0.0022      0.008     -0.283      0.777      -0.017       0.013
z_ln_total_area                                       0.0025      0.006      0.394      0.693      -0.010       0.015
z_rooms_count                                        -0.0600      0.005    -11.527      0.000      -0.070      -0.050
z_floor_comfort_score                                 0.0276      0.003      9.813      0.000       0.022       0.033
z_building_newness                                    0.0886      0.003     25.533      0.000       0.082       0.095
z_material_score                                      0.0415      0.003     15.307      0.000       0.036       0.047
z_metro_mcc_proximity                                 0.0462      0.003     17.802      0.000       0.041       0.051
z_mcd_proximity                                      -0.0152      0.003     -5.287      0.000      -0.021      -0.010
z_stop_proximity                                     -0.0029      0.003     -1.033      0.302      -0.008       0.003
z_log_stops_500m                                     -0.0203      0.003     -6.514      0.000      -0.026      -0.014
z_log_schools_1000m                                  -0.0268      0.004     -7.639      0.000      -0.034      -0.020
z_log_kindergartens_1000m                             0.0205      0.003      6.238      0.000       0.014       0.027
z_log_clinics_1000m                                  -0.0004      0.004     -0.108      0.914      -0.008       0.007
z_log_green_area_1000m                                0.0096      0.004      2.651      0.008       0.003       0.017
z_green_proximity                                     0.0014      0.003      0.502      0.616      -0.004       0.007
z_water_proximity                                     0.0133      0.003      4.529      0.000       0.008       0.019
z_major_road_300m                                    -0.0073      0.003     -2.633      0.008      -0.013      -0.002
z_railway_300m                                       -0.0175      0.003     -5.080      0.000      -0.024      -0.011
z_log_industrial_area_1000m                          -0.0116      0.003     -4.488      0.000      -0.017      -0.007
z_waste_1000m                                        -0.0083      0.002     -3.321      0.001      -0.013      -0.003
z_ln_total_area_x_zone_core                           0.0949      0.013      7.474      0.000       0.070       0.120
z_ln_total_area_x_zone_semi_periphery                 0.0593      0.009      6.387      0.000       0.041       0.077
z_rooms_count_x_zone_core                            -0.0324      0.014     -2.377      0.017      -0.059      -0.006
z_rooms_count_x_zone_semi_periphery                  -0.0157      0.008     -1.910      0.056      -0.032       0.000
z_floor_comfort_score_x_zone_core                     0.0227      0.008      2.967      0.003       0.008       0.038
z_floor_comfort_score_x_zone_semi_periphery           0.0272      0.005      5.781      0.000       0.018       0.036
z_building_newness_x_zone_core                        0.0252      0.009      2.925      0.003       0.008       0.042
z_building_newness_x_zone_semi_periphery             -0.0041      0.005     -0.756      0.450      -0.015       0.007
z_material_score_x_zone_core                          0.0327      0.010      3.294      0.001       0.013       0.052
z_material_score_x_zone_semi_periphery                0.0272      0.005      5.397      0.000       0.017       0.037
z_metro_mcc_proximity_x_zone_core                    -0.0337      0.010     -3.239      0.001      -0.054      -0.013
z_metro_mcc_proximity_x_zone_semi_periphery          -0.0211      0.005     -4.330      0.000      -0.031      -0.012
z_mcd_proximity_x_zone_core                          -0.0819      0.010     -7.845      0.000      -0.102      -0.061
z_mcd_proximity_x_zone_semi_periphery                 0.0200      0.005      4.087      0.000       0.010       0.030
z_stop_proximity_x_zone_core                         -0.0126      0.008     -1.607      0.108      -0.028       0.003
z_stop_proximity_x_zone_semi_periphery               -0.0265      0.005     -5.781      0.000      -0.036      -0.018
z_log_stops_500m_x_zone_core                         -0.0143      0.009     -1.556      0.120      -0.032       0.004
z_log_stops_500m_x_zone_semi_periphery               -0.0247      0.005     -4.967      0.000      -0.034      -0.015
z_log_schools_1000m_x_zone_core                       0.0830      0.013      6.447      0.000       0.058       0.108
z_log_schools_1000m_x_zone_semi_periphery             0.0421      0.006      7.241      0.000       0.031       0.054
z_log_kindergartens_1000m_x_zone_core                 0.0309      0.012      2.621      0.009       0.008       0.054
z_log_kindergartens_1000m_x_zone_semi_periphery      -0.0613      0.006    -10.416      0.000      -0.073      -0.050
z_log_clinics_1000m_x_zone_core                      -0.0011      0.015     -0.076      0.939      -0.030       0.027
z_log_clinics_1000m_x_zone_semi_periphery             0.0359      0.007      5.380      0.000       0.023       0.049
z_log_green_area_1000m_x_zone_core                    0.0092      0.006      1.425      0.154      -0.003       0.022
z_log_green_area_1000m_x_zone_semi_periphery          0.0016      0.005      0.327      0.744      -0.008       0.011
z_green_proximity_x_zone_core                        -0.0025      0.008     -0.300      0.764      -0.019       0.014
z_green_proximity_x_zone_semi_periphery               0.0229      0.005      4.539      0.000       0.013       0.033
z_water_proximity_x_zone_core                         0.0472      0.007      6.346      0.000       0.033       0.062
z_water_proximity_x_zone_semi_periphery              -0.0001      0.004     -0.024      0.981      -0.009       0.009
z_major_road_300m_x_zone_core                         0.0156      0.007      2.097      0.036       0.001       0.030
z_major_road_300m_x_zone_semi_periphery               0.0183      0.004      4.119      0.000       0.010       0.027
z_railway_300m_x_zone_core                            0.0103      0.008      1.254      0.210      -0.006       0.026
z_railway_300m_x_zone_semi_periphery                 -0.0034      0.005     -0.698      0.485      -0.013       0.006
z_log_industrial_area_1000m_x_zone_core              -0.0301      0.008     -3.638      0.000      -0.046      -0.014
z_log_industrial_area_1000m_x_zone_semi_periphery    -0.0290      0.005     -5.678      0.000      -0.039      -0.019
z_waste_1000m_x_zone_core                             0.0387      0.008      5.052      0.000       0.024       0.054
z_waste_1000m_x_zone_semi_periphery                  -0.0229      0.004     -5.419      0.000      -0.031      -0.015
z_x_centered                                         -0.0610      0.002    -28.446      0.000      -0.065      -0.057
z_y_centered                                         -0.0211      0.002    -10.410      0.000      -0.025      -0.017
z_x2                                                 -0.0441      0.003    -12.925      0.000      -0.051      -0.037
z_y2                                                 -0.0682      0.004    -16.783      0.000      -0.076      -0.060
z_xy                                                 -0.0035      0.002     -1.942      0.052      -0.007     3.2e-05
z_log_dist_to_core_center                            -0.1673      0.011    -15.553      0.000      -0.188      -0.146
==============================================================================
Omnibus:                     5785.223   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            47620.756
Skew:                          -1.179   Prob(JB):                         0.00
Kurtosis:                      10.239   Cond. No.                         19.9
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

Метрики model_6:

,model,dependent_var,rooms_filter,n_total,n_train,n_test,n_features,r2_train,adj_r2_train,r2_test,rmse_train_log,rmse_test_log,mae_train_log,mae_test_log,aic_train,bic_train
0,model_6_spatial_nonlinear_controls,ln_price_m2,1_3_only,24647,19717,4930,65,0.6215,0.6202,0.607,0.2677,0.2812,0.1846,0.1916,4114.0994,4634.789

Коэффициенты model_6:

,variable,coef_log,std_err,t_value,p_value,ci_low,ci_high,effect_percent,ci_low_percent,ci_high_percent
0,const,12.9390,0.0064,2025.354,0.0000,12.9264,12.9515,41621686.30,41103779.93,42146118.25
1,zone_core,0.0434,0.0205,2.120,0.0340,0.0033,0.0835,4.43,0.33,8.71
2,zone_semi_periphery,-0.0022,0.0076,-0.283,0.7772,-0.0171,0.0128,-0.21,-1.69,1.28
3,z_ln_total_area,0.0025,0.0064,0.394,0.6933,-0.0101,0.0151,0.25,-1.00,1.52
4,z_rooms_count,-0.0600,0.0052,-11.527,0.0000,-0.0702,-0.0498,-5.82,-6.78,-4.86
...,...,...,...,...,...,...,...,...,...,...
61,z_y_centered,-0.0211,0.0020,-10.410,0.0000,-0.0251,-0.0172,-2.09,-2.48,-1.70
62,z_x2,-0.0441,0.0034,-12.925,0.0000,-0.0508,-0.0374,-4.31,-4.95,-3.67
63,z_y2,-0.0682,0.0041,-16.783,0.0000,-0.0762,-0.0603,-6.60,-7.34,-5.85
64,z_xy,-0.0035,0.0018,-1.942,0.0521,-0.0070,0.0000,-0.35,-0.70,0.00
65,z_log_dist_to_core_center,-0.1673,0.0108,-15.553,0.0000,-0.1884,-0.1462,-15.41,-17.17,-13.61

Готово.
Метрики сохранены: model_6_spatial_nonlinear_controls_ln_price_m2_metrics.csv
Коэффициенты сохранены: model_6_spatial_nonlinear_controls_ln_price_m2_coefficients.csv
Summary сохранен: model_6_spatial_nonlinear_controls_ln_price_m2_summary.txt

In [ ]:
df["zone_core"] = (df["zone_name"] == "core").astype(int)
df["zone_semi_periphery"] = (df["zone_name"] == "semi_periphery").astype(int)

for component in component_vars:
    for zone in zone_vars:
        new_col = f"{component}_x_{zone}"
        df[new_col] = df[component] * df[zone]

model_df_full = df[[DEPENDENT_VAR, "zone_name"] + MODEL_VARS].copy()

for col in [DEPENDENT_VAR] + MODEL_VARS:
    model_df_full[col] = pd.to_numeric(model_df_full[col], errors="coerce")

for col in MODEL_VARS:
    model_df_full[col] = model_df_full[col].fillna(model_df_full[col].median())

model_df_full = model_df_full.dropna(subset=[DEPENDENT_VAR, "zone_name"]).copy()

y_full = model_df_full[DEPENDENT_VAR]
X_full = sm.add_constant(model_df_full[MODEL_VARS], has_constant="add")

model_full = sm.OLS(y_full, X_full).fit(cov_type="HC3")

print(model_full.summary())

coef_full = pd.DataFrame({
    "variable": model_full.params.index,
    "coef_log": model_full.params.values,
    "std_err": model_full.bse.values,
    "t_value": model_full.tvalues.values,
    "p_value": model_full.pvalues.values,
    "ci_low": model_full.conf_int()[0].values,
    "ci_high": model_full.conf_int()[1].values
})

coef_full["effect_percent"] = (np.exp(coef_full["coef_log"]) - 1) * 100
coef_full["ci_low_percent"] = (np.exp(coef_full["ci_low"]) - 1) * 100
coef_full["ci_high_percent"] = (np.exp(coef_full["ci_high"]) - 1) * 100

coef_full.to_csv(
    "model_6_full_sample_coefficients.csv",
    index=False,
    encoding="utf-8-sig"
)

model_df_full["y_pred_full"] = model_full.predict(X_full)
model_df_full["residual_full"] = y_full - model_df_full["y_pred_full"]

model_df_full[[
    DEPENDENT_VAR,
    "y_pred_full",
    "residual_full",
    "zone_name"
]].to_csv(
    "model_6_full_sample_predictions_residuals.csv",
    index=False,
    encoding="utf-8-sig"
)

model = model_full
X = X_full.copy()
df_model = model_df_full.copy()

print("Финальная модель на всей выборке обучена.")
print("N:", len(model_df_full))
print("Коэффициенты сохранены: model_6_full_sample_coefficients.csv")
print("Предсказания и остатки сохранены: model_6_full_sample_predictions_residuals.csv")

                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_price_m2   R-squared:                       0.619
Model:                            OLS   Adj. R-squared:                  0.618
Method:                 Least Squares   F-statistic:                     597.3
Date:                Sun, 07 Jun 2026   Prob (F-statistic):               0.00
Time:                        14:02:43   Log-Likelihood:                -2732.3
No. Observations:               24647   AIC:                             5597.
Df Residuals:                   24581   BIC:                             6132.
Df Model:                          65
Covariance Type:                  HC3
=====================================================================================================================
                                                        coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------------
const                                                12.9403      0.006   2288.052      0.000      12.929      12.951
zone_core                                             0.0205      0.018      1.112      0.266      -0.016       0.057
zone_semi_periphery                                  -0.0028      0.007     -0.420      0.675      -0.016       0.010
z_ln_total_area                                       0.0010      0.006      0.172      0.863      -0.010       0.012
z_rooms_count                                        -0.0582      0.005    -12.369      0.000      -0.067      -0.049
z_floor_comfort_score                                 0.0279      0.003     11.023      0.000       0.023       0.033
z_building_newness                                    0.0932      0.003     29.377      0.000       0.087       0.099
z_material_score                                      0.0410      0.002     16.780      0.000       0.036       0.046
z_metro_mcc_proximity                                 0.0452      0.002     19.487      0.000       0.041       0.050
z_mcd_proximity                                      -0.0162      0.003     -6.261      0.000      -0.021      -0.011
z_stop_proximity                                     -0.0024      0.002     -0.962      0.336      -0.007       0.002
z_log_stops_500m                                     -0.0203      0.003     -7.309      0.000      -0.026      -0.015
z_log_schools_1000m                                  -0.0262      0.003     -8.249      0.000      -0.032      -0.020
z_log_kindergartens_1000m                             0.0198      0.003      6.503      0.000       0.014       0.026
z_log_clinics_1000m                                   0.0028      0.003      0.856      0.392      -0.004       0.009
z_log_green_area_1000m                                0.0084      0.003      2.580      0.010       0.002       0.015
z_green_proximity                                     0.0020      0.003      0.772      0.440      -0.003       0.007
z_water_proximity                                     0.0123      0.003      4.705      0.000       0.007       0.017
z_major_road_300m                                    -0.0095      0.002     -3.804      0.000      -0.014      -0.005
z_railway_300m                                       -0.0176      0.003     -5.707      0.000      -0.024      -0.012
z_log_industrial_area_1000m                          -0.0132      0.002     -5.831      0.000      -0.018      -0.009
z_waste_1000m                                        -0.0100      0.002     -4.467      0.000      -0.014      -0.006
z_ln_total_area_x_zone_core                           0.0980      0.011      8.638      0.000       0.076       0.120
z_ln_total_area_x_zone_semi_periphery                 0.0606      0.008      7.295      0.000       0.044       0.077
z_rooms_count_x_zone_core                            -0.0385      0.012     -3.192      0.001      -0.062      -0.015
z_rooms_count_x_zone_semi_periphery                  -0.0178      0.007     -2.432      0.015      -0.032      -0.003
z_floor_comfort_score_x_zone_core                     0.0206      0.007      2.827      0.005       0.006       0.035
z_floor_comfort_score_x_zone_semi_periphery           0.0265      0.004      6.212      0.000       0.018       0.035
z_building_newness_x_zone_core                        0.0185      0.008      2.364      0.018       0.003       0.034
z_building_newness_x_zone_semi_periphery             -0.0078      0.005     -1.610      0.107      -0.017       0.002
z_material_score_x_zone_core                          0.0410      0.009      4.352      0.000       0.023       0.059
z_material_score_x_zone_semi_periphery                0.0273      0.004      6.071      0.000       0.018       0.036
z_metro_mcc_proximity_x_zone_core                    -0.0372      0.009     -4.044      0.000      -0.055      -0.019
z_metro_mcc_proximity_x_zone_semi_periphery          -0.0202      0.004     -4.557      0.000      -0.029      -0.012
z_mcd_proximity_x_zone_core                          -0.0778      0.010     -8.170      0.000      -0.096      -0.059
z_mcd_proximity_x_zone_semi_periphery                 0.0229      0.004      5.232      0.000       0.014       0.031
z_stop_proximity_x_zone_core                         -0.0126      0.007     -1.750      0.080      -0.027       0.002
z_stop_proximity_x_zone_semi_periphery               -0.0253      0.004     -6.175      0.000      -0.033      -0.017
z_log_stops_500m_x_zone_core                         -0.0082      0.008     -1.008      0.313      -0.024       0.008
z_log_stops_500m_x_zone_semi_periphery               -0.0240      0.004     -5.339      0.000      -0.033      -0.015
z_log_schools_1000m_x_zone_core                       0.0770      0.012      6.699      0.000       0.054       0.100
z_log_schools_1000m_x_zone_semi_periphery             0.0406      0.005      7.820      0.000       0.030       0.051
z_log_kindergartens_1000m_x_zone_core                 0.0278      0.011      2.561      0.010       0.007       0.049
z_log_kindergartens_1000m_x_zone_semi_periphery      -0.0606      0.005    -11.269      0.000      -0.071      -0.050
z_log_clinics_1000m_x_zone_core                       0.0080      0.013      0.619      0.536      -0.017       0.033
z_log_clinics_1000m_x_zone_semi_periphery             0.0310      0.006      5.186      0.000       0.019       0.043
z_log_green_area_1000m_x_zone_core                    0.0089      0.006      1.546      0.122      -0.002       0.020
z_log_green_area_1000m_x_zone_semi_periphery          0.0004      0.004      0.088      0.930      -0.008       0.009
z_green_proximity_x_zone_core                        -0.0050      0.007     -0.670      0.503      -0.020       0.010
z_green_proximity_x_zone_semi_periphery               0.0241      0.005      5.307      0.000       0.015       0.033
z_water_proximity_x_zone_core                         0.0482      0.007      7.246      0.000       0.035       0.061
z_water_proximity_x_zone_semi_periphery               0.0037      0.004      0.921      0.357      -0.004       0.012
z_major_road_300m_x_zone_core                         0.0163      0.007      2.401      0.016       0.003       0.030
z_major_road_300m_x_zone_semi_periphery               0.0219      0.004      5.482      0.000       0.014       0.030
z_railway_300m_x_zone_core                            0.0136      0.007      1.824      0.068      -0.001       0.028
z_railway_300m_x_zone_semi_periphery                 -0.0037      0.004     -0.837      0.403      -0.012       0.005
z_log_industrial_area_1000m_x_zone_core              -0.0268      0.008     -3.578      0.000      -0.042      -0.012
z_log_industrial_area_1000m_x_zone_semi_periphery    -0.0278      0.005     -6.112      0.000      -0.037      -0.019
z_waste_1000m_x_zone_core                             0.0410      0.007      5.877      0.000       0.027       0.055
z_waste_1000m_x_zone_semi_periphery                  -0.0205      0.004     -5.382      0.000      -0.028      -0.013
z_x_centered                                         -0.0611      0.002    -31.943      0.000      -0.065      -0.057
z_y_centered                                         -0.0212      0.002    -11.683      0.000      -0.025      -0.018
z_x2                                                 -0.0445      0.003    -14.809      0.000      -0.050      -0.039
z_y2                                                 -0.0677      0.004    -19.014      0.000      -0.075      -0.061
z_xy                                                 -0.0017      0.002     -1.090      0.276      -0.005       0.001
z_log_dist_to_core_center                            -0.1680      0.009    -17.872      0.000      -0.186      -0.150
==============================================================================
Omnibus:                     7424.070   Durbin-Watson:                   1.230
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            61933.208
Skew:                          -1.213   Prob(JB):                         0.00
Kurtosis:                      10.377   Cond. No.                         19.8
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
Финальная модель на всей выборке обучена.
N: 24647
Коэффициенты сохранены: model_6_full_sample_coefficients.csv
Предсказания и остатки сохранены: model_6_full_sample_predictions_residuals.csv

In [ ]:
import os
import numpy as np
import pandas as pd
import geopandas as gpd
import statsmodels.api as sm

from sklearn.model_selection import train_test_split, GroupKFold
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

INPUT_GPKG = "apartments_hedonic_indices.gpkg"
INPUT_LAYER = "apartments_hedonic_indices"

DEPENDENT_VAR = "ln_price_m2"

FILTER_ROOMS_1_3 = True

TEST_SIZE = 0.2
RANDOM_STATE = 42

N_SPLITS = 5

OUTPUT_DIR = "model_6_diagnostics_new_zones"
os.makedirs(OUTPUT_DIR, exist_ok=True)

if not os.path.exists(INPUT_GPKG):
    raise FileNotFoundError(
        f"Не найден файл {INPUT_GPKG}."
    )

gdf = gpd.read_file(INPUT_GPKG, layer=INPUT_LAYER)

print("Файл:", INPUT_GPKG)
print("Слой:", INPUT_LAYER)
print("Всего квартир:", len(gdf))
print("CRS:", gdf.crs)

gdf["rooms_count_num"] = pd.to_numeric(gdf["rooms_count"], errors="coerce")

print("\nРаспределение rooms_count до фильтра:")
print(gdf["rooms_count_num"].value_counts(dropna=False).sort_index())

if FILTER_ROOMS_1_3:
    gdf = gdf[gdf["rooms_count_num"].isin([1, 2, 3])].copy()

print("\nКвартир после фильтра 1–3 комнаты:", len(gdf))
print("\nРаспределение по зонам:")
print(gdf["zone_name"].value_counts(dropna=False))

def safe_log1p(s):
    s = pd.to_numeric(s, errors="coerce")
    s = s.where(s >= 0, np.nan)
    return np.log1p(s)

def zscore(s):
    s = pd.to_numeric(s, errors="coerce")
    mean = s.mean()
    std = s.std()

    if pd.isna(std) or std == 0:
        return pd.Series(0, index=s.index)

    return (s - mean) / std

def material_to_score(x):
    if pd.isna(x):
        return np.nan

    s = str(x).lower().strip()

    if any(v in s for v in ["монолит", "monolith", "monolithic"]):
        return 1.0
    if any(v in s for v in ["кирп", "brick"]):
        return 0.8
    if any(v in s for v in ["блок", "block"]):
        return 0.6
    if any(v in s for v in ["панел", "panel"]):
        return 0.4
    if any(v in s for v in ["дерев", "wood"]):
        return 0.3

    return 0.5

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

def pseudo_r2(y_true, y_pred, baseline_mean=None):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)

    if baseline_mean is None:
        baseline_mean = np.mean(y_true)

    sse_model = np.sum((y_true - y_pred) ** 2)
    sse_baseline = np.sum((y_true - baseline_mean) ** 2)

    if sse_baseline == 0:
        return np.nan

    return 1 - sse_model / sse_baseline

def fit_statsmodels_ols(train_df, y_col, x_cols):
    y_train = train_df[y_col]
    X_train = sm.add_constant(train_df[x_cols], has_constant="add")
    model = sm.OLS(y_train, X_train).fit(cov_type="HC3")
    return model

df = gdf.copy()

df["total_area"] = pd.to_numeric(df["total_area"], errors="coerce")

if "ln_total_area" not in df.columns:
    df["ln_total_area"] = np.log(df["total_area"])

if "floor_comfort_score" not in df.columns:
    df["floor_comfort_score"] = np.nan
    df.loc[df["is_first_floor"] == 1, "floor_comfort_score"] = 0
    df.loc[df["is_last_floor"] == 1, "floor_comfort_score"] = 0.5
    df.loc[df["is_middle_floor"] == 1, "floor_comfort_score"] = 1

if "material_score" not in df.columns:
    df["material_score"] = df["material_type"].apply(material_to_score)

df["building_newness"] = -safe_log1p(df["building_age"])

df["metro_mcc_proximity"] = -safe_log1p(df["dist_nearest_metro_mcc"])
df["mcd_proximity"] = -safe_log1p(df["dist_nearest_mcd"])
df["stop_proximity"] = -safe_log1p(df["dist_nearest_stop"])
df["log_stops_500m"] = safe_log1p(df["stops_500m"])

df["log_schools_1000m"] = safe_log1p(df["schools_1000m"])
df["log_kindergartens_1000m"] = safe_log1p(df["kindergartens_1000m"])
df["log_clinics_1000m"] = safe_log1p(df["clinics_1000m"])
df["log_green_area_1000m"] = safe_log1p(df["green_area_1000m"])

df["green_proximity"] = -safe_log1p(df["dist_nearest_green"])
df["water_proximity"] = -safe_log1p(df["dist_nearest_water"])

df["log_industrial_area_1000m"] = safe_log1p(df["industrial_area_1000m"])

df["x"] = df.geometry.x
df["y"] = df.geometry.y

core_points = df[df["zone_name"] == "core"].copy()

core_x = core_points.geometry.x.mean()
core_y = core_points.geometry.y.mean()

df["dist_to_core_center"] = np.sqrt(
    (df["x"] - core_x) ** 2 +
    (df["y"] - core_y) ** 2
)

df["log_dist_to_core_center"] = np.log1p(df["dist_to_core_center"])

df["x_centered"] = df["x"] - df["x"].mean()
df["y_centered"] = df["y"] - df["y"].mean()

df["x2"] = df["x_centered"] ** 2
df["y2"] = df["y_centered"] ** 2
df["xy"] = df["x_centered"] * df["y_centered"]

component_raw_cols = [

    "ln_total_area",
    "rooms_count",
    "floor_comfort_score",
    "building_newness",
    "material_score",

    "metro_mcc_proximity",
    "mcd_proximity",
    "stop_proximity",
    "log_stops_500m",

    "log_schools_1000m",
    "log_kindergartens_1000m",
    "log_clinics_1000m",
    "log_green_area_1000m",
    "green_proximity",
    "water_proximity",

    "major_road_300m",
    "railway_300m",
    "log_industrial_area_1000m",
    "waste_1000m"
]

for col in component_raw_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")
    df[col] = df[col].fillna(df[col].median())
    df["z_" + col] = zscore(df[col])

spatial_raw_cols = [
    "x_centered",
    "y_centered",
    "x2",
    "y2",
    "xy",
    "log_dist_to_core_center"
]

for col in spatial_raw_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")
    df[col] = df[col].fillna(df[col].median())
    df["z_" + col] = zscore(df[col])

zone_vars = [
    "zone_core",
    "zone_semi_periphery"
]

component_vars = [

    "z_ln_total_area",
    "z_rooms_count",
    "z_floor_comfort_score",
    "z_building_newness",
    "z_material_score",

    "z_metro_mcc_proximity",
    "z_mcd_proximity",
    "z_stop_proximity",
    "z_log_stops_500m",

    "z_log_schools_1000m",
    "z_log_kindergartens_1000m",
    "z_log_clinics_1000m",
    "z_log_green_area_1000m",
    "z_green_proximity",
    "z_water_proximity",

    "z_major_road_300m",
    "z_railway_300m",
    "z_log_industrial_area_1000m",
    "z_waste_1000m"
]

interaction_vars = []

for component in component_vars:
    for zone in zone_vars:
        new_col = f"{component}_x_{zone}"
        df[new_col] = df[component] * df[zone]
        interaction_vars.append(new_col)

spatial_vars = [
    "z_x_centered",
    "z_y_centered",
    "z_x2",
    "z_y2",
    "z_xy",
    "z_log_dist_to_core_center"
]

MODEL_VARS = zone_vars + component_vars + interaction_vars + spatial_vars

print("\nКоличество признаков MODEL 6:", len(MODEL_VARS))

if "hex_group_id" in df.columns:
    GROUP_COL = "hex_group_id"
elif "hex_id" in df.columns:
    GROUP_COL = "hex_id"
else:
    GROUP_COL = None

if GROUP_COL is None:
    print("\n нет hex_group_id/hex_id.")
    df["spatial_group"] = "row_" + df.index.astype(str)
else:
    df["spatial_group"] = df[GROUP_COL].astype("object")

    missing_groups = df["spatial_group"].isna().sum()
    print(f"\nГрупповая колонка для spatial CV: {GROUP_COL}")
    print("Пропусков в группах до заполнения:", missing_groups)

    df.loc[df["spatial_group"].isna(), "spatial_group"] = (
        "missing_group_" + df.loc[df["spatial_group"].isna()].index.astype(str)
    )

df["spatial_group"] = df["spatial_group"].astype(str)

print("Уникальных spatial_group:", df["spatial_group"].nunique())

model_df = df[[DEPENDENT_VAR, "zone_name", "spatial_group", "geometry"] + MODEL_VARS].copy()

for col in [DEPENDENT_VAR] + MODEL_VARS:
    model_df[col] = pd.to_numeric(model_df[col], errors="coerce")

for col in MODEL_VARS:
    model_df[col] = model_df[col].fillna(model_df[col].median())

n_before = len(model_df)
model_df = model_df.dropna(subset=[DEPENDENT_VAR, "zone_name", "spatial_group"]).copy()
n_after = len(model_df)

print("\nНаблюдений до удаления NaN:", n_before)
print("Наблюдений в модели:", n_after)
print("Удалено:", n_before - n_after)

train_df, test_df = train_test_split(
    model_df,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    stratify=model_df["zone_name"]
)

model_random = fit_statsmodels_ols(train_df, DEPENDENT_VAR, MODEL_VARS)

X_train = sm.add_constant(train_df[MODEL_VARS], has_constant="add")
X_test = sm.add_constant(test_df[MODEL_VARS], has_constant="add")

y_train = train_df[DEPENDENT_VAR]
y_test = test_df[DEPENDENT_VAR]

y_train_pred = model_random.predict(X_train)
y_test_pred = model_random.predict(X_test)

train_mean = y_train.mean()

random_metrics = {
    "validation": "random_train_test",
    "n_train": len(train_df),
    "n_test": len(test_df),

    "ols_r2_train": model_random.rsquared,
    "ols_adj_r2_train": model_random.rsquared_adj,

    "pseudo_r2_train": pseudo_r2(y_train, y_train_pred, baseline_mean=train_mean),
    "pseudo_r2_test": pseudo_r2(y_test, y_test_pred, baseline_mean=train_mean),

    "r2_test_sklearn": r2_score(y_test, y_test_pred),

    "rmse_train_log": rmse(y_train, y_train_pred),
    "rmse_test_log": rmse(y_test, y_test_pred),

    "mae_train_log": mean_absolute_error(y_train, y_train_pred),
    "mae_test_log": mean_absolute_error(y_test, y_test_pred)
}

random_metrics_df = pd.DataFrame([random_metrics]).round(4)

print("\nRandom train/test pseudo R² и метрики:")
display(random_metrics_df)

random_metrics_df.to_csv(
    os.path.join(OUTPUT_DIR, "model_6_random_pseudo_r2_metrics.csv"),
    index=False
)

groups = model_df["spatial_group"].astype(str).values

group_cv = GroupKFold(n_splits=N_SPLITS)

fold_rows = []

all_y_true = []
all_y_pred = []
all_baseline_means = []

for fold, (train_idx, test_idx) in enumerate(
    group_cv.split(model_df, groups=groups),
    start=1
):
    fold_train = model_df.iloc[train_idx].copy()
    fold_test = model_df.iloc[test_idx].copy()

    fold_model = fit_statsmodels_ols(fold_train, DEPENDENT_VAR, MODEL_VARS)

    X_fold_train = sm.add_constant(fold_train[MODEL_VARS], has_constant="add")
    X_fold_test = sm.add_constant(fold_test[MODEL_VARS], has_constant="add")

    y_fold_train = fold_train[DEPENDENT_VAR]
    y_fold_test = fold_test[DEPENDENT_VAR]

    y_fold_train_pred = fold_model.predict(X_fold_train)
    y_fold_test_pred = fold_model.predict(X_fold_test)

    fold_train_mean = y_fold_train.mean()

    fold_row = {
        "fold": fold,
        "n_train": len(fold_train),
        "n_test": len(fold_test),
        "n_train_groups": fold_train["spatial_group"].nunique(),
        "n_test_groups": fold_test["spatial_group"].nunique(),

        "r2_train": fold_model.rsquared,
        "adj_r2_train": fold_model.rsquared_adj,

        "pseudo_r2_train": pseudo_r2(
            y_fold_train,
            y_fold_train_pred,
            baseline_mean=fold_train_mean
        ),
        "pseudo_r2_test": pseudo_r2(
            y_fold_test,
            y_fold_test_pred,
            baseline_mean=fold_train_mean
        ),

        "r2_test_sklearn": r2_score(y_fold_test, y_fold_test_pred),

        "rmse_train_log": rmse(y_fold_train, y_fold_train_pred),
        "rmse_test_log": rmse(y_fold_test, y_fold_test_pred),

        "mae_train_log": mean_absolute_error(y_fold_train, y_fold_train_pred),
        "mae_test_log": mean_absolute_error(y_fold_test, y_fold_test_pred)
    }

    fold_rows.append(fold_row)

    all_y_true.extend(y_fold_test.values)
    all_y_pred.extend(y_fold_test_pred.values)
    all_baseline_means.extend([fold_train_mean] * len(fold_test))

spatial_cv_folds = pd.DataFrame(fold_rows)

spatial_cv_summary = pd.DataFrame({
    "metric": [
        "pseudo_r2_test",
        "r2_test_sklearn",
        "rmse_test_log",
        "mae_test_log",
        "pseudo_r2_train",
        "rmse_train_log",
        "mae_train_log"
    ],
    "mean": [
        spatial_cv_folds["pseudo_r2_test"].mean(),
        spatial_cv_folds["r2_test_sklearn"].mean(),
        spatial_cv_folds["rmse_test_log"].mean(),
        spatial_cv_folds["mae_test_log"].mean(),
        spatial_cv_folds["pseudo_r2_train"].mean(),
        spatial_cv_folds["rmse_train_log"].mean(),
        spatial_cv_folds["mae_train_log"].mean()
    ],
    "std": [
        spatial_cv_folds["pseudo_r2_test"].std(),
        spatial_cv_folds["r2_test_sklearn"].std(),
        spatial_cv_folds["rmse_test_log"].std(),
        spatial_cv_folds["mae_test_log"].std(),
        spatial_cv_folds["pseudo_r2_train"].std(),
        spatial_cv_folds["rmse_train_log"].std(),
        spatial_cv_folds["mae_train_log"].std()
    ]
})

all_y_true = np.asarray(all_y_true)
all_y_pred = np.asarray(all_y_pred)
all_baseline_means = np.asarray(all_baseline_means)

sse_model_oof = np.sum((all_y_true - all_y_pred) ** 2)
sse_baseline_oof = np.sum((all_y_true - all_baseline_means) ** 2)

spatial_pseudo_r2_oof = 1 - sse_model_oof / sse_baseline_oof

spatial_oof_metrics = pd.DataFrame([{
    "validation": "spatial_GroupKFold_oof",
    "n_observations_oof": len(all_y_true),
    "n_splits": N_SPLITS,
    "spatial_pseudo_r2_oof": spatial_pseudo_r2_oof,
    "rmse_oof_log": rmse(all_y_true, all_y_pred),
    "mae_oof_log": mean_absolute_error(all_y_true, all_y_pred)
}])

print("\nSpatial CV по fold:")
display(spatial_cv_folds.round(4))

print("\nSpatial CV summary:")
display(spatial_cv_summary.round(4))

print("\nSpatial pseudo R² out-of-fold:")
display(spatial_oof_metrics.round(4))

spatial_cv_folds.round(4).to_csv(
    os.path.join(OUTPUT_DIR, "model_6_spatial_cv_folds.csv"),
    index=False
)

spatial_cv_summary.round(4).to_csv(
    os.path.join(OUTPUT_DIR, "model_6_spatial_cv_summary.csv"),
    index=False
)

spatial_oof_metrics.round(4).to_csv(
    os.path.join(OUTPUT_DIR, "model_6_spatial_pseudo_r2_oof.csv"),
    index=False
)

full_model = fit_statsmodels_ols(model_df, DEPENDENT_VAR, MODEL_VARS)

X_full = sm.add_constant(model_df[MODEL_VARS], has_constant="add")
y_full = model_df[DEPENDENT_VAR]

model_df["y_pred_full"] = full_model.predict(X_full)
model_df["residual_full"] = y_full - model_df["y_pred_full"]
model_df["abs_residual_full"] = model_df["residual_full"].abs()

full_metrics = {
    "validation": "full_sample",
    "n": len(model_df),
    "ols_r2": full_model.rsquared,
    "ols_adj_r2": full_model.rsquared_adj,
    "pseudo_r2_full": pseudo_r2(
        y_full,
        model_df["y_pred_full"],
        baseline_mean=y_full.mean()
    ),
    "rmse_full_log": rmse(y_full, model_df["y_pred_full"]),
    "mae_full_log": mean_absolute_error(y_full, model_df["y_pred_full"])
}

full_metrics_df = pd.DataFrame([full_metrics]).round(4)

print("\nFull sample metrics:")
display(full_metrics_df)

full_metrics_df.to_csv(
    os.path.join(OUTPUT_DIR, "model_6_full_sample_metrics.csv"),
    index=False
)

try:
    from libpysal.weights import KNN
    from esda.moran import Moran

    residual_gdf = gpd.GeoDataFrame(
        model_df.copy(),
        geometry="geometry",
        crs=gdf.crs
    )

    residual_gdf = residual_gdf.dropna(subset=["residual_full"]).copy()

    K_NEIGHBORS = 8

    w_knn = KNN.from_dataframe(
        residual_gdf,
        k=K_NEIGHBORS
    )

    w_knn.transform = "R"

    moran = Moran(
        residual_gdf["residual_full"].values,
        w_knn,
        permutations=999
    )

    moran_results = pd.DataFrame([{
        "variable": "residual_full",
        "weights": f"KNN_k{K_NEIGHBORS}",
        "n": len(residual_gdf),
        "moran_I": moran.I,
        "expected_I": moran.EI,
        "z_norm": moran.z_norm,
        "p_norm": moran.p_norm,
        "z_rand": moran.z_rand,
        "p_rand": moran.p_rand,
        "p_sim": moran.p_sim,
        "permutations": 999
    }])

    print("\nMoran's I по остаткам полной модели:")
    display(moran_results.round(4))

    moran_results.round(4).to_csv(
        os.path.join(OUTPUT_DIR, "model_6_morans_i_residuals.csv"),
        index=False
    )

except ImportError:
    print("\nНе установлены libpysal/esda.")
    print("Запусти в отдельной ячейке:")
    print("!pip install libpysal esda")
    print("После установки перезапусти блок Moran's I.")

residuals_out = model_df[
    [
        DEPENDENT_VAR,
        "y_pred_full",
        "residual_full",
        "abs_residual_full",
        "zone_name",
        "spatial_group",
        "geometry"
    ]
].copy()

residuals_gdf = gpd.GeoDataFrame(
    residuals_out,
    geometry="geometry",
    crs=gdf.crs
)

residuals_gpkg = os.path.join(
    OUTPUT_DIR,
    "model_6_residuals.gpkg"
)

if os.path.exists(residuals_gpkg):
    os.remove(residuals_gpkg)

residuals_gdf.to_file(
    residuals_gpkg,
    layer="model_6_residuals",
    driver="GPKG"
)

residuals_gdf.drop(columns="geometry").to_csv(
    os.path.join(OUTPUT_DIR, "model_6_residuals.csv"),
    index=False
)

print("\nГотово.")
print("Все результаты сохранены в папку:", OUTPUT_DIR)

Файл: apartments_hedonic_indices.gpkg
Слой: apartments_hedonic_indices
Всего квартир: 31570
CRS: EPSG:32637

Распределение rooms_count до фильтра:
rooms_count_num
1.0    5858
2.0    9885
3.0    8904
4.0    3315
5.0     991
6.0     295
NaN    2322
Name: count, dtype: int64

Квартир после фильтра 1–3 комнаты: 24647

Распределение по зонам:
zone_name
periphery         11205
semi_periphery     9747
core               3695
Name: count, dtype: int64

Количество признаков MODEL 6: 65

Групповая колонка для spatial CV: hex_id
Пропусков в группах до заполнения: 0
Уникальных spatial_group: 975

Наблюдений до удаления NaN: 24647
Наблюдений в модели: 24647
Удалено: 0

Random train/test pseudo R² и метрики:

,validation,n_train,n_test,ols_r2_train,ols_adj_r2_train,pseudo_r2_train,pseudo_r2_test,r2_test_sklearn,rmse_train_log,rmse_test_log,mae_train_log,mae_test_log
0,random_train_test,19717,4930,0.6215,0.6202,0.6215,0.6072,0.607,0.2677,0.2812,0.1846,0.1916

Spatial CV по fold:

,fold,n_train,n_test,n_train_groups,n_test_groups,r2_train,adj_r2_train,pseudo_r2_train,pseudo_r2_test,r2_test_sklearn,rmse_train_log,rmse_test_log,mae_train_log,mae_test_log
0,1,19717,4930,781,194,0.6192,0.6179,0.6192,0.6119,0.6116,0.2701,0.2733,0.1860,0.1863
1,2,19717,4930,779,196,0.6168,0.6155,0.6168,0.6195,0.6195,0.2719,0.2666,0.1861,0.1876
2,3,19718,4929,780,195,0.6253,0.6241,0.6253,0.5793,0.5776,0.2688,0.2808,0.1845,0.1949
3,4,19718,4929,780,195,0.6195,0.6182,0.6195,0.6027,0.6024,0.2709,0.2727,0.1871,0.1878
4,5,19718,4929,780,195,0.6214,0.6202,0.6214,0.5989,0.5945,0.2670,0.2874,0.1841,0.1961

Spatial CV summary:

            metric    mean     std
0   pseudo_r2_test  0.6025  0.0153
1  r2_test_sklearn  0.6011  0.0162
2    rmse_test_log  0.2761  0.0080
3     mae_test_log  0.1905  0.0046
4  pseudo_r2_train  0.6204  0.0032
5   rmse_train_log  0.2697  0.0019
6    mae_train_log  0.1856  0.0012

Spatial pseudo R² out-of-fold:

,validation,n_observations_oof,n_splits,spatial_pseudo_r2_oof,rmse_oof_log,mae_oof_log
0,spatial_GroupKFold_oof,24647,5,0.6024,0.2762,0.1905

Full sample metrics:

,validation,n,ols_r2,ols_adj_r2,pseudo_r2_full,rmse_full_log,mae_full_log
0,full_sample,24647,0.6187,0.6177,0.6187,0.2703,0.186

Moran's I по остаткам полной модели:

,variable,weights,n,moran_I,expected_I,z_norm,p_norm,z_rand,p_rand,p_sim,permutations
0,residual_full,KNN_k8,24647,0.3124,-0.0,106.7,0.0,106.7159,0.0,0.001,999

Готово.
Все результаты сохранены в папку: model_6_diagnostics_new_zones

In [ ]:
import os
import numpy as np
import pandas as pd
import statsmodels.api as sm

if "OUTPUT_DIR" not in globals():
    OUTPUT_DIR = "model_6_diagnostics"

os.makedirs(OUTPUT_DIR, exist_ok=True)

if "full_model" in globals():
    final_model = full_model
elif "model_full" in globals():
    final_model = model_full
elif "model" in globals():
    final_model = model
else:
    raise NameError("Не найдена финальная модель: full_model / model_full / model")

if "model_df" not in globals():
    raise NameError("Не найден model_df.")

if "MODEL_VARS" not in globals():
    raise NameError("Не найден MODEL_VARS.")

X_export = sm.add_constant(model_df[MODEL_VARS], has_constant="add")
y_export = model_df[DEPENDENT_VAR]

if "y_pred_full" not in model_df.columns:
    model_df["y_pred_full"] = final_model.predict(X_export)

if "residual_full" not in model_df.columns:
    model_df["residual_full"] = y_export - model_df["y_pred_full"]

if "abs_residual_full" not in model_df.columns:
    model_df["abs_residual_full"] = model_df["residual_full"].abs()

In [ ]:
coef_df = pd.DataFrame({
    "variable": final_model.params.index,
    "coef_log": final_model.params.values,
    "std_err": final_model.bse.values,
    "t_value": final_model.tvalues.values,
    "p_value": final_model.pvalues.values,
    "ci_low": final_model.conf_int()[0].values,
    "ci_high": final_model.conf_int()[1].values
})

coef_df["effect_percent"] = (np.exp(coef_df["coef_log"]) - 1) * 100
coef_df["ci_low_percent"] = (np.exp(coef_df["ci_low"]) - 1) * 100
coef_df["ci_high_percent"] = (np.exp(coef_df["ci_high"]) - 1) * 100

coef_df["abs_coef_log"] = coef_df["coef_log"].abs()
coef_df["significant_5pct"] = coef_df["p_value"] < 0.05
coef_df["significant_10pct"] = coef_df["p_value"] < 0.10

def classify_variable(var):
    if var == "const":
        return "constant"

    if var in ["zone_core", "zone_semi_periphery"]:
        return "zone_dummy"

    if var in component_vars:
        return "base_component"

    if "zone_core" in var and "_x_" in var:
        return "interaction_core"

    if "zone_semi_periphery" in var and "_x_" in var:
        return "interaction_semi_periphery"

    if "spatial_vars" in globals() and var in spatial_vars:
        return "spatial_control"

    return "other"

def extract_base_component(var):
    if "_x_zone_core" in var:
        return var.replace("_x_zone_core", "")

    if "_x_zone_semi_periphery" in var:
        return var.replace("_x_zone_semi_periphery", "")

    return var

coef_df["term_type"] = coef_df["variable"].apply(classify_variable)
coef_df["base_component"] = coef_df["variable"].apply(extract_base_component)

coef_df = coef_df.sort_values("abs_coef_log", ascending=False)

coef_path = os.path.join(OUTPUT_DIR, "model_6_coefficients.csv")

coef_df.to_csv(
    coef_path,
    index=False,
    encoding="utf-8-sig"
)

print("Файл с коэффициентами сохранён:", coef_path)

display(
    coef_df[
        [
            "variable",
            "term_type",
            "base_component",
            "coef_log",
            "effect_percent",
            "p_value",
            "significant_5pct",
            "ci_low",
            "ci_high"
        ]
    ].round(4)
)

Файл с коэффициентами сохранён: model_6_diagnostics_new_zones/model_6_coefficients.csv

,variable,term_type,base_component,coef_log,effect_percent,p_value,significant_5pct,ci_low,ci_high
0,const,constant,const,12.9403,4.167706e+07,0.0000,True,12.9292,12.9514
65,z_log_dist_to_core_center,spatial_control,z_log_dist_to_core_center,-0.1680,-1.546660e+01,0.0000,True,-0.1865,-0.1496
22,z_ln_total_area_x_zone_core,interaction_core,z_ln_total_area,0.0980,1.029100e+01,0.0000,True,0.0757,0.1202
6,z_building_newness,base_component,z_building_newness,0.0932,9.763500e+00,0.0000,True,0.0869,0.0994
34,z_mcd_proximity_x_zone_core,interaction_core,z_mcd_proximity,-0.0778,-7.485800e+00,0.0000,True,-0.0965,-0.0591
...,...,...,...,...,...,...,...,...,...
10,z_stop_proximity,base_component,z_stop_proximity,-0.0024,-2.375000e-01,0.3360,False,-0.0072,0.0025
16,z_green_proximity,base_component,z_green_proximity,0.0020,1.971000e-01,0.4402,False,-0.0030,0.0070
64,z_xy,spatial_control,z_xy,-0.0017,-1.747000e-01,0.2757,False,-0.0049,0.0014
3,z_ln_total_area,base_component,z_ln_total_area,0.0010,1.002000e-01,0.8633,False,-0.0104,0.0124
47,z_log_green_area_1000m_x_zone_semi_periphery,interaction_semi_periphery,z_log_green_area_1000m,0.0004,3.900000e-02,0.9302,False,-0.0083,0.0091

In [ ]:
if "OUTPUT_DIR" not in globals() or OUTPUT_DIR == "model_6_diagnostics":
    OUTPUT_DIR = "model_6_diagnostics_new_zones"
    os.makedirs(OUTPUT_DIR, exist_ok=True)

base_export_cols = [
    DEPENDENT_VAR,
    "zone_name",
    "spatial_group",
    "y_pred_full",
    "residual_full",
    "abs_residual_full"
]

base_export_cols = [
    col for col in base_export_cols
    if col in model_df.columns
]

model_export_cols = [
    col for col in MODEL_VARS
    if col in model_df.columns
]

modeling_data = model_df[base_export_cols + model_export_cols].copy()

raw_feature_cols = [

    "hex_id",
    "hex_group_id",
    "x",
    "y",

    "price",
    "price_m2",
    "ln_price",
    "ln_price_m2",

    "total_area",
    "ln_total_area",
    "rooms_count",
    "rooms_count_num",
    "floor",
    "floor_comfort_score",

    "building_year",
    "building_age",
    "building_newness",
    "material_type",
    "material_score",

    "dist_nearest_metro_mcc",
    "dist_nearest_mcd",
    "dist_nearest_stop",
    "stops_500m",
    "metro_mcc_proximity",
    "mcd_proximity",
    "stop_proximity",
    "log_stops_500m",

    "schools_1000m",
    "kindergartens_1000m",
    "clinics_1000m",
    "log_schools_1000m",
    "log_kindergartens_1000m",
    "log_clinics_1000m",

    "green_area_1000m",
    "dist_nearest_green",
    "dist_nearest_water",
    "log_green_area_1000m",
    "green_proximity",
    "water_proximity",

    "major_road_300m",
    "railway_300m",
    "industrial_area_1000m",
    "log_industrial_area_1000m",
    "waste_1000m",

    "x_centered",
    "y_centered",
    "x2",
    "y2",
    "xy",
    "dist_to_core_center",
    "log_dist_to_core_center"
]

if "df" in globals():
    available_raw_cols = [
        col for col in raw_feature_cols
        if col in df.columns and col not in modeling_data.columns
    ]

    if len(available_raw_cols) > 0:
        raw_part = df.loc[modeling_data.index, available_raw_cols].copy()
        modeling_data = pd.concat([modeling_data, raw_part], axis=1)

if "geometry" in model_df.columns and "geometry_wkt" not in modeling_data.columns:
    modeling_data["geometry_wkt"] = model_df["geometry"].apply(
        lambda g: g.wkt if pd.notna(g) else np.nan
    )

modeling_data_path = os.path.join(OUTPUT_DIR, "model_6_modeling_data.csv")

modeling_data.to_csv(
    modeling_data_path,
    index=False,
    encoding="utf-8-sig"
)

print("Файл с таблицей модели сохранён:", modeling_data_path)
print("Размер таблицы:", modeling_data.shape)

display(modeling_data.head())

Файл с таблицей модели сохранён: model_6_diagnostics_new_zones/model_6_modeling_data.csv
Размер таблицы: (24647, 120)

,ln_price_m2,zone_name,spatial_group,y_pred_full,residual_full,abs_residual_full,zone_core,zone_semi_periphery,z_ln_total_area,z_rooms_count,...,log_industrial_area_1000m,waste_1000m,x_centered,y_centered,x2,y2,xy,dist_to_core_center,log_dist_to_core_center,geometry_wkt
0,11.374279,periphery,3135.0,12.382022,-1.007743,1.007743,0.0,0.0,-0.667346,-0.161762,...,11.421417,1,14899.115148,6867.946207,2.219836e+08,4.716869e+07,1.023263e+08,14165.172349,9.558612,POINT (426256.20864518086 6186032.815401154)
1,11.581918,periphery,3082.0,12.633750,-1.051832,1.051832,0.0,0.0,-0.838285,-0.161762,...,12.397745,0,14253.548553,-190.346170,2.031636e+08,3.623166e+04,-2.713108e+06,12467.320330,9.430946,POINT (425610.64204979566 6178974.523024487)
2,11.907217,periphery,3082.0,12.349321,-0.442103,0.442103,0.0,0.0,0.106421,1.147148,...,11.882750,0,14137.014966,-641.855718,1.998552e+08,4.119788e+05,-9.073924e+06,12414.101152,9.426669,POINT (425494.1084634445 6178523.013476344)
5,11.289782,periphery,3015.0,12.705798,-1.416016,1.416016,0.0,0.0,-0.655548,-0.161762,...,0.000000,0,13699.211578,4586.111933,1.876684e+08,2.103242e+07,6.282612e+07,12272.787732,9.415221,POINT (425056.3050755324 6183750.981127375)
6,12.500312,semi_periphery,2960.0,12.705694,-0.205382,0.205382,0.0,1.0,-2.939274,-1.470672,...,12.021625,0,12700.648708,-724.776329,1.613065e+08,5.253007e+05,-9.205130e+06,11012.578770,9.306884,POINT (424057.74220482836 6178440.092864576)

Аналитика

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

coef_path = Path("model_6_diagnostics_new_zones") / "model_6_coefficients.csv"
coef_df = pd.read_csv(coef_path)

coef_dict = dict(zip(coef_df["variable"], coef_df["coef_log"]))

base_vars = [

    "z_ln_total_area",
    "z_rooms_count",
    "z_floor_comfort_score",
    "z_building_newness",
    "z_material_score",

    "z_metro_mcc_proximity",
    "z_mcd_proximity",
    "z_stop_proximity",
    "z_log_stops_500m",

    "z_log_schools_1000m",
    "z_log_kindergartens_1000m",
    "z_log_clinics_1000m",
    "z_log_green_area_1000m",
    "z_green_proximity",
    "z_water_proximity",

    "z_major_road_300m",
    "z_railway_300m",
    "z_log_industrial_area_1000m",
    "z_waste_1000m",
]

def get_zone_coef(var, zone):
    """
    Возвращает коэффициент переменной в конкретной зоне.

    periphery:
        beta

    core:
        beta + beta_x_zone_core

    semi_periphery:
        beta + beta_x_zone_semi_periphery
    """

    base_coef = coef_dict.get(var, 0)

    if zone == "periphery":
        return base_coef

    elif zone == "core":
        interaction_name = f"{var}_x_zone_core"
        interaction_coef = coef_dict.get(interaction_name, 0)
        return base_coef + interaction_coef

    elif zone == "semi_periphery":
        interaction_name = f"{var}_x_zone_semi_periphery"
        interaction_coef = coef_dict.get(interaction_name, 0)
        return base_coef + interaction_coef

    else:
        raise ValueError("zone должна быть: periphery, core или semi_periphery")

rows = []

for var in base_vars:
    for zone in ["core", "semi_periphery", "periphery"]:
        beta_zone = get_zone_coef(var, zone)

        rows.append({
            "variable": var,
            "zone": zone,
            "coef_log": beta_zone,
            "effect_percent": (np.exp(beta_zone) - 1) * 100,
            "abs_coef_log": abs(beta_zone)
        })

zone_effects = pd.DataFrame(rows)

zone_effects = zone_effects.sort_values(
    ["zone", "abs_coef_log"],
    ascending=[True, False]
)

display(zone_effects.round(4))

zone_effects.to_csv(
    "model_6_zone_variable_effects.csv",
    index=False,
    encoding="utf-8-sig"
)

,variable,zone,coef_log,effect_percent,abs_coef_log
9,z_building_newness,core,0.1117,11.8149,0.1117
0,z_ln_total_area,core,0.0990,10.4015,0.0990
3,z_rooms_count,core,-0.0967,-9.2166,0.0967
18,z_mcd_proximity,core,-0.0940,-8.9702,0.0940
12,z_material_score,core,0.0820,8.5453,0.0820
42,z_water_proximity,core,0.0604,6.2282,0.0604
27,z_log_schools_1000m,core,0.0509,5.2186,0.0509
6,z_floor_comfort_score,core,0.0484,4.9635,0.0484
30,z_log_kindergartens_1000m,core,0.0475,4.8666,0.0475
51,z_log_industrial_area_1000m,core,-0.0401,-3.9281,0.0401
54,z_waste_1000m,core,0.0309,3.1419,0.0309
24,z_log_stops_500m,core,-0.0285,-2.8138,0.0285
36,z_log_green_area_1000m,core,0.0173,1.7435,0.0173
21,z_stop_proximity,core,-0.0150,-1.4877,0.0150
33,z_log_clinics_1000m,core,0.0109,1.0916,0.0109
15,z_metro_mcc_proximity,core,0.0080,0.7996,0.0080
45,z_major_road_300m,core,0.0069,0.6894,0.0069
48,z_railway_300m,core,-0.0040,-0.3987,0.0040
39,z_green_proximity,core,-0.0030,-0.3032,0.0030
11,z_building_newness,periphery,0.0932,9.7635,0.0932
5,z_rooms_count,periphery,-0.0582,-5.6526,0.0582
17,z_metro_mcc_proximity,periphery,0.0452,4.6238,0.0452
14,z_material_score,periphery,0.0410,4.1877,0.0410
8,z_floor_comfort_score,periphery,0.0279,2.8255,0.0279
29,z_log_schools_1000m,periphery,-0.0262,-2.5829,0.0262
26,z_log_stops_500m,periphery,-0.0203,-2.0124,0.0203
32,z_log_kindergartens_1000m,periphery,0.0198,1.9949,0.0198
50,z_railway_300m,periphery,-0.0176,-1.7424,0.0176
20,z_mcd_proximity,periphery,-0.0162,-1.6046,0.0162
53,z_log_industrial_area_1000m,periphery,-0.0132,-1.3145,0.0132
44,z_water_proximity,periphery,0.0123,1.2345,0.0123
56,z_waste_1000m,periphery,-0.0100,-0.9976,0.0100
47,z_major_road_300m,periphery,-0.0095,-0.9414,0.0095
38,z_log_green_area_1000m,periphery,0.0084,0.8444,0.0084
35,z_log_clinics_1000m,periphery,0.0028,0.2846,0.0028
23,z_stop_proximity,periphery,-0.0024,-0.2375,0.0024
41,z_green_proximity,periphery,0.0020,0.1971,0.0020
2,z_ln_total_area,periphery,0.0010,0.1002,0.0010
10,z_building_newness,semi_periphery,0.0853,8.9064,0.0853
4,z_rooms_count,semi_periphery,-0.0760,-7.3209,0.0760
13,z_material_score,semi_periphery,0.0683,7.0690,0.0683
1,z_ln_total_area,semi_periphery,0.0616,6.3494,0.0616
7,z_floor_comfort_score,semi_periphery,0.0544,5.5911,0.0544
25,z_log_stops_500m,semi_periphery,-0.0443,-4.3314,0.0443
52,z_log_industrial_area_1000m,semi_periphery,-0.0411,-4.0227,0.0411
31,z_log_kindergartens_1000m,semi_periphery,-0.0408,-4.0012,0.0408
34,z_log_clinics_1000m,semi_periphery,0.0338,3.4422,0.0338
55,z_waste_1000m,semi_periphery,-0.0306,-3.0106,0.0306
22,z_stop_proximity,semi_periphery,-0.0277,-2.7284,0.0277
40,z_green_proximity,semi_periphery,0.0260,2.6383,0.0260
16,z_metro_mcc_proximity,semi_periphery,0.0250,2.5338,0.0250
49,z_railway_300m,semi_periphery,-0.0213,-2.1033,0.0213
43,z_water_proximity,semi_periphery,0.0159,1.6073,0.0159
28,z_log_schools_1000m,semi_periphery,0.0144,1.4542,0.0144
46,z_major_road_300m,semi_periphery,0.0125,1.2560,0.0125
37,z_log_green_area_1000m,semi_periphery,0.0088,0.8838,0.0088
19,z_mcd_proximity,semi_periphery,0.0067,0.6748,0.0067

In [ ]:
feature_groups = {
    "Внутренние характеристики квартиры и дома": [
        "z_ln_total_area",
        "z_rooms_count",
        "z_floor_comfort_score",
        "z_building_newness",
        "z_material_score",
    ],

    "Транспортная доступность": [
        "z_metro_mcc_proximity",
        "z_mcd_proximity",
        "z_stop_proximity",
        "z_log_stops_500m",
    ],

    "Позитивные внешние характеристики": [
        "z_log_schools_1000m",
        "z_log_kindergartens_1000m",
        "z_log_clinics_1000m",
        "z_log_green_area_1000m",
        "z_green_proximity",
        "z_water_proximity",
    ],

    "Негативные внешние характеристики": [
        "z_major_road_300m",
        "z_railway_300m",
        "z_log_industrial_area_1000m",
        "z_waste_1000m",
    ],
}

def get_feature_group(var):
    for group_name, vars_list in feature_groups.items():
        if var in vars_list:
            return group_name
    return "Прочее"

zone_effects["feature_group"] = zone_effects["variable"].apply(get_feature_group)

zone_effects_grouped = zone_effects[
    zone_effects["feature_group"] != "Прочее"
].copy()

group_strength = (
    zone_effects_grouped
    .groupby(["zone", "feature_group"], as_index=False)
    .agg(
        block_strength_abs_beta=("abs_coef_log", "sum"),
        mean_abs_beta=("abs_coef_log", "mean"),
        n_features=("variable", "count")
    )
)

group_strength["block_share"] = (
    group_strength["block_strength_abs_beta"]
    / group_strength.groupby("zone")["block_strength_abs_beta"].transform("sum")
)

group_strength["block_share_percent"] = group_strength["block_share"] * 100

group_strength = group_strength.sort_values(
    ["zone", "block_strength_abs_beta"],
    ascending=[True, False]
)

display(group_strength.round(4))

group_strength.to_csv(
    "model_6_zone_block_strength.csv",
    index=False,
    encoding="utf-8-sig"
)

,zone,feature_group,block_strength_abs_beta,mean_abs_beta,n_features,block_share,block_share_percent
0,core,Внутренние характеристики квартиры и дома,0.4378,0.0876,5,0.5119,51.1944
2,core,Позитивные внешние характеристики,0.1900,0.0317,6,0.2222,22.2179
3,core,Транспортная доступность,0.1455,0.0364,4,0.1701,17.0129
1,core,Негативные внешние характеристики,0.0819,0.0205,4,0.0957,9.5748
4,periphery,Внутренние характеристики квартиры и дома,0.2212,0.0442,5,0.5181,51.8085
7,periphery,Транспортная доступность,0.0841,0.0210,4,0.1969,19.6908
6,periphery,Позитивные внешние характеристики,0.0714,0.0119,6,0.1672,16.7231
5,periphery,Негативные внешние характеристики,0.0503,0.0126,4,0.1178,11.7776
8,semi_periphery,Внутренние характеристики квартиры и дома,0.3456,0.0691,5,0.4976,49.7592
10,semi_periphery,Позитивные внешние характеристики,0.1399,0.0233,6,0.2014,20.1419
9,semi_periphery,Негативные внешние характеристики,0.1054,0.0263,4,0.1517,15.1700
11,semi_periphery,Транспортная доступность,0.1037,0.0259,4,0.1493,14.9289

In [ ]:

pivot_strength = group_strength.pivot(
    index="feature_group",
    columns="zone",
    values="block_strength_abs_beta"
)

pivot_share = group_strength.pivot(
    index="feature_group",
    columns="zone",
    values="block_share_percent"
)

print("Сила блоков: сумма модулей коэффициентов")
display(pivot_strength.round(4))

print("Доля блоков внутри зоны, %")
display(pivot_share.round(1))

pivot_strength.to_csv(
    "model_6_zone_block_strength_pivot.csv",
    encoding="utf-8-sig"
)

pivot_share.to_csv(
    "model_6_zone_block_share_pivot.csv",
    encoding="utf-8-sig"
)

Сила блоков: сумма модулей коэффициентов

zone                                         core  periphery  semi_periphery
feature_group
Внутренние характеристики квартиры и дома  0.4378     0.2212          0.3456
Негативные внешние характеристики          0.0819     0.0503          0.1054
Позитивные внешние характеристики          0.1900     0.0714          0.1399
Транспортная доступность                   0.1455     0.0841          0.1037

Доля блоков внутри зоны, %

zone                                       core  periphery  semi_periphery
feature_group
Внутренние характеристики квартиры и дома  51.2       51.8            49.8
Негативные внешние характеристики           9.6       11.8            15.2
Позитивные внешние характеристики          22.2       16.7            20.1
Транспортная доступность                   17.0       19.7            14.9

In [ ]:
ranking = group_strength.copy()

ranking["rank_in_zone"] = (
    ranking
    .groupby("zone")["block_strength_abs_beta"]
    .rank(method="dense", ascending=False)
    .astype(int)
)

ranking = ranking.sort_values(["zone", "rank_in_zone"])

display(
    ranking[
        [
            "zone",
            "rank_in_zone",
            "feature_group",
            "block_strength_abs_beta",
            "block_share_percent",
            "n_features"
        ]
    ].round(4)
)

ranking.to_csv(
    "model_6_zone_block_ranking.csv",
    index=False,
    encoding="utf-8-sig"
)

,zone,rank_in_zone,feature_group,block_strength_abs_beta,block_share_percent,n_features
0,core,1,Внутренние характеристики квартиры и дома,0.4378,51.1944,5
2,core,2,Позитивные внешние характеристики,0.1900,22.2179,6
3,core,3,Транспортная доступность,0.1455,17.0129,4
1,core,4,Негативные внешние характеристики,0.0819,9.5748,4
4,periphery,1,Внутренние характеристики квартиры и дома,0.2212,51.8085,5
7,periphery,2,Транспортная доступность,0.0841,19.6908,4
6,periphery,3,Позитивные внешние характеристики,0.0714,16.7231,6
5,periphery,4,Негативные внешние характеристики,0.0503,11.7776,4
8,semi_periphery,1,Внутренние характеристики квартиры и дома,0.3456,49.7592,5
10,semi_periphery,2,Позитивные внешние характеристики,0.1399,20.1419,6
9,semi_periphery,3,Негативные внешние характеристики,0.1054,15.1700,4
11,semi_periphery,4,Транспортная доступность,0.1037,14.9289,4

In [ ]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from pathlib import Path
from IPython.display import display, Markdown

DATA_PATH = Path("model_6_diagnostics_new_zones/model_6_modeling_data.csv")

if DATA_PATH.exists():
    df = pd.read_csv(DATA_PATH)
elif "modeling_data" in globals():
    df = modeling_data.copy()
    print("Файл model_6_modeling_data.csv не найден")
else:
    raise FileNotFoundError(
        "Не найден model_6_diagnostics_new_zones/model_6_modeling_data.csv."
    )

OUTPUT_DIR = Path("zone_models_3_separate_no_interactions_linear_space")
OUTPUT_DIR.mkdir(exist_ok=True)

TARGET_COL = "ln_price_m2"
ZONE_COL = "zone_name"

print("Размер данных для трех отдельных зональных моделей:", df.shape)
print("Зоны:")
display(df[ZONE_COL].value_counts())

Размер данных для трех отдельных зональных моделей: (24647, 120)
Зоны:

zone_name
periphery         11205
semi_periphery     9747
core               3695
Name: count, dtype: int64

In [ ]:
internal_vars = [
    "z_ln_total_area",
    "z_rooms_count",
    "z_floor_comfort_score",
    "z_building_newness",
    "z_material_score",
]

transport_vars = [
    "z_metro_mcc_proximity",
    "z_mcd_proximity",
    "z_stop_proximity",
    "z_log_stops_500m",
]

positive_external_vars = [
    "z_log_schools_1000m",
    "z_log_kindergartens_1000m",
    "z_log_clinics_1000m",
    "z_log_green_area_1000m",
    "z_green_proximity",
    "z_water_proximity",
]

negative_external_vars = [
    "z_major_road_300m",
    "z_railway_300m",
    "z_log_industrial_area_1000m",
    "z_waste_1000m",
]

spatial_vars = [
    "z_x_centered",
    "z_y_centered",
]

feature_groups = {
    "Внутренние характеристики квартиры и дома": internal_vars,
    "Транспортная доступность": transport_vars,
    "Позитивные внешние характеристики": positive_external_vars,
    "Негативные внешние характеристики": negative_external_vars,
}

MODEL_VARS = (
    internal_vars
    + transport_vars
    + positive_external_vars
    + negative_external_vars
    + spatial_vars
)

MODEL_VARS = [col for col in MODEL_VARS if col in df.columns]

print("Число признаков в отдельных зональных моделях без zone×feature и без x2/y2/xy:", len(MODEL_VARS))
print(MODEL_VARS)

Число признаков в отдельных зональных моделях без zone×feature и без x2/y2/xy: 21
['z_ln_total_area', 'z_rooms_count', 'z_floor_comfort_score', 'z_building_newness', 'z_material_score', 'z_metro_mcc_proximity', 'z_mcd_proximity', 'z_stop_proximity', 'z_log_stops_500m', 'z_log_schools_1000m', 'z_log_kindergartens_1000m', 'z_log_clinics_1000m', 'z_log_green_area_1000m', 'z_green_proximity', 'z_water_proximity', 'z_major_road_300m', 'z_railway_300m', 'z_log_industrial_area_1000m', 'z_waste_1000m', 'z_x_centered', 'z_y_centered']

In [ ]:
def regression_metrics(y_true, y_pred, n_params=None):
    residuals = y_true - y_pred

    sse = np.sum(residuals ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)

    r2 = 1 - sse / sst

    rmse = np.sqrt(np.mean(residuals ** 2))
    mae = np.mean(np.abs(residuals))

    if n_params is not None:
        n = len(y_true)
        adj_r2 = 1 - (1 - r2) * (n - 1) / (n - n_params - 1)
    else:
        adj_r2 = np.nan

    return {
        "r2": r2,
        "adj_r2": adj_r2,
        "rmse_log": rmse,
        "mae_log": mae,
        "mae_percent_approx": (np.exp(mae) - 1) * 100,
        "rmse_percent_approx": (np.exp(rmse) - 1) * 100,
    }

def get_feature_group(var):
    for group_name, vars_list in feature_groups.items():
        if var in vars_list:
            return group_name

    if var in spatial_vars:
        return "Пространственные контроли"

    if var == "const":
        return "Константа"

    return "Прочее"

In [ ]:
zone_order = ["core", "semi_periphery", "periphery"]

zone_names_ru = {
    "core": "центр",
    "semi_periphery": "полупериферия",
    "periphery": "периферия",
}

models = {}
metrics_rows = []
coef_rows = []
pred_rows = []

for zone in zone_order:

    zone_df = df[df[ZONE_COL] == zone].copy()

    needed_cols = [TARGET_COL] + MODEL_VARS
    zone_df = zone_df.dropna(subset=needed_cols).copy()

    if len(zone_df) < len(MODEL_VARS) + 5:
        print(f"Пропускаю зону {zone}: слишком мало наблюдений после dropna ({len(zone_df)}).")
        continue

    X = zone_df[MODEL_VARS].copy()
    X = sm.add_constant(X, has_constant="add")

    y = zone_df[TARGET_COL].copy()

    if "spatial_group" in zone_df.columns and zone_df["spatial_group"].nunique() >= 10:
        model = sm.OLS(y, X).fit(
            cov_type="cluster",
            cov_kwds={"groups": zone_df["spatial_group"]}
        )
        se_type = "cluster_by_spatial_group"
    else:
        model = sm.OLS(y, X).fit(cov_type="HC3")
        se_type = "HC3"

    models[zone] = model

    y_pred = model.predict(X)
    residuals = y - y_pred

    m = regression_metrics(y, y_pred, n_params=len(MODEL_VARS))
    m.update({
        "zone": zone,
        "zone_ru": zone_names_ru[zone],
        "n": len(zone_df),
        "n_features": len(MODEL_VARS),
        "aic": model.aic,
        "bic": model.bic,
        "se_type": se_type,
    })

    metrics_rows.append(m)

    conf_int = model.conf_int()

    for var in model.params.index:
        beta = model.params[var]

        coef_rows.append({
            "zone": zone,
            "zone_ru": zone_names_ru[zone],
            "variable": var,
            "feature_group": get_feature_group(var),
            "coef_log": beta,
            "effect_percent": (np.exp(beta) - 1) * 100,
            "std_err": model.bse[var],
            "t_value": model.tvalues[var],
            "p_value": model.pvalues[var],
            "ci_low": conf_int.loc[var, 0],
            "ci_high": conf_int.loc[var, 1],
            "abs_coef_log": abs(beta),
            "significant_5pct": model.pvalues[var] < 0.05,
            "significant_10pct": model.pvalues[var] < 0.10,
        })

    temp_pred = zone_df[[ZONE_COL, TARGET_COL]].copy()
    temp_pred["zone"] = zone
    temp_pred["zone_ru"] = zone_names_ru[zone]
    temp_pred["y_pred_zone_model"] = y_pred
    temp_pred["residual_zone_model"] = residuals
    temp_pred["abs_residual_zone_model"] = np.abs(residuals)

    if "spatial_group" in zone_df.columns:
        temp_pred["spatial_group"] = zone_df["spatial_group"]

    pred_rows.append(temp_pred)

zone_metrics = pd.DataFrame(metrics_rows)
zone_coefficients = pd.DataFrame(coef_rows)
zone_predictions = pd.concat(pred_rows, axis=0, ignore_index=True) if pred_rows else pd.DataFrame()

zone_metrics.to_csv(
    OUTPUT_DIR / "zone_models_no_interactions_metrics.csv",
    index=False,
    encoding="utf-8-sig"
)

zone_coefficients.to_csv(
    OUTPUT_DIR / "zone_models_no_interactions_coefficients.csv",
    index=False,
    encoding="utf-8-sig"
)

zone_predictions.to_csv(
    OUTPUT_DIR / "zone_models_no_interactions_predictions.csv",
    index=False,
    encoding="utf-8-sig"
)

display(zone_metrics.round(4))
display(
    zone_coefficients
    .sort_values(["zone", "abs_coef_log"], ascending=[True, False])
    .head(30)
    .round(4)
)

,r2,adj_r2,rmse_log,mae_log,mae_percent_approx,rmse_percent_approx,zone,zone_ru,n,n_features,aic,bic,se_type
0,0.5142,0.5115,0.3417,0.2394,27.0495,40.7308,core,центр,3695,21,2593.9497,2730.6739,cluster_by_spatial_group
1,0.4357,0.4344,0.2945,0.2126,23.6949,34.2426,semi_periphery,полупериферия,9747,21,3872.4150,4030.4787,cluster_by_spatial_group
2,0.3662,0.3650,0.2512,0.1761,19.2548,28.5550,periphery,периферия,11205,21,881.6698,1042.8003,cluster_by_spatial_group

,zone,zone_ru,variable,feature_group,coef_log,effect_percent,std_err,t_value,p_value,ci_low,ci_high,abs_coef_log,significant_5pct,significant_10pct
0,core,центр,const,Константа,13.2440,5.646501e+07,0.0387,342.2075,0.0000,13.1681,13.3198,13.2440,True,True
20,core,центр,z_x_centered,Пространственные контроли,-0.2125,-1.914070e+01,0.0428,-4.9588,0.0000,-0.2964,-0.1285,0.2125,True,True
21,core,центр,z_y_centered,Пространственные контроли,-0.2109,-1.901660e+01,0.0686,-3.0756,0.0021,-0.3453,-0.0765,0.2109,True,True
4,core,центр,z_building_newness,Внутренние характеристики квартиры и дома,0.1145,1.213500e+01,0.0110,10.4368,0.0000,0.0930,0.1360,0.1145,True,True
12,core,центр,z_log_clinics_1000m,Позитивные внешние характеристики,0.1138,1.205030e+01,0.0287,3.9635,0.0001,0.0575,0.1700,0.1138,True,True
1,core,центр,z_ln_total_area,Внутренние характеристики квартиры и дома,0.1121,1.186330e+01,0.0142,7.9097,0.0000,0.0843,0.1399,0.1121,True,True
2,core,центр,z_rooms_count,Внутренние характеристики квартиры и дома,-0.1104,-1.045370e+01,0.0149,-7.3987,0.0000,-0.1397,-0.0812,0.1104,True,True
10,core,центр,z_log_schools_1000m,Позитивные внешние характеристики,0.1062,1.120040e+01,0.0252,4.2083,0.0000,0.0567,0.1556,0.1062,True,True
5,core,центр,z_material_score,Внутренние характеристики квартиры и дома,0.0890,9.308100e+00,0.0139,6.4113,0.0000,0.0618,0.1162,0.0890,True,True
15,core,центр,z_water_proximity,Позитивные внешние характеристики,0.0544,5.585600e+00,0.0157,3.4607,0.0005,0.0236,0.0851,0.0544,True,True
18,core,центр,z_log_industrial_area_1000m,Негативные внешние характеристики,-0.0476,-4.645800e+00,0.0197,-2.4144,0.0158,-0.0862,-0.0090,0.0476,True,True
3,core,центр,z_floor_comfort_score,Внутренние характеристики квартиры и дома,0.0451,4.613800e+00,0.0089,5.0398,0.0000,0.0276,0.0626,0.0451,True,True
19,core,центр,z_waste_1000m,Негативные внешние характеристики,0.0372,3.790600e+00,0.0161,2.3135,0.0207,0.0057,0.0687,0.0372,True,True
9,core,центр,z_log_stops_500m,Транспортная доступность,-0.0326,-3.211200e+00,0.0149,-2.1916,0.0284,-0.0618,-0.0034,0.0326,True,True
13,core,центр,z_log_green_area_1000m,Позитивные внешние характеристики,0.0240,2.425400e+00,0.0097,2.4651,0.0137,0.0049,0.0430,0.0240,True,True
7,core,центр,z_mcd_proximity,Транспортная доступность,-0.0224,-2.218100e+00,0.0308,-0.7286,0.4662,-0.0828,0.0379,0.0224,False,False
8,core,центр,z_stop_proximity,Транспортная доступность,-0.0205,-2.026300e+00,0.0156,-1.3084,0.1907,-0.0511,0.0102,0.0205,False,False
17,core,центр,z_railway_300m,Негативные внешние характеристики,-0.0191,-1.892300e+00,0.0118,-1.6200,0.1052,-0.0422,0.0040,0.0191,False,False
14,core,центр,z_green_proximity,Позитивные внешние характеристики,0.0155,1.562500e+00,0.0156,0.9925,0.3210,-0.0151,0.0461,0.0155,False,False
16,core,центр,z_major_road_300m,Негативные внешние характеристики,0.0069,6.889000e-01,0.0137,0.5016,0.6160,-0.0200,0.0337,0.0069,False,False
6,core,центр,z_metro_mcc_proximity,Транспортная доступность,0.0046,4.637000e-01,0.0169,0.2737,0.7843,-0.0285,0.0378,0.0046,False,False
11,core,центр,z_log_kindergartens_1000m,Позитивные внешние характеристики,0.0021,2.109000e-01,0.0254,0.0829,0.9339,-0.0477,0.0519,0.0021,False,False
44,periphery,периферия,const,Константа,12.7855,3.570028e+07,0.0125,1026.7757,0.0000,12.7611,12.8099,12.7855,True,True
48,periphery,периферия,z_building_newness,Внутренние характеристики квартиры и дома,0.0860,8.980000e+00,0.0096,8.9594,0.0000,0.0672,0.1048,0.0860,True,True
50,periphery,периферия,z_metro_mcc_proximity,Транспортная доступность,0.0660,6.818500e+00,0.0075,8.7796,0.0000,0.0512,0.0807,0.0660,True,True
49,periphery,периферия,z_material_score,Внутренние характеристики квартиры и дома,0.0635,6.553800e+00,0.0054,11.7130,0.0000,0.0529,0.0741,0.0635,True,True
46,periphery,периферия,z_rooms_count,Внутренние характеристики квартиры и дома,-0.0561,-5.459400e+00,0.0081,-6.9058,0.0000,-0.0721,-0.0402,0.0561,True,True
64,periphery,периферия,z_x_centered,Пространственные контроли,-0.0468,-4.572200e+00,0.0057,-8.1983,0.0000,-0.0580,-0.0356,0.0468,True,True
56,periphery,периферия,z_log_clinics_1000m,Позитивные внешние характеристики,0.0332,3.377800e+00,0.0114,2.9132,0.0036,0.0109,0.0556,0.0332,True,True
47,periphery,периферия,z_floor_comfort_score,Внутренние характеристики квартиры и дома,0.0283,2.867000e+00,0.0033,8.6195,0.0000,0.0218,0.0347,0.0283,True,True

In [ ]:
block_coef = zone_coefficients[
    zone_coefficients["feature_group"].isin(feature_groups.keys())
].copy()

block_strength = (
    block_coef
    .groupby(["zone", "zone_ru", "feature_group"], as_index=False)
    .agg(
        block_strength_abs_beta=("abs_coef_log", "sum"),
        mean_abs_beta=("abs_coef_log", "mean"),
        n_features=("variable", "count"),
        n_significant_5pct=("significant_5pct", "sum"),
        n_significant_10pct=("significant_10pct", "sum"),
    )
)

block_strength["block_share"] = (
    block_strength["block_strength_abs_beta"]
    / block_strength.groupby("zone")["block_strength_abs_beta"].transform("sum")
)

block_strength["block_share_percent"] = block_strength["block_share"] * 100

block_strength = block_strength.sort_values(
    ["zone", "block_strength_abs_beta"],
    ascending=[True, False]
)

block_strength.to_csv(
    OUTPUT_DIR / "zone_models_no_interactions_block_strength.csv",
    index=False,
    encoding="utf-8-sig"
)

display(block_strength.round(4))

,zone,zone_ru,feature_group,block_strength_abs_beta,mean_abs_beta,n_features,n_significant_5pct,n_significant_10pct,block_share,block_share_percent
0,core,центр,Внутренние характеристики квартиры и дома,0.4712,0.0942,5,5,5,0.4818,48.1786
2,core,центр,Позитивные внешние характеристики,0.3159,0.0526,6,4,4,0.3230,32.2993
1,core,центр,Негативные внешние характеристики,0.1107,0.0277,4,2,2,0.1132,11.3245
3,core,центр,Транспортная доступность,0.0802,0.0200,4,1,1,0.0820,8.1976
4,periphery,периферия,Внутренние характеристики квартиры и дома,0.2366,0.0473,5,4,4,0.5445,54.4523
7,periphery,периферия,Транспортная доступность,0.0922,0.0230,4,2,2,0.2122,21.2217
6,periphery,периферия,Позитивные внешние характеристики,0.0750,0.0125,6,2,2,0.1727,17.2686
5,periphery,периферия,Негативные внешние характеристики,0.0307,0.0077,4,0,1,0.0706,7.0573
8,semi_periphery,полупериферия,Внутренние характеристики квартиры и дома,0.3589,0.0718,5,5,5,0.4819,48.1888
10,semi_periphery,полупериферия,Позитивные внешние характеристики,0.1779,0.0297,6,4,4,0.2389,23.8939
11,semi_periphery,полупериферия,Транспортная доступность,0.1271,0.0318,4,3,4,0.1707,17.0695
9,semi_periphery,полупериферия,Негативные внешние характеристики,0.0808,0.0202,4,2,2,0.1085,10.8477

In [ ]:
block_strength_pivot = block_strength.pivot(
    index="feature_group",
    columns="zone_ru",
    values="block_strength_abs_beta"
)

block_share_pivot = block_strength.pivot(
    index="feature_group",
    columns="zone_ru",
    values="block_share_percent"
)

ordered_cols = ["центр", "полупериферия", "периферия"]
block_strength_pivot = block_strength_pivot[[c for c in ordered_cols if c in block_strength_pivot.columns]]
block_share_pivot = block_share_pivot[[c for c in ordered_cols if c in block_share_pivot.columns]]

print("Сила блоков: сумма |β|")
display(block_strength_pivot.round(3))

print("Доля блоков внутри зоны, %")
display(block_share_pivot.round(1))

block_strength_pivot.to_csv(
    OUTPUT_DIR / "zone_models_no_interactions_block_strength_pivot.csv",
    encoding="utf-8-sig"
)

block_share_pivot.to_csv(
    OUTPUT_DIR / "zone_models_no_interactions_block_share_pivot.csv",
    encoding="utf-8-sig"
)

Сила блоков: сумма |β|

zone_ru                                    центр  полупериферия  периферия
feature_group
Внутренние характеристики квартиры и дома  0.471          0.359      0.237
Негативные внешние характеристики          0.111          0.081      0.031
Позитивные внешние характеристики          0.316          0.178      0.075
Транспортная доступность                   0.080          0.127      0.092

Доля блоков внутри зоны, %

zone_ru                                    центр  полупериферия  периферия
feature_group
Внутренние характеристики квартиры и дома   48.2           48.2       54.5
Негативные внешние характеристики           11.3           10.8        7.1
Позитивные внешние характеристики           32.3           23.9       17.3
Транспортная доступность                     8.2           17.1       21.2

In [ ]:
import os
import numpy as np
import pandas as pd
import statsmodels.api as sm
from pathlib import Path
from IPython.display import display, Markdown
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

ZONE_ORDER = ["periphery", "semi_periphery", "core"]
ZONE_NAMES_RU = {
    "core": "центр",
    "semi_periphery": "полупериферия",
    "periphery": "периферия",
}

MODEL_1_DIR = Path("model_6_diagnostics_new_zones")
MODEL_2_DIR = Path("zone_models_3_separate_no_interactions_linear_space")
MODEL_3_DIR = Path("model_7_no_internal_2rooms_middle_floor_general")
MODEL_4_DIR = Path("model_8_no_internal_2rooms_middle_floor_by_zone")

for path in [MODEL_1_DIR, MODEL_2_DIR, MODEL_3_DIR, MODEL_4_DIR]:
    path.mkdir(exist_ok=True)

def percent_from_log_coef(beta):
    if pd.isna(beta):
        return np.nan
    return (np.exp(beta) - 1) * 100

def rmse_local(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

def regression_metrics_local(y_true, y_pred, n_params=None):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    residuals = y_true - y_pred
    sse = np.sum(residuals ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)
    r2 = 1 - sse / sst if sst != 0 else np.nan
    rmse_value = np.sqrt(np.mean(residuals ** 2))
    mae_value = np.mean(np.abs(residuals))

    if n_params is not None and len(y_true) > n_params + 1:
        adj_r2 = 1 - (1 - r2) * (len(y_true) - 1) / (len(y_true) - n_params - 1)
    else:
        adj_r2 = np.nan

    return {
        "r2": r2,
        "adj_r2": adj_r2,
        "rmse_log": rmse_value,
        "mae_log": mae_value,
        "rmse_percent_approx": percent_from_log_coef(rmse_value),
        "mae_percent_approx": percent_from_log_coef(mae_value),
    }

def coefficient_table_from_model(model):
    conf_int = model.conf_int()
    out = pd.DataFrame({
        "variable": model.params.index,
        "coef_log": model.params.values,
        "std_err": model.bse.values,
        "t_value": model.tvalues.values,
        "p_value": model.pvalues.values,
        "ci_low": conf_int[0].values,
        "ci_high": conf_int[1].values,
    })
    out["effect_percent"] = percent_from_log_coef(out["coef_log"])
    out["ci_low_percent"] = percent_from_log_coef(out["ci_low"])
    out["ci_high_percent"] = percent_from_log_coef(out["ci_high"])
    out["abs_coef_log"] = out["coef_log"].abs()
    out["significant_5pct"] = out["p_value"] < 0.05
    out["significant_10pct"] = out["p_value"] < 0.10
    return out

def general_model_zone_effect_table(model, model_name, model_description, output_dir, filename):
    params = model.params
    bse = model.bse
    pvalues = model.pvalues
    conf_int = model.conf_int()

    rows = []
    zone_to_var = {
        "periphery": None,
        "semi_periphery": "zone_semi_periphery",
        "core": "zone_core",
    }

    for zone in ZONE_ORDER:
        var = zone_to_var[zone]
        if var is None:
            beta = 0.0
            std_err = np.nan
            p_value = np.nan
            ci_low = 0.0
            ci_high = 0.0
            note = "Базовая зона сравнения"
        else:
            beta = params.get(var, np.nan)
            std_err = bse.get(var, np.nan)
            p_value = pvalues.get(var, np.nan)
            if var in conf_int.index:
                ci_low = conf_int.loc[var, 0]
                ci_high = conf_int.loc[var, 1]
            else:
                ci_low = np.nan
                ci_high = np.nan
            note = "Эффект зоны относительно периферии при средних значениях стандартизированных признаков"

        rows.append({
            "model": model_name,
            "model_description": model_description,
            "zone": zone,
            "zone_ru": ZONE_NAMES_RU[zone],
            "baseline_zone": "periphery",
            "zone_term": var if var is not None else "baseline",
            "coef_log_relative_to_periphery": beta,
            "effect_percent_relative_to_periphery": percent_from_log_coef(beta),
            "std_err": std_err,
            "p_value": p_value,
            "ci_low": ci_low,
            "ci_high": ci_high,
            "ci_low_percent": percent_from_log_coef(ci_low),
            "ci_high_percent": percent_from_log_coef(ci_high),
            "interpretation_note": note,
        })

    table = pd.DataFrame(rows)
    table.to_csv(output_dir / filename, index=False, encoding="utf-8-sig")
    return table

def separate_models_zone_effect_table(models_dict, metrics_df, model_name, model_description, output_dir, filename):
    rows = []
    intercepts = {}

    for zone, model in models_dict.items():
        intercepts[zone] = model.params.get("const", np.nan)

    baseline = intercepts.get("periphery", np.nan)

    n_by_zone = {}
    if isinstance(metrics_df, pd.DataFrame) and "zone" in metrics_df.columns:
        n_col = "n" if "n" in metrics_df.columns else None
        if n_col is not None:
            n_by_zone = dict(zip(metrics_df["zone"], metrics_df[n_col]))

    for zone in ZONE_ORDER:
        intercept = intercepts.get(zone, np.nan)
        beta = intercept - baseline if pd.notna(intercept) and pd.notna(baseline) else np.nan
        rows.append({
            "model": model_name,
            "model_description": model_description,
            "zone": zone,
            "zone_ru": ZONE_NAMES_RU[zone],
            "baseline_zone": "periphery",
            "coef_log_relative_to_periphery": beta,
            "effect_percent_relative_to_periphery": percent_from_log_coef(beta),
            "intercept_log_price_m2": intercept,
            "expected_price_m2_at_reference": np.exp(intercept) if pd.notna(intercept) else np.nan,
            "n": n_by_zone.get(zone, np.nan),
            "interpretation_note": "Разница констант отдельных зональных моделей относительно периферии",
        })

    table = pd.DataFrame(rows)
    table.to_csv(output_dir / filename, index=False, encoding="utf-8-sig")
    return table

In [ ]:
DATA_PATH = MODEL_1_DIR / "model_6_modeling_data.csv"

if DATA_PATH.exists():
    analysis_df = pd.read_csv(DATA_PATH)
elif "df" in globals():
    analysis_df = df.copy()
else:
    raise FileNotFoundError("Не найден model_6_modeling_data.csv и переменная df.")

analysis_df = analysis_df.loc[:, ~analysis_df.columns.duplicated()].copy()

def coefficient_table_from_model(model):
    conf = np.asarray(model.conf_int())

    result = pd.DataFrame({
        "feature": model.params.index.to_numpy(),
        "coef_log": model.params.to_numpy(),
        "std_error": model.bse.to_numpy(),
        "t_value": model.tvalues.to_numpy(),
        "p_value": model.pvalues.to_numpy(),
        "ci_low": conf[:, 0],
        "ci_high": conf[:, 1],
    })

    result["coef_percent"] = np.where(
        result["feature"] == "const",
        np.nan,
        (np.exp(result["coef_log"]) - 1) * 100
    )

    result["abs_coef_log"] = result["coef_log"].abs()
    result["abs_coef_percent"] = result["coef_percent"].abs()

    result["significance"] = ""
    result.loc[result["p_value"] < 0.1, "significance"] = "*"
    result.loc[result["p_value"] < 0.05, "significance"] = "**"
    result.loc[result["p_value"] < 0.01, "significance"] = "***"

    result["significant_10pct"] = result["p_value"] < 0.1
    result["significant_5pct"] = result["p_value"] < 0.05
    result["significant_1pct"] = result["p_value"] < 0.01

    return result

TARGET_COL = "ln_price_m2"
ZONE_COL = "zone_name"

if "zone_core" not in analysis_df.columns:
    analysis_df["zone_core"] = (analysis_df[ZONE_COL] == "core").astype(int)

if "zone_semi_periphery" not in analysis_df.columns:
    analysis_df["zone_semi_periphery"] = (analysis_df[ZONE_COL] == "semi_periphery").astype(int)

if "rooms_count_num" not in analysis_df.columns and "rooms_count" in analysis_df.columns:
    analysis_df["rooms_count_num"] = pd.to_numeric(analysis_df["rooms_count"], errors="coerce")

if "floor_comfort_score" not in analysis_df.columns:
    if {"is_first_floor", "is_last_floor", "is_middle_floor"}.issubset(analysis_df.columns):
        analysis_df["floor_comfort_score"] = np.nan
        analysis_df.loc[analysis_df["is_first_floor"] == 1, "floor_comfort_score"] = 0
        analysis_df.loc[analysis_df["is_last_floor"] == 1, "floor_comfort_score"] = 0.5
        analysis_df.loc[analysis_df["is_middle_floor"] == 1, "floor_comfort_score"] = 1
    else:
        raise ValueError("Для фильтра не найден floor_comfort_score или признаки is_first_floor/is_last_floor/is_middle_floor.")

analysis_df["rooms_count_num"] = pd.to_numeric(analysis_df["rooms_count_num"], errors="coerce")
analysis_df["floor_comfort_score"] = pd.to_numeric(analysis_df["floor_comfort_score"], errors="coerce")

model_3_df = analysis_df[
    (analysis_df["rooms_count_num"] == 2)
    & (analysis_df["floor_comfort_score"] >= 0.999)
    & (analysis_df[ZONE_COL].isin(["core", "semi_periphery", "periphery"]))
].copy()

transport_vars_no_internal = [
    "z_metro_mcc_proximity",
    "z_mcd_proximity",
    "z_stop_proximity",
    "z_log_stops_500m",
]

positive_external_vars_no_internal = [
    "z_log_schools_1000m",
    "z_log_kindergartens_1000m",
    "z_log_clinics_1000m",
    "z_log_green_area_1000m",
    "z_green_proximity",
    "z_water_proximity",
]

negative_external_vars_no_internal = [
    "z_major_road_300m",
    "z_railway_300m",
    "z_log_industrial_area_1000m",
    "z_waste_1000m",
]

external_component_vars = (
    transport_vars_no_internal
    + positive_external_vars_no_internal
    + negative_external_vars_no_internal
)

external_component_vars = [col for col in external_component_vars if col in model_3_df.columns]

zone_vars_general = [
    "zone_core",
    "zone_semi_periphery",
]

interaction_vars_no_internal = []

for component in external_component_vars:
    for zone_var in zone_vars_general:
        new_col = f"{component}_x_{zone_var}"
        model_3_df[new_col] = (
            pd.to_numeric(model_3_df[component], errors="coerce")
            * pd.to_numeric(model_3_df[zone_var], errors="coerce")
        )
        interaction_vars_no_internal.append(new_col)

spatial_vars_general = [
    "z_x_centered",
    "z_y_centered",
    "z_x2",
    "z_y2",
    "z_xy",
    "z_log_dist_to_core_center",
]

spatial_vars_general = [col for col in spatial_vars_general if col in model_3_df.columns]

MODEL_3_VARS = (
    zone_vars_general
    + external_component_vars
    + interaction_vars_no_internal
    + spatial_vars_general
)

MODEL_3_VARS = list(dict.fromkeys(MODEL_3_VARS))

for col in [TARGET_COL] + MODEL_3_VARS:
    model_3_df[col] = pd.to_numeric(model_3_df[col], errors="coerce")

for col in MODEL_3_VARS:
    model_3_df[col] = model_3_df[col].fillna(model_3_df[col].median())

model_3_df = model_3_df.dropna(subset=[TARGET_COL, ZONE_COL] + MODEL_3_VARS).copy()

print("Модель 3: общая модель без внутренних характеристик")
print("Фильтр: только 2-комнатные, не первый и не последний этаж")
print("N:", len(model_3_df))
print("Распределение по зонам:")
display(model_3_df[ZONE_COL].value_counts())
print("Число признаков:", len(MODEL_3_VARS))

X_model_3 = sm.add_constant(model_3_df[MODEL_3_VARS], has_constant="add")
y_model_3 = model_3_df[TARGET_COL]

model_3_general_no_internal = sm.OLS(y_model_3, X_model_3).fit(cov_type="HC3")

y_model_3_pred = model_3_general_no_internal.predict(X_model_3)

model_3_metrics = pd.DataFrame([{
    "model": "model_3_general_no_internal_2rooms_middle_floor",
    "sample": "2 rooms, not first floor, not last floor",
    "n": len(model_3_df),
    "n_features": len(MODEL_3_VARS),
    **regression_metrics_local(
        y_model_3,
        y_model_3_pred,
        n_params=len(MODEL_3_VARS)
    ),
    "aic": model_3_general_no_internal.aic,
    "bic": model_3_general_no_internal.bic,
}])

model_3_coefficients = coefficient_table_from_model(model_3_general_no_internal)

model_3_metrics.to_csv(
    MODEL_3_DIR / "model_3_general_no_internal_metrics.csv",
    index=False,
    encoding="utf-8-sig"
)

model_3_coefficients.to_csv(
    MODEL_3_DIR / "model_3_general_no_internal_coefficients.csv",
    index=False,
    encoding="utf-8-sig"
)

model_3_df[[TARGET_COL, ZONE_COL] + MODEL_3_VARS].to_csv(
    MODEL_3_DIR / "model_3_general_no_internal_modeling_data.csv",
    index=False,
    encoding="utf-8-sig"
)

print(model_3_general_no_internal.summary())
display(model_3_metrics.round(4))
display(
    model_3_coefficients
    .sort_values("abs_coef_log", ascending=False)
    .head(30)
    .round(4)
)

Модель 3: общая модель без внутренних характеристик
Фильтр: только 2-комнатные, не первый и не последний этаж
N: 8424
Распределение по зонам:

zone_name
periphery         3701
semi_periphery    3419
core              1304
Name: count, dtype: int64

Число признаков: 50
                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_price_m2   R-squared:                       0.580
Model:                            OLS   Adj. R-squared:                  0.578
Method:                 Least Squares   F-statistic:                     200.9
Date:                Sun, 07 Jun 2026   Prob (F-statistic):               0.00
Time:                        14:06:27   Log-Likelihood:                -699.63
No. Observations:                8424   AIC:                             1501.
Df Residuals:                    8373   BIC:                             1860.
Df Model:                          50
Covariance Type:                  HC3
=====================================================================================================================
                                                        coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------------
const                                                13.0041      0.010   1351.030      0.000      12.985      13.023
zone_core                                            -0.0153      0.030     -0.510      0.610      -0.074       0.043
zone_semi_periphery                                  -0.0246      0.012     -2.071      0.038      -0.048      -0.001
z_metro_mcc_proximity                                 0.0513      0.004     11.738      0.000       0.043       0.060
z_mcd_proximity                                      -0.0241      0.005     -5.190      0.000      -0.033      -0.015
z_stop_proximity                                     -0.0064      0.005     -1.401      0.161      -0.015       0.003
z_log_stops_500m                                     -0.0253      0.005     -5.365      0.000      -0.035      -0.016
z_log_schools_1000m                                  -0.0627      0.006    -10.969      0.000      -0.074      -0.052
z_log_kindergartens_1000m                             0.0294      0.006      5.205      0.000       0.018       0.041
z_log_clinics_1000m                                   0.0093      0.006      1.483      0.138      -0.003       0.022
z_log_green_area_1000m                                0.0083      0.006      1.464      0.143      -0.003       0.019
z_green_proximity                                    -0.0062      0.005     -1.352      0.176      -0.015       0.003
z_water_proximity                                     0.0132      0.005      2.761      0.006       0.004       0.023
z_major_road_300m                                    -0.0029      0.004     -0.648      0.517      -0.012       0.006
z_railway_300m                                       -0.0133      0.005     -2.590      0.010      -0.023      -0.003
z_log_industrial_area_1000m                          -0.0049      0.004     -1.164      0.244      -0.013       0.003
z_waste_1000m                                        -0.0037      0.004     -0.904      0.366      -0.012       0.004
z_metro_mcc_proximity_x_zone_core                    -0.0053      0.014     -0.384      0.701      -0.032       0.022
z_metro_mcc_proximity_x_zone_semi_periphery          -0.0194      0.007     -2.604      0.009      -0.034      -0.005
z_mcd_proximity_x_zone_core                          -0.1150      0.015     -7.706      0.000      -0.144      -0.086
z_mcd_proximity_x_zone_semi_periphery                 0.0180      0.008      2.359      0.018       0.003       0.033
z_stop_proximity_x_zone_core                         -0.0248      0.011     -2.206      0.027      -0.047      -0.003
z_stop_proximity_x_zone_semi_periphery               -0.0368      0.007     -5.311      0.000      -0.050      -0.023
z_log_stops_500m_x_zone_core                          0.0013      0.012      0.112      0.911      -0.022       0.025
z_log_stops_500m_x_zone_semi_periphery               -0.0125      0.008     -1.605      0.109      -0.028       0.003
z_log_schools_1000m_x_zone_core                       0.0763      0.017      4.559      0.000       0.044       0.109
z_log_schools_1000m_x_zone_semi_periphery             0.0763      0.009      8.852      0.000       0.059       0.093
z_log_kindergartens_1000m_x_zone_core                 0.0414      0.017      2.505      0.012       0.009       0.074
z_log_kindergartens_1000m_x_zone_semi_periphery      -0.0772      0.009     -8.496      0.000      -0.095      -0.059
z_log_clinics_1000m_x_zone_core                      -0.0849      0.021     -4.112      0.000      -0.125      -0.044
z_log_clinics_1000m_x_zone_semi_periphery            -0.0093      0.010     -0.892      0.372      -0.030       0.011
z_log_green_area_1000m_x_zone_core                    0.0092      0.009      1.010      0.312      -0.009       0.027
z_log_green_area_1000m_x_zone_semi_periphery         -0.0014      0.008     -0.182      0.855      -0.017       0.014
z_green_proximity_x_zone_core                         0.0097      0.013      0.760      0.447      -0.015       0.035
z_green_proximity_x_zone_semi_periphery               0.0381      0.008      4.680      0.000       0.022       0.054
z_water_proximity_x_zone_core                         0.0172      0.011      1.532      0.125      -0.005       0.039
z_water_proximity_x_zone_semi_periphery               0.0211      0.007      3.030      0.002       0.007       0.035
z_major_road_300m_x_zone_core                        -0.0102      0.011     -0.966      0.334      -0.031       0.010
z_major_road_300m_x_zone_semi_periphery               0.0194      0.007      2.913      0.004       0.006       0.032
z_railway_300m_x_zone_core                            0.0203      0.011      1.888      0.059      -0.001       0.041
z_railway_300m_x_zone_semi_periphery                  0.0117      0.007      1.617      0.106      -0.002       0.026
z_log_industrial_area_1000m_x_zone_core              -0.0161      0.013     -1.257      0.209      -0.041       0.009
z_log_industrial_area_1000m_x_zone_semi_periphery    -0.0300      0.008     -3.910      0.000      -0.045      -0.015
z_waste_1000m_x_zone_core                             0.0423      0.011      3.917      0.000       0.021       0.063
z_waste_1000m_x_zone_semi_periphery                  -0.0204      0.007     -3.138      0.002      -0.033      -0.008
z_x_centered                                         -0.0815      0.003    -23.384      0.000      -0.088      -0.075
z_y_centered                                         -0.0264      0.003     -7.924      0.000      -0.033      -0.020
z_x2                                                 -0.0356      0.006     -6.332      0.000      -0.047      -0.025
z_y2                                                 -0.0480      0.007     -7.239      0.000      -0.061      -0.035
z_xy                                                 -0.0117      0.003     -3.866      0.000      -0.018      -0.006
z_log_dist_to_core_center                            -0.2693      0.017    -15.974      0.000      -0.302      -0.236
==============================================================================
Omnibus:                      928.311   Durbin-Watson:                   1.224
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5347.374
Skew:                          -0.370   Prob(JB):                         0.00
Kurtosis:                       6.832   Cond. No.                         19.6
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

,model,sample,n,n_features,r2,adj_r2,rmse_log,mae_log,rmse_percent_approx,mae_percent_approx,aic,bic
0,model_3_general_no_internal_2rooms_middle_floor,"2 rooms, not first floor, not last floor",8424,50,0.5805,0.578,0.2629,0.1931,30.0729,21.2992,1501.2586,1860.2395

,feature,coef_log,std_error,t_value,p_value,ci_low,ci_high,coef_percent,abs_coef_log,abs_coef_percent,significance,significant_10pct,significant_5pct,significant_1pct
0,const,13.0041,0.0096,1351.0304,0.0000,12.9852,13.0229,NaN,13.0041,NaN,***,True,True,True
50,z_log_dist_to_core_center,-0.2693,0.0169,-15.9737,0.0000,-0.3023,-0.2362,-23.6049,0.2693,23.6049,***,True,True,True
19,z_mcd_proximity_x_zone_core,-0.1150,0.0149,-7.7061,0.0000,-0.1442,-0.0857,-10.8604,0.1150,10.8604,***,True,True,True
29,z_log_clinics_1000m_x_zone_core,-0.0849,0.0206,-4.1124,0.0000,-0.1254,-0.0444,-8.1401,0.0849,8.1401,***,True,True,True
45,z_x_centered,-0.0815,0.0035,-23.3838,0.0000,-0.0883,-0.0747,-7.8283,0.0815,7.8283,***,True,True,True
28,z_log_kindergartens_1000m_x_zone_semi_periphery,-0.0772,0.0091,-8.4959,0.0000,-0.0950,-0.0594,-7.4255,0.0772,7.4255,***,True,True,True
26,z_log_schools_1000m_x_zone_semi_periphery,0.0763,0.0086,8.8524,0.0000,0.0594,0.0932,7.9328,0.0763,7.9328,***,True,True,True
25,z_log_schools_1000m_x_zone_core,0.0763,0.0167,4.5586,0.0000,0.0435,0.1091,7.9314,0.0763,7.9314,***,True,True,True
7,z_log_schools_1000m,-0.0627,0.0057,-10.9694,0.0000,-0.0739,-0.0515,-6.0811,0.0627,6.0811,***,True,True,True
3,z_metro_mcc_proximity,0.0513,0.0044,11.7384,0.0000,0.0427,0.0598,5.2598,0.0513,5.2598,***,True,True,True
48,z_y2,-0.0480,0.0066,-7.2386,0.0000,-0.0610,-0.0350,-4.6905,0.0480,4.6905,***,True,True,True
43,z_waste_1000m_x_zone_core,0.0423,0.0108,3.9173,0.0001,0.0211,0.0634,4.3165,0.0423,4.3165,***,True,True,True
27,z_log_kindergartens_1000m_x_zone_core,0.0414,0.0165,2.5048,0.0123,0.0090,0.0738,4.2285,0.0414,4.2285,**,True,True,False
34,z_green_proximity_x_zone_semi_periphery,0.0381,0.0081,4.6798,0.0000,0.0222,0.0541,3.8864,0.0381,3.8864,***,True,True,True
22,z_stop_proximity_x_zone_semi_periphery,-0.0368,0.0069,-5.3113,0.0000,-0.0504,-0.0232,-3.6140,0.0368,3.6140,***,True,True,True
47,z_x2,-0.0356,0.0056,-6.3318,0.0000,-0.0467,-0.0246,-3.5009,0.0356,3.5009,***,True,True,True
42,z_log_industrial_area_1000m_x_zone_semi_periphery,-0.0300,0.0077,-3.9098,0.0001,-0.0450,-0.0149,-2.9515,0.0300,2.9515,***,True,True,True
8,z_log_kindergartens_1000m,0.0294,0.0057,5.2050,0.0000,0.0183,0.0405,2.9863,0.0294,2.9863,***,True,True,True
46,z_y_centered,-0.0264,0.0033,-7.9245,0.0000,-0.0329,-0.0198,-2.6014,0.0264,2.6014,***,True,True,True
6,z_log_stops_500m,-0.0253,0.0047,-5.3650,0.0000,-0.0346,-0.0161,-2.4999,0.0253,2.4999,***,True,True,True
21,z_stop_proximity_x_zone_core,-0.0248,0.0112,-2.2063,0.0274,-0.0468,-0.0028,-2.4490,0.0248,2.4490,**,True,True,False
2,zone_semi_periphery,-0.0246,0.0119,-2.0708,0.0384,-0.0480,-0.0013,-2.4334,0.0246,2.4334,**,True,True,False
4,z_mcd_proximity,-0.0241,0.0046,-5.1895,0.0000,-0.0332,-0.0150,-2.3827,0.0241,2.3827,***,True,True,True
36,z_water_proximity_x_zone_semi_periphery,0.0211,0.0070,3.0297,0.0024,0.0074,0.0347,2.1290,0.0211,2.1290,***,True,True,True
44,z_waste_1000m_x_zone_semi_periphery,-0.0204,0.0065,-3.1384,0.0017,-0.0332,-0.0077,-2.0229,0.0204,2.0229,***,True,True,True
39,z_railway_300m_x_zone_core,0.0203,0.0108,1.8878,0.0591,-0.0008,0.0414,2.0543,0.0203,2.0543,*,True,False,False
38,z_major_road_300m_x_zone_semi_periphery,0.0194,0.0067,2.9133,0.0036,0.0064,0.0325,1.9610,0.0194,1.9610,***,True,True,True
18,z_metro_mcc_proximity_x_zone_semi_periphery,-0.0194,0.0075,-2.6040,0.0092,-0.0340,-0.0048,-1.9230,0.0194,1.9230,***,True,True,True
20,z_mcd_proximity_x_zone_semi_periphery,0.0180,0.0076,2.3589,0.0183,0.0031,0.0330,1.8209,0.0180,1.8209,**,True,True,False
35,z_water_proximity_x_zone_core,0.0172,0.0112,1.5321,0.1255,-0.0048,0.0391,1.7304,0.0172,1.7304,,False,False,False

In [ ]:
all_zone_effects = pd.concat(
    [
        model_1_zone_effect,
        model_2_zone_effect,
        model_3_zone_effect,
        model_4_zone_effect,
    ],
    axis=0,
    ignore_index=True,
)

all_zone_effects_out = all_zone_effects[[
    "model",
    "model_description",
    "zone_ru",
    "baseline_zone",
    "coef_log_relative_to_periphery",
    "effect_percent_relative_to_periphery",
    "interpretation_note",
]].copy()

all_zone_effects_out = all_zone_effects_out.rename(columns={
    "model": "Модель",
    "model_description": "Описание модели",
    "zone_ru": "Зона",
    "baseline_zone": "Базовая зона сравнения",
    "coef_log_relative_to_periphery": "Коэффициент зоны в лог-модели / разница констант",
    "effect_percent_relative_to_periphery": "Эффект зоны к периферии, %",
    "interpretation_note": "Как считать",
})

all_zone_effects_out.to_csv(
    "all_4_models_zone_effects_coefficients_percent.csv",
    index=False,
    encoding="utf-8-sig",
)

display(all_zone_effects_out.round(4))
print("Сводная таблица сохранена: all_4_models_zone_effects_coefficients_percent.csv")

,Модель,Описание модели,Зона,Базовая зона сравнения,Коэффициент зоны в лог-модели / разница констант,"Эффект зоны к периферии, %",Как считать
0,model_1_general_full_with_interactions,"Общая модель с внутренними характеристиками, з...",периферия,periphery,0.0000,0.0000,Базовая зона сравнения
1,model_1_general_full_with_interactions,"Общая модель с внутренними характеристиками, з...",полупериферия,periphery,-0.0028,-0.2840,Эффект зоны относительно периферии при средних...
2,model_1_general_full_with_interactions,"Общая модель с внутренними характеристиками, з...",центр,periphery,0.0205,2.0716,Эффект зоны относительно периферии при средних...
3,model_2_three_zone_models_full,Три отдельные зональные модели с внутренними х...,периферия,periphery,0.0000,0.0000,Разница констант отдельных зональных моделей о...
4,model_2_three_zone_models_full,Три отдельные зональные модели с внутренними х...,полупериферия,periphery,0.2300,25.8538,Разница констант отдельных зональных моделей о...
5,model_2_three_zone_models_full,Три отдельные зональные модели с внутренними х...,центр,periphery,0.4585,58.1639,Разница констант отдельных зональных моделей о...
6,model_3_general_no_internal_2rooms_middle_floor,Общая модель без внутренних характеристик; тол...,периферия,periphery,0.0000,0.0000,Базовая зона сравнения
7,model_3_general_no_internal_2rooms_middle_floor,Общая модель без внутренних характеристик; тол...,полупериферия,periphery,-0.0246,-2.4334,Эффект зоны относительно периферии при средних...
8,model_3_general_no_internal_2rooms_middle_floor,Общая модель без внутренних характеристик; тол...,центр,periphery,-0.0153,-1.5136,Эффект зоны относительно периферии при средних...
9,model_4_three_zone_models_no_internal_2rooms_m...,Три отдельные зональные модели без внутренних ...,периферия,periphery,0.0000,0.0000,Разница констант отдельных зональных моделей о...
10,model_4_three_zone_models_no_internal_2rooms_m...,Три отдельные зональные модели без внутренних ...,полупериферия,periphery,0.2886,33.4590,Разница констант отдельных зональных моделей о...
11,model_4_three_zone_models_no_internal_2rooms_m...,Три отдельные зональные модели без внутренних ...,центр,periphery,0.5325,70.3153,Разница констант отдельных зональных моделей о...

Сводная таблица сохранена: all_4_models_zone_effects_coefficients_percent.csv